### PR TITLE
fix: don't copy auth bytes from oauth filter request to failed response

### LINKED ISSUE #2545: Returning client auth_bytes suspicious
> It makes no sense to return the authBytes which the client sent in its request back to the client. I think we should be just leaving the authBytes unset in this case.

_Originally posted by @tombentley  in https://github.com/kroxylicious/kroxylicious/pull/2526#discussion_r2255709817

> Good spot.  I didn't notice that when I initially reviewed the submission.  From a quick look at https://datatracker.ietf.org/doc/html/rfc7628#page-9, it looks wrong.  Let separate this into a separate issue.

_Originally posted by @k-wall in https://github.com/kroxylicious/kroxylicious/pull/2526#discussion_r2256336257_

### PR DESCRIPTION
**Pull request by piotrpdev**
### Type of change

- Fix

### Description

Fix `OauthBearerValidationFilter` unnecessarily copying the authentication bytes from an incoming request to a failed response.

### Additional Context

Resolves #2545.

I'm assuming this issue was only talking about filters.

For [`setAuthBytes(authBytes)` in `KafkaAuthnHandler`](https://github.com/kroxylicious/kroxylicious/blob/dc157ee0962c9fbd91866c233af598732494cf88/kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaAuthnHandler.java#L367):
- Removing it or changing it to `setAuthBytes(Bytes.EMPTY)` causes [`responseBytes` to be empty](https://github.com/kroxylicious/kroxylicious/blob/dc157ee0962c9fbd91866c233af598732494cf88/kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/KafkaAuthnHandlerTest.java#L291), failing the [`ScramMessages.ServerFirstMessage` check in `KafkaAuthnHandlerTest`](https://github.com/kroxylicious/kroxylicious/blob/dc157ee0962c9fbd91866c233af598732494cf88/kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/KafkaAuthnHandlerTest.java#L402) i.e. `KafkaAuthnHandlerTest.testSaslScramSha256SuccessfulAuth:509->doSaslScramShaAuth:402 » Sasl Invalid SCRAM server first message format`.
- Changing it to `setAuthBytes(null)` results in `responseBytes` being null `KafkaAuthnHandlerTest.testSaslScramSha256SuccessfulAuth:509->doSaslScramShaAuth:422->assertAuthnSuccess:448 expected: <AUTHN_SUCCESS> but was: <FRAMED_SASL_AUTHENTICATE>`

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [x] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [x] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/testplugins/SaslPlainTerminationFilter.java [hunk 1]
```diff
@@ -86,12 +86,11 @@ CompletionStage<RequestFilterResult> onSaslHandshakeRequest(SaslHandshakeRequest
 
     CompletionStage<RequestFilterResult> onSaslAuthenticateRequest(SaslAuthenticateRequestData request,
                                                                    FilterContext context) {
-        byte[] bytes = new byte[0];
         Errors error;
         String errorMessage;
 
         try {
-            bytes = doEvaluateResponse(context, request.authBytes());
```
Comment (tombentley) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/testplugins/SaslPlainTerminationFilter.java:94]: I think I'd rather not change what we're doing for SASL `PLAIN`, though what you've done here is not incorrect. 

For the `OAUTH_BEARER` case, the existing code is obviously wrong, because the `authBytes` being set on the response is what the client sent. That's just now how SASL works.

For `PLAIN` what we're doing in `doEvaluateResponse` is getting the response `authBytes` from a `SaslServer` and setting that. Now this filter is specific to SASL `PLAIN`, where we know exchange is simply:

1. Client sends password to server
2. Server validated password, and we're done. 

So we know _a priori_ that the `SaslServer` is not returning anything. However the fact is that the `SaslPlainTerminationFilter` _is delegating_ to the `SaslServer`, so I think the filter short-circuiting the logic is a bit dubious. It should fulfil it's side of the contract offered by `SaslServer`. 

At the end of the day neither is incorrect, of course. 

Eventually, I'd like for us to end up with a `SaslTerminationFilter` with pluggable mechanism (as Keith has done for SASL inspection), and at that point we'd definitely need to be using the `SaslServer` correctly, without building mechanism-specific knowledge into the filter itself.

**Review by tombentley — COMMENTED** [review]
Thanks @piotrpdev I had one comment about `PLAIN`.

@callaertanthony you might want to give this a quick review too.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/testplugins/SaslPlainTerminationFilter.java (hunk 1 above)
Comment (piotrpdev) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/testplugins/SaslPlainTerminationFilter.java:94]: Reverted in https://github.com/kroxylicious/kroxylicious/pull/2821/commits/964d7d4fda5e25e3692df68bd21db2ecd4f43d18

**Comment by k-wall** [comment]
LGTM.  Couple of nits:

Could you bolster the unit tests?

For example `willShortCircuitAuthenticateIfNoHandshakeBefore` needs the following in the assertArg block.

```
            assertThat(((SaslAuthenticateResponseData) actualResponse).authBytes()).isEmpty();
```

The use of the word refactor is imprecise.    Refactoring is to change the code without changing behaviour.  This is a bug fix - it changes behaviour.  

Also we want the summary to communicate the essence of the change "omit setAuthBytes() from filter response" is true but too broad.  Can you succinctly capture the delta in a single sentence?   It is worth the effort as it saves other contributor mental work (which should be a net win).

Finally, it deserving of change log.

If you like, add yourself to https://github.com/kroxylicious/kroxylicious/blob/main/CONTRIBUTORS.md.  Part of this change is just fine.

Thanks @piotrpdev
