### PR TITLE
test(operator): fix race condition in Route status update IT test

### LINKED ISSUE #3673: bug: Non-Deterministic Test `KafkaProxyReconcilerIT` on MicroShift
A test failed non-deterministically in GitHub Actions:

## failed test

Job: Operator integration & system tests on MicroShift

Test: `io.kroxylicious.kubernetes.operator.reconciler.kafkaproxy.KafkaProxyReconcilerIT.deploymentChecksumUpdatesWhenOpenshiftRouteHostAssigned`

Build: https://github.com/kroxylicious/kroxylicious/actions/runs/24218917776/job/70707372281

## stack trace

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://api.crc.testing:6443/apis/route.openshift.io/v1/namespaces/kafkaproxyreconcilerit-deploymentchecksumupdateswhenopens-21db4/routes/bar-bootstrap/status. Message: Operation cannot be fulfilled on routes.route.openshift.io "bar-bootstrap": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=route.openshift.io, kind=routes, name=bar-bootstrap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on routes.route.openshift.io "bar-bootstrap": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:205)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:419)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:397)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:776)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:231)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:236)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patchStatus(HasMetadataOperation.java:241)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patchStatus(HasMetadataOperation.java:44)
	at io.kroxylicious.kubernetes.operator.LocallyRunningOperatorRbacHandler$1.patchStatus(LocallyRunningOperatorRbacHandler.java:231)
	at io.kroxylicious.kubernetes.operator.reconciler.kafkaproxy.KafkaProxyReconcilerIT.deploymentChecksumUpdatesWhenOpenshiftRouteHostAssigned(KafkaProxyReconcilerIT.java:990)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://api.crc.testing:6443/apis/route.openshift.io/v1/namespaces/kafkaproxyreconcilerit-deploymentchecksumupdateswhenopens-21db4/routes/bar-bootstrap/status. Message: Operation cannot be fulfilled on routes.route.openshift.io "bar-bootstrap": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=route.openshift.io, kind=routes, name=bar-bootstrap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on routes.route.openshift.io "bar-bootstrap": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:642)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:622)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:582)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:141)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at io.fabric8.kubernetes.client.utils.AsyncUtils.lambda$retryWithExponentialBackoff$3(AsyncUtils.java:91)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- [x] Bugfix
- [ ] Enhancement / new feature
- [ ] Refactoring
- [ ] Documentation

### Description

Fixes non-deterministic test failure in `KafkaProxyReconcilerIT.deploymentChecksumUpdatesWhenOpenshiftRouteHostAssigned` that was failing with 409 Conflict errors when racing with the OpenShift IngressController.

**Changes:**
- Changed from `patchStatus()` to `editStatus()` which automatically handles resource version conflicts through retries
- Use distinct host value `"another.invalid"` to ensure updates are never no-ops (even if IngressController has already set the expected host)
- Improved variable naming and code clarity

**Test validation:**
- Verified the fix works correctly against a local CRC cluster
- Test passes consistently without 409 errors

### Additional Context

The test was failing non-deterministically in CI (MicroShift) because both the test and the OpenShift IngressController were attempting to update the Route's status concurrently, causing resource version conflicts. The `editStatus()` method in Fabric8 Kubernetes client handles these conflicts automatically by retrying with updated resource versions, making the test reliable.

Fixes #3673

### Checklist

- [x] PR raised from a fork of this repository and made from a branch rather than main.
- [x] Write tests (this is a test fix - the test itself validates the change)
- [ ] Update documentation (not applicable - test-only change)
- [x] Make sure all unit/integration tests pass (verified locally on CRC)
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [x] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, trigger the performance test suite. Ensure that any degradations to performance numbers are understood and justified. (not applicable - test-only change)
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (not applicable - test-only change)
- [x] If AI tools assisted with code changes, ensure commit messages include `Assisted-by:` trailer.

### CODE REVIEW

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/reconciler/kafkaproxy/KafkaProxyReconcilerIT.java [hunk 1]
```diff
@@ -976,24 +976,28 @@ void deploymentChecksumUpdatesWhenOpenshiftRouteHostAssigned() {
...
+        var observedChecksum = deploymentPodTemplateChecksum(proxy);
 
-        // When - OpenShift assigns a host to the bootstrap route
-        Route bootstrapRoute = testActor.get(Route.class, bootstrapRouteName);
-        Route routeWithHost = new RouteBuilder(bootstrapRoute)
+        // When
+
+        // The test is racing with the Ingress controller. We don't know if the ingress
+        // controller will have updated the resource or not yet. We make an update to
+        // the Route that are certain will be different to that made by the controller
```
Comment (tombentley) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/reconciler/kafkaproxy/KafkaProxyReconcilerIT.java]:
```suggestion
        // the Route that we are certain will be different to that made by the controller
```

**Review by tombentley — APPROVED** [review]
LGTM, thanks @k-wall

**Comment by tombentley** [comment]
@k-wall it appears that `OperatorChangeDetectionST` now fails:

```
Error:  io.kroxylicious.systemtests.OperatorChangeDetectionST.shouldUpdateDeploymentWhenKafkaProxyIngressChanges(String) -- Time elapsed: 48.58 s <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [9000] milliseconds for [VirtualKafkaCluster] with name:[null] in namespace [operator-chan-st-9eb248].
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:958)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:98)
	at io.kroxylicious.systemtests.OperatorChangeDetectionST.lambda$getInitialChecksum$15(OperatorChangeDetectionST.java:391)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by k-wall** [comment]
> @k-wall it appears that `OperatorChangeDetectionST` now fails:
> 
> 
> 
> ```
> 
> Error:  io.kroxylicious.systemtests.OperatorChangeDetectionST.shouldUpdateDeploymentWhenKafkaProxyIngressChanges(String) -- Time elapsed: 48.58 s <<< ERROR!
> 
> io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [9000] milliseconds for [VirtualKafkaCluster] with name:[null] in namespace [operator-chan-st-9eb248].
> 
> 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:958)
> 
> 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:98)
> 
> 	at io.kroxylicious.systemtests.OperatorChangeDetectionST.lambda$getInitialChecksum$15(OperatorChangeDetectionST.java:391)
> 
> 	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
> 
> 	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
> 
> 	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
> 
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> 
> ```

Sigh! I'll take a look!

**Comment by k-wall** [comment]
The `OperatorChangeDetectionST` failure (system test) is unrelated to the `KafkaProxyReconcilerIT` fix (integration test) in this PR.

This is a known flaky test - I've logged it as #3804. The system test intermittently times out waiting for VirtualKafkaCluster resources in CI (similar to the previously closed #2150).

The integration test fix in this PR is valid and addresses a separate issue.
