### PR TITLE
fix: messages enter Filter chain before Transport Subject built

### LINKED ISSUE #3745: bug: Non-Deterministic Test PluginTlsApiIT.clientTlsContextMutualTls
A test failed non-deterministically in GitHub Actions:

## failed test

`io.kroxylicious.it.PluginTlsApiIT.clientTlsContextMutualTls(Config, Topic)[3]`

https://github.com/kroxylicious/kroxylicious/actions/runs/24558672398/job/71801781072?pr=3724

## stack trace

```
[ERROR] Tests run: 15, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 57.27 s <<< FAILURE! -- in io.kroxylicious.it.PluginTlsApiIT
[ERROR] io.kroxylicious.it.PluginTlsApiIT.clientTlsContextMutualTls(Config, Topic)[3] -- Time elapsed: 3.699 s <<< FAILURE!
org.assertj.core.error.AssertJMultipleFailuresError: 

[single header with key ClientAuthAwareLawyerFilter#authenticatedSubject value] (1 failure)
-- failure 1 --
expected: "Subject[principals=[User[name=CN=client, OU=Dev, O=kroxylicious.io, L=null, ST=null, C=US, emailAddress=clientTest@kroxylicious.io]]]"
 but was: "Subject[principals=[]]"
at HeaderAssert.lambda$hasValueEqualTo$0(HeaderAssert.java:59)
	at io.kroxylicious.test.assertj.HeaderAssert.hasStringValueSatisfying(HeaderAssert.java:80)
	at io.kroxylicious.test.assertj.HeaderAssert.hasValueEqualTo(HeaderAssert.java:59)
	at io.kroxylicious.it.PluginTlsApiIT.assertClientTlsContext(PluginTlsApiIT.java:209)
	at io.kroxylicious.it.PluginTlsApiIT.clientTlsContextMutualTls(PluginTlsApiIT.java:92)
```

The test expected the Subject to contain principals with client certificate information (from mutual TLS authentication), but the Subject had an empty principals list, suggesting a race condition or timing issue in subject building from transport information.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Fixes #3745

One thing that must happen to resolve #3745 is we have to buffer the messages before the Filter chain. This prevents Filters being exposed to messages before the PCSM decides it is time.

To do this we change things so that Filters are installed AFTER the KafkaProxyFrontendHandler, so that it's buffering logic can prevent messages entering the Filters.

We also delay the forwarding of buffered messages until the client is unblocked. We had established logic that toggled autoread to true after both the backend server became active and the transport subject was created. With this change we additionally forward on all buffered messages at this point.

* Filters are moved from before the Frontend Handler to after the Frontend Handler. This allows the existing buffering in the Frontend Handler to prevent messages entering the Filter Chain.
* A FilterChainCompletionHandler is installed at the end of the pipeline, responsible for simply telling the PCSM about messages that have emerged from the Filter Chain.
* If the PCSM is told about a client message reaching the FilterChainCompletionHandler but the state is not Forward we transition to Closed due to illegal state.
* FilterHandlers no longer fire channelReadComplete. The PCSM flushes the server after every message is sent to the backend. This is no worse than before as prior we were firing from every FilterHandler forward, triggering redundant events that were eventually no-ops in the backend flushing logic.
* FrontendHandler no longer needs to be concerned with firing channelReadComplete
* Forwarding of Buffered messages is no longer done on entry into Forwarding, we wait for the client to unblock after we have both entered Forwarding and finished async creation of the Transport Subject

## Problematic Flow from Before

1. connection from client to proxy established
2. client channel becomes active
3. TLS handshake occurs and handshake event propagated to ProxyChannelStateMachine (PCSM)
4. PCSM starts async Subject build
5. message from client flows through Filter chain and is buffered by the PCSM/FrontendHandler <- **BAD, Subject not populated when Filter worked with the message**
6. backend connects, PCSM is moved into forwarding
7. buffered messages are forwarded to the backend channel
8. async Subject build completes, client unblocked (autoread = true)

## New Flow

1. connection from client to proxy established
2. client channel becomes active
3. TLS handshake occurs and handshake event propagated to ProxyChannelStateMachine (PCSM)
4. PCSM starts async Subject build
5. message is buffered by the PCSM/FrontendHandler (before the Filter chain) <- **GOOD, Filters haven't observed the message yet**
6. backend connects, PCSM is moved into forwarding <-**GOOD, buffered messages are not forwarded yet, Filters haven't observed the message yet**
8. async Subject build completes, buffered messages are forwarded into the Filter chain, client unblocked (autoread = true) <-**GOOD, Transport Subject is populated at this point**
9. message reaches FilterChainCompletionHandler, they are passed to the PCSM, which forwards it to the backend channel

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/FilterHandler.java [hunk 1]
```diff
@@ -496,7 +496,6 @@ private void forwardRequest(DecodedRequestFrame<?> decodedFrame,
                 .log("Filter forwarding request");
 
         ctx.fireChannelRead(decodedFrame);
-        ctx.fireChannelReadComplete();
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/FilterHandler.java:499]: prior we called a channel read complete on every filter forward. I think this was a way to ensure deferred work was eventually flushed to the server, because we used the channelReadComplete event in the Frontend handler to drive a server flush. Because we have several filters in the chain (our internal ones plus user ones) that generated redundant channelReadComplete events that eventually are no-ops in the backendHandler as there's no pending flushes.

Instead I've changed it so that there is a single ForwardingHandler at the end of the pipeline. If the ForwardingHandler receives a message it is inferred that we must be in Forwarding, we tell the PCSM to send the message to the backend. The PCSM now invokes the serverFlush immediately after pushing every message to the backend. No worse than before (should be better as there's less redundant server flush attempts).

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 2]
```diff
@@ -316,17 +309,6 @@ private List<FilterAndInvoker> buildFilters() {
...
-    /**
-     * <p>Invoked when the last message read by the current read operation
-     * has been consumed by {@link #channelRead(ChannelHandlerContext, Object)}.</p>
-     * This allows the proxy to batch requests.
-     * @param clientCtx The client context
-     */
-    @Override
-    public void channelReadComplete(ChannelHandlerContext clientCtx) {
-        proxyChannelStateMachine.clientReadComplete();
-    }
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:328]: Prior the FilterHandlers in front of the frontend handler would fire a `channelReadComplete` on forward. If the backend wasn't connected these `channelReadCompletes` would not drive a server flush. So we had to call this after unbuffering to ensure the buffered messages written to the backend channel were flushed.

This isn't the case any more, the ForwardingHandler only receives messages that should be forwardable because we are in the Forwarding state. So the PCSM can flush every message that gets that far after writing it to the backend. Note that we were already flushing every message during normal forwarding, because of the FilterHandler `channelReadCompletes`, so this PR just removes some redundant events.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 3]
```diff
@@ -451,25 +433,6 @@ ChannelFuture initConnection(String remoteHost, int remotePort, Bootstrap bootst
         return bootstrap.connect(remoteHost, remotePort);
     }
 
-    /**
-     * Called by the {@link ProxyChannelStateMachine} on entry to the {@link Forwarding} state.
-     */
-    void inForwarding() {
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:457]: we now unbuffer when the client is unblocked before enabling autoread

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 4]
```diff
@@ -644,4 +614,7 @@ private Long getAuthenticatedIdleMillis(Optional<NettySettings> nettySettings) {
         return nettySettings.flatMap(NettySettings::authenticatedIdleTimeout).map(Duration::toMillis).orElse(NO_TIMEOUT);
     }
 
+    public void forward(Object msg) {
+        clientCtx().fireChannelRead(msg);
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:625]: this is where we used to send to the backend, the frontend handler now needs to fire channel read so that the FilterHandlers upstream of the FrontendHandler can handle it.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 5]
```diff
@@ -642,8 +644,7 @@ private void toConnecting(
     private void toForwarding(Forwarding forwarding) {
         setState(forwarding);
         kafkaSession.transitionTo(KafkaSessionState.NOT_AUTHENTICATED);
-        Objects.requireNonNull(frontendHandler).inForwarding();
-        // once buffered message has been forwarded we enable auto-read to start accepting further messages
+        // we must wait for the transport subject before forwarded buffered messages and then setting autoread=false on the client
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: should say autoread=true

**Comment by robobario** [comment]
@k-wall I gave it ~40 minutes of running with your aggressive reproducer with no failures. Thanks for that!

CC @hrishabhg

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 2 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:328]: yep have confirmed that on `main` once we are in Forwarding `flushToServer` on the backend handler will be called N times per message where N is the number of Filters in the chain. Most of these calls doing nothing because there's nothing to flush. So I'll stand by this PR improving things, doing a bit less redundant work.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 6]
```diff
@@ -555,10 +514,21 @@ private void addFiltersToPipeline(
...
+        forwardBufferedMessages();
         inboundChannel.config().setAutoRead(true);
         proxyChannelStateMachine.onClientWritable();
     }
 
+    private void forwardBufferedMessages() {
+        // connection is complete, so first forward the buffered message
+        if (bufferedMsgs != null) {
+            for (Object bufferedMsg : bufferedMsgs) {
+                clientCtx().fireChannelRead(bufferedMsg);
```
Comment (hrishabhg) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: nit:
```suggestion
                forward(bufferedMsg);
```

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 7]
```diff
@@ -535,14 +498,10 @@ private void addFiltersToPipeline(
...
-
-        for (var protocolFilter : filters) {
-            // TODO configurable timeout
-            // Handler name must be unique, but filters are allowed to appear multiple times
-            String handlerName = "filter-" + ++num + "-" + protocolFilter.filterName();
-            pipeline.addBefore(clientCtx().name(),
+        for (int i = filters.size() - 1; i >= 0; i--) {
+            FilterAndInvoker protocolFilter = filters.get(i);
+            String handlerName = "filter-" + (i + 1) + "-" + protocolFilter.filterName();
+            pipeline.addAfter(clientCtx().name(),
```
Comment (hrishabhg) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: Are we changing the direction of filter chain?

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 8]
```diff
@@ -430,7 +432,7 @@ void onClientRequest(
                          Object msg) {
         Objects.requireNonNull(frontendHandler);
         if (state() instanceof Forwarding) { // post-backend connection
-            messageFromClient(msg);
+            frontendHandler.forward(msg);
```
Comment (hrishabhg) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: Suggestion: While it makes sense from a technical standpoint given the current fix, the phrasing feels awkward in plain language. It’s unusual that in the forwarding state, PCSM instructs the FrontendHandler to forward the message instead of passing it directly to the backend.


Better would be that only `ForwardingHandler` only forwards the msg to the pcsm.

**Review by hrishabhg — COMMENTED** [review]
@robobario the changes looks good and simple. I have one suggestion if we can make single actor to forward the msg to pcsm.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java [hunk 9]
```diff
@@ -0,0 +1,35 @@
...
+
+package io.kroxylicious.proxy.internal;
+
+import java.util.Objects;
+
+import io.netty.channel.ChannelHandlerContext;
+import io.netty.channel.ChannelInboundHandlerAdapter;
+
+/**
+ * An inbound channel handler that informs a {@link ProxyChannelStateMachine} about messages read from the channel.
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java]:
```suggestion
 * An inbound channel handler that informs a {@link ProxyChannelStateMachine} about messages read from client channel.
```

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java [hunk 10]
```diff
@@ -242,6 +241,7 @@ void addHandlers(Channel ch, EndpointBinding binding, KafkaSession kafkaSession)
                 proxyNettySettings);
 
         pipeline.addLast("netHandler", frontendHandler);
+        pipeline.addLast("forwardingHandler", new ForwardingHandler(proxyChannelStateMachine));
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java]: Could we add a comment here, that the filter handlers are added when the KPFH receives a `channelActive()`.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java [hunk 11]
```diff
@@ -242,6 +241,7 @@ void addHandlers(Channel ch, EndpointBinding binding, KafkaSession kafkaSession)
                 proxyNettySettings);
 
         pipeline.addLast("netHandler", frontendHandler);
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java]: Unrelated, but it seems a bit weird to call this "netHandler". That doesn't make sense to us, nor to end users (which I guess might see it in logs).

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java [hunk 12]
```diff
@@ -0,0 +1,35 @@
...
+class ForwardingHandler extends ChannelInboundHandlerAdapter {
+    private final ProxyChannelStateMachine proxyChannelStateMachine;
+
+    ForwardingHandler(ProxyChannelStateMachine proxyChannelStateMachine) {
+        this.proxyChannelStateMachine = Objects.requireNonNull(proxyChannelStateMachine, "proxyChannelStateMachine is null");
+    }
+
+    @Override
+    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
+        proxyChannelStateMachine.messageFromClient(msg);
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java]: I think we should rename that `messageFromClient` in the PCSM. It doesn't really make it clear where the message has arrived. Maybe `forwardMessage` or even `forwardMessageToNextChannel` (which is what the backend handler is ultimately doing, even though it's intermediated by the PCSM). The latter seems a bit more compatible with routing. Wdyt @hrishabhg?

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java [hunk 13]
```diff
@@ -0,0 +1,35 @@
...
+ * and should be forwarded to the {@link KafkaProxyBackendHandler}. We can infer that the state machine should be in
+ * {@link ProxyChannelState.Forwarding} or {@link ProxyChannelState.Closed} state, because messages should not flow through
+ * {@link KafkaProxyFrontendHandler} and arrive at this handler until the state is {@link ProxyChannelState.Forwarding}.
+ * </p>
+ */
+class ForwardingHandler extends ChannelInboundHandlerAdapter {
+    private final ProxyChannelStateMachine proxyChannelStateMachine;
+
+    ForwardingHandler(ProxyChannelStateMachine proxyChannelStateMachine) {
+        this.proxyChannelStateMachine = Objects.requireNonNull(proxyChannelStateMachine, "proxyChannelStateMachine is null");
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java]: Does the string literal arg add anything? It's an NPE: It should never happen.

**Comment by robobario** [comment]
A bit tricky, we need the earlier handler to give it to the PCSM so it can decide to buffer or not, and we need the later handler to give it to the PCSM to forward it to the backend handler

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 7 above)
Comment (tombentley) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: It looks correct. to me, but it's does manage to look very odd. If we're adding A, B, C and this KPFH handler is K and it's followed by the forwarding handler F the pipeline builds like this:

* `K F`
* `K C F`
* `K B C F`
* `K A B C F`

We're always adding **after** K, but ignoring K it behaves like we're **prepending**. I don't immediately see a better way => deserves a comment.

**Review by tombentley — COMMENTED** [review]
I think this change does fix the problem @robobario, and I think it's cleaner than the other fixes you were looking at. I left a few comments/questions and will take another look tomorrow.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java (hunk 12 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java]: yeah I wasn't sure whether the channel should instruct the state machine, since the state machine is the decision maker, maybe it should be more of an `on*` method. Like `onMessageReadyToForwardToBackend(msg)`? The equivalent method for the FrontendHandler might be `onMessageBeforeFilterChain(msg)`, in that case it can't be an imperative instruction since PCSM decides whether to buffer or forward it into the filter chain.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 7 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: Yep it's to preserve the order while adding after the FrontendHandler.

An alternative I considered was to assume the existence of the handler named "forwardingHandler" and `addBefore` it. But it's more fragile and indirect. Would be a footgun if we needed to introduce more handlers. Easier to understand that we insert them relative to the FrontendHandler I think. Will add a comment.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java (hunk 8 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: yeah maybe this would be better named like `frontendHandler.admitMessageIntoFilterChain(msg)` to help clue readers into what is going to happen.

Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: it's a point too, we use the term `forward` in the FilterHandler when we mean push the message on to the next handler, so it's a bit overloaded to refer to sending messages from the frontend channel to the backend channel as forwarding.

Maybe we could go for the terminal language, this handler is the end of the line, like `FrontendTerminalHandler`? The handler itself isn't really concerned with what happens to the message, it just sits at the end and tells someone else the message reached the terminal.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 7 above)
Comment (k-wall) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: there's a subtly that I didn't immediately appreciate.  `pipeline` always points at K. We throw away the new pipeline object resulting from the addAfter, so our insert position remains the same across the iteration.  

I think if you renamed `pipeline` -> `head`, I'd had grok'd the code much quicker.

+1 to the comment

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 14]
```diff
@@ -410,15 +415,12 @@ void serverReadComplete() {
...
-    }
-
-    /**
-     * Called to notify the state machine that reading the downstream the batch is complete.
-     */
-    void clientReadComplete() {
-        if (state instanceof Forwarding) {
-            Objects.requireNonNull(backendHandler).flushToServer();
+        if (state() instanceof Forwarding) { // post-backend connection
+            Objects.requireNonNull(backendHandler).forwardToServer(msg);
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java:419]: can we not give the the backend handler the responsibility to flushToServer and avoid flushToServer being a public method?

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 15]
```diff
@@ -642,8 +644,7 @@ private void toConnecting(
     private void toForwarding(Forwarding forwarding) {
         setState(forwarding);
         kafkaSession.transitionTo(KafkaSessionState.NOT_AUTHENTICATED);
-        Objects.requireNonNull(frontendHandler).inForwarding();
-        // once buffered message has been forwarded we enable auto-read to start accepting further messages
+        // we must wait for the transport subject before forwarded buffered messages and then enanling autoread on the client
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: jumbled english
```suggestion
        // we must wait for the transport subject to be built before forwarding the buffered messages and then enabling autoread on the client
```

File: kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/FilterHarness.java [hunk 16]
```diff
@@ -102,7 +102,7 @@ protected void buildChannel(Filter... filters) {
                 forwarding,
                 mock(KafkaProxyFrontendHandler.class),
                 mock(KafkaProxyBackendHandler.class),
-                kafkaSession);
+                kafkaSession, -1);
```
Comment (k-wall) [inline kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/FilterHarness.java]: nit - convention for calls to this method are one parameter per line.

**Review by k-wall — APPROVED** [review]
Solid fix, thank you @robobario

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java (hunk 12 above)
Comment (SamBarker) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java]: `on` methods are life cycle events and callers shouldn't pre-suppose the policy decision the PSCM would make. I'd argue the lifecycle event here is `onClientFilterChainComplete` bookends `onClientRequest` nicely. The later fired on message arrival the former fired once we are done processing it.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java (hunk 8 above)
Comment (SamBarker) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: `FilterChainCompletionHandler` feels right for the handler name — it signals filter chain completion without presupposing what the PCSM does next.

Agreed on `admitToFilterChain` over `forward` for the FrontendHandler method.

**Review by SamBarker — APPROVED** [review]
LGTM modulo some re-naming as a tactical fix.

I think there is a more structural change to the state machine but thats a much bigger change that I want to follow up later.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java (hunk 14 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java:419]: We could do that for now.
The state machine is better positioned for coming up with alternative flushing strategies because it is aware of read completes on the front channel etc.
I haven't got a good idea of what that might look like since there is so much going on, Filters going async, Filters sending their own messages to the backend which delay the forwarding of the triggering message. It's hard to imagine how we'd optimize the flushing.

Will defer making that change as we could clean up the backend handler a bit while we do it.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java (hunk 13 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ForwardingHandler.java]: removed

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 7 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: I refactored this to make it easier to read. We now track the last handler name that was added and add after it. Should be more intuitive now as they are added in filter order.

```
K F
K A F
K A B F
K A B C F
```

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java (hunk 11 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyInitializer.java]: renamed to frontendHandler
