### PR TITLE
[SystemTest] Fix log collector on clean up

### LINKED ISSUE #3494: [SystemTests] RecordEncruptionST clean up fails
**Describe the bug**
RecordEncryptionST is passing, but when deleting the topic something goes wrong and logcollector starts to collect all logs.

**To Reproduce**
1. Run RecordEncryptionST
2. See error

**Expected behavior**
Avoid the error and the collection of the logs.

**YAML files and logs**

https://github.com/kroxylicious/kroxylicious/actions/runs/23181794616/job/67356546549?pr=3452#step:12:14423

**Additional context**

### PR DESCRIPTION
**Pull request by franvila**
### Type of change

- Bugfix

### Description

Log collector started to collect data after each test, because we were not checking if there was a failure or not on test execution.

### Additional Context

Fixes #3494 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-systemtests/src/test/java/io/kroxylicious/systemtests/extensions/KroxyliciousExtension.java [hunk 1]
```diff
@@ -92,7 +92,7 @@ public void afterEach(ExtensionContext extensionContext) {
         String testClassName = extensionContext.getRequiredTestClass().getName();
         String testMethodName = extensionContext.getRequiredTestMethod().getName();
         try {
-            if (!isAbortedTest(extensionContext)) {
+            if (extensionContext.getExecutionException().isPresent() && !isAbortedTest(extensionContext)) {
```
Comment (k-wall) [inline kroxylicious-systemtests/src/test/java/io/kroxylicious/systemtests/extensions/KroxyliciousExtension.java]: I think there is an opportunity to be more concise using the functional style.

```
            extensionContext.getExecutionException()
                    .filter(Predicate.not(TestAbortedException.class::isInstance))
                    .ifPresent(ee -> logCollector.collectLogs(testClassName, testMethodName));
```

Comment (franvila) [reply kroxylicious-systemtests/src/test/java/io/kroxylicious/systemtests/extensions/KroxyliciousExtension.java]: Done
