### PR TITLE
Port-per-broker Exposition: make lowest broker id configurable

### LINKED ISSUE #1045: Proxy fails to connect to cluster in KRaft mode when broker ports restricted to 1
**Describe the bug**
When using the Kroxylicious proxy to connect to a Kafka cluster that is running in KRaft mode it is incorrectly requesting ports. Specifically I saw this when running with a single combined node and setting `numberOfBrokerPorts` to 1.

**To Reproduce**
1. Follow the steps in the Kafka quickstart to start a single Kafka node in KRaft mode: https://kafka.apache.org/quickstart
2. Start Kroxylicious with `numberOfBrokerPorts` set to 1
3. Try to list Kafka topics: `./bin/kafka-topics.sh --bootstrap-server localhost:9192 --list`
4. The command hangs and Kroxylicious logs the error "Cannot generate broker address for node id 1"
5. Performing the same steps with a single Zookeeper node and single Kafka node in Zookeeper mode works as expected and does not fail.

**Expected behavior**
The proxy should successfully use the ports 9192 and 9193 to proxy traffic.

**YAML files and logs**

Config yaml used:
```
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: localhost:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9192
        numberOfBrokerPorts: 1
    logNetwork: false
    logFrames: false
```

Error logged:
```
2024-02-28 10:00:49 <KQueueEventLoopGroup-5-7> WARN  io.kroxylicious.proxy.internal.FilterHandler:293 - [id: 0xee3cf6a7, L:/127.0.0.1:49790 - R:localhost/127.0.0.1:9092]: Filterresponse for BrokerAddressFilter@376749768 METADATA ended exceptionally - closing connection. Cause message java.lang.IllegalArgumentException: Cannot generate broker address for node id 1 as port 9194 would fall outside port range 9193-9193 that is defined for provider with downstream bootstrap localhost:9192)
```

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Enhancement / new feature

### Description

Closes #1045

For example, if the lowest broker id in the cluster is 1, the configuration:
```
clusterNetworkAddressConfigProvider:
  type: PortPerBrokerClusterNetworkAddressConfigProvider
  config:
    bootstrapAddress: kroxylicious:9092
    firstBrokerId: 1
```
would map broker 1 to port 9093, broker 2 to port 9094 and broker 3 to port 9095

Why:
If a user is working with a cluster where the first broker id is 1 (the default KRaft configuration in the apache kafka distribution sets node.id to 1), if you have `numberOfBrokerPorts` configured to 1 then we cannot map the only broker. Not a very nice user experience. This would also accommodate users who have broker ids starting from a number greater than 0 without having to bind and expose max(BrokerId) ports.

Note:
This is a quick fix for a specific problem, reducing the number of ports required if the lowest node id is greater than zero. Port-per-broker is still only suited to simplistic configurations where the target Kafka cluster has sequential ids and the set of ids is reasonably static. See #902. We will likely need something more sophisticated to handle the nodeId to port mappings.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/PortPerBrokerClusterNetworkAddressConfigProvider.java [hunk 1]
```diff
@@ -104,17 +105,20 @@ public static class PortPerBrokerClusterNetworkAddressConfigProviderConfig {
...
                                                                       @JsonProperty(required = false) String brokerAddressPattern,
                                                                       @JsonProperty(required = false) Integer brokerStartPort,
+                                                                      @JsonProperty(required = false, defaultValue = "0") Integer firstBrokerId,
                                                                       @JsonProperty(required = false, defaultValue = "3") Integer numberOfBrokerPorts) {
             Objects.requireNonNull(bootstrapAddress, "bootstrapAddress cannot be null");
 
             this.bootstrapAddress = bootstrapAddress;
             this.brokerAddressPattern = brokerAddressPattern != null ? brokerAddressPattern : bootstrapAddress.host();
             this.brokerStartPort = brokerStartPort != null ? brokerStartPort : (bootstrapAddress.port() + 1);
+            this.firstNodeId = firstBrokerId != null ? firstBrokerId : 0;
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/PortPerBrokerClusterNetworkAddressConfigProvider.java:121]: I've got mixed naming here, but it's something to discuss. Currently the proxy is aware of brokers, but potentially in future we might need to proxy controller only nodes. Maybe we should move to the newer node and nodeId language used by Kafka?

**Comment by robobario** [comment]
Have confirmed that when I run the [kafka quickstart](https://kafka.apache.org/quickstart) and configure the proxy with:

```yaml
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9192
        numberOfBrokerPorts: 1
```
producing to the proxy fails with:
```
2024-03-07 13:13:52 <epollEventLoopGroup-5-1> WARN  io.kroxylicious.proxy.internal.FilterHandler:293 - [id: 0xab0fcd71, L:/127.0.0.1:51128 - R:localhost/127.0.0.1:9092]: Filterresponse for BrokerAddressFilter@1746177399 METADATA ended exceptionally - closing connection. Cause message java.lang.IllegalArgumentException: Cannot generate broker address for node id 1 as port 9194 would fall outside port range 9193-9193 that is defined for provider with downstream bootstrap localhost:9192)
```

and then adding:
```yaml
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9192
        numberOfBrokerPorts: 1
        firstBrokerId: 1
```
fixes it and you can now produce to the cluster

**Comment by robobario** [comment]
should add docs

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/PortPerBrokerClusterNetworkAddressConfigProvider.java (hunk 1 above)
Comment (k-wall) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/clusternetworkaddressconfigprovider/PortPerBrokerClusterNetworkAddressConfigProvider.java:121]: I think you are right.  Adopting the node language will be right thing now controllers are exposed to clients too.  But this can wait, we need to revisit port-per-broker, so I think we can sweep up the naming issues at the same time.

File: docs/deploying.adoc [hunk 2]
```diff
@@ -70,14 +75,16 @@ clusterNetworkAddressConfigProvider:
     brokerAddressPattern: mybroker-$(nodeId).mycluster.kafka.com # <2>
     brokerStartPort: 9193                                        # <3>
     numberOfBrokerPorts: 3                                       # <4>
-    bindAddress: 192.168.0.1                                     # <5>
+    firstBrokerId: 1000                                          # <5>
```
Comment (k-wall) [inline docs/deploying.adoc:78]: It is not clear from the name that this refers to a property of the target cluster, rather than virtual cluster.  A user might be confused into thinking they are configuring the later.

File: docs/deploying.adoc [hunk 3]
```diff
@@ -70,14 +75,16 @@ clusterNetworkAddressConfigProvider:
...
+    bindAddress: 192.168.0.1                                     # <6>
 ----
 <1> The hostname and port of the bootstrap that will be used by the Kafka Clients.
 <2> (Optional) The broker address pattern used to form the broker addresses.  If not defined, it defaults to the
 hostname part of the `bootstrapAddress` and the port number allocated to the broker.
 <3> (Optional) The starting number for broker port range. Defaults to the port of the `bootstrapAddress` plus 1.
 <4> (Optional) The _maximum_ number of brokers of ports that are permitted.  Defaults to 3.
-<5> (Optional) The bind address used when binding the ports. If undefined, all network interfaces will be bound.
+<5> (Optional) The first broker id in your cluster. Defaults to 0.
```
[the remark this answers is not in the document]
Comment (robobario) [reply docs/deploying.adoc:86]: if lowest makes sense in the definition maybe the property should be `lowestBrokerId`, maybe `first` isn't so great as it's implying an ordering that the user has to grok

File: docs/deploying.adoc (hunk 2 above)
Comment (robobario) [reply docs/deploying.adoc]: Yeah it feels a bit deep for 0.5.0, TargetCluster and CNACP are in different modules so some options might be something like:

1. Move CNACP to kroxylicious-runtime and add a method on it like `initialise(TargetCluster c)` that has to be called before using the provider.
2. Introduce a CNACPFactory interface to kroxylicious-runtime with a method like `CNACP build(TargetCluster c)` and refactor port-per-broker and SNI so we service load the factory and then use it to build the provider.

I think I'd rather have it on port-per-broker config for now while we figure out what the solution should look like in future, it'd be nice if we could avoid the user having to configure in their node id bounds.

Comment (SamBarker) [reply docs/deploying.adoc]: I think the problem @k-wall highlights is important but as you both say too involved for the 0.5.0 release. 

Really not sure which of your suggestions makes sense for the longer term fix.

**Review by SamBarker — APPROVED** [review]
LGTM

File: docs/deploying.adoc (hunk 2 above)
Comment (robobario) [reply docs/deploying.adoc]: I've renamed it `lowestTargetBrokerId` to make it explicit

**Comment by robobario** [comment]
@strimzi-ci run system tests

**Review by k-wall — APPROVED** [review]
