### PR TITLE
[System Tests] fix kaf client restart pod

### LINKED ISSUE #3605: KroxyliciousST.restartKafkaBrokers timed out with subsequent failure to gather logs.
CI saw the following test fail.

https://github.com/kroxylicious/kroxylicious/actions/runs/23951353554/job/69866141176

## failed test

`KroxyliciousST#restartKafkaBrokers`

By examining the stack trace, I think you can infer that the test timed out, but that was obscured by the subsequent failure to gather than logs from the pod.

## stack trace

```
Error:  Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 684.5 s <<< FAILURE! -- in io.kroxylicious.systemtests.KroxyliciousST
Error:  io.kroxylicious.systemtests.KroxyliciousST.restartKafkaBrokers(String) -- Time elapsed: 317.5 s <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://192.168.49.2:8443/api/v1/namespaces/kroxylicious-st-7d9d0f/pods/kafka-consumer-client-kaf-serene-murdock5-p5rfw/log?pretty=false. Message: pods "kafka-consumer-client-kaf-serene-murdock5-p5rfw" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=pods, name=kafka-consumer-client-kaf-serene-murdock5-p5rfw, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "kafka-consumer-client-kaf-serene-murdock5-p5rfw" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:642)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:622)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:582)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleRaw(OperationSupport.java:721)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleRawGet(OperationSupport.java:474)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.doGetLog(PodOperationsImpl.java:133)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.getLog(PodOperationsImpl.java:141)
	at io.kroxylicious.systemtests.k8s.KubeClient.logsInSpecificNamespace(KubeClient.java:292)
	at io.kroxylicious.systemtests.clients.KafClient.waitForConsumer(KafClient.java:159)
	at io.kroxylicious.systemtests.clients.KafClient.consumeMessages(KafClient.java:138)
	at io.kroxylicious.systemtests.steps.KroxyliciousSteps.consumeMessages(KroxyliciousSteps.java:126)
	at io.kroxylicious.systemtests.KroxyliciousST.restartKafkaBrokers(KroxyliciousST.java:155)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

### PR DESCRIPTION
**Pull request by franvila**
### Type of change

- Bugfix

### Description

Sometimes the kaf client fails to launch the consumer and container was restarted within the pod. Currently the container is never restarted and a new pod is created, leaving the erroneous alive to read the log.

See #3605 for more information.

### Additional Context

Fixes #3605 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [x] Write tests
- [x] Update documentation
- [x] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [x] If applicable to the change, make sure system tests pass.
- [x] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [x] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

**Review by SamBarker — COMMENTED** [review]
Thank you for this fix Francisco! The core issue makes sense — hardcoding a pod name breaks when the pod gets replaced, and the move to label-based lookup is a clear improvement.

I have a couple of questions:

### `restartPolicy` placement

The `restartPolicy` has moved from the pod spec level to the container level:

```java
// Before (pod spec):
.withRestartPolicy(Constants.RESTART_POLICY_ON_FAILURE)

// After (container):
.withContainers(ContainerTemplates.baseImageBuilder(...)
    .withRestartPolicy(Constants.RESTART_POLICY_NEVER)
    .build())
```

For Jobs, `restartPolicy` is a pod-level field. Container-level `restartPolicy` is a newer feature intended for init/sidecar containers (Kubernetes 1.28+) — I'm not sure it's honoured for regular containers. Could this end up with no effective restart policy on the pod spec?

### Timeout handler loses log output

In the `ConditionTimeoutException` catch block, `log` will always be `""` now since the fetch was removed but not replaced with the label-based lookup that the `KubeClusterException` handler uses:

```java
catch (ConditionTimeoutException e) {
    // log is "" here — previously it fetched logs from the named pod
    LOGGER.atError().setMessage("Timeout! Received: {}").addArgument(log).log();
}
```

Should this also look up pods by label and fetch their logs for diagnosis, similar to the `KubeClusterException` handler?

### Broader question: Job vs Pod abstraction

More of an open question than a blocker — since we're submitting a Job, should we be tracking pods at all? The current approach (both before and after this fix) reaches through the Job to query pods directly, which is what caused the original bug. Would it be simpler to interact at the Job level — e.g. wait for Job completion via the Job API, then retrieve logs from the Job's pod(s)? That would let the Job controller own pod lifecycle entirely.

**Comment by franvila** [comment]
> Thank you for this fix Francisco! The core issue makes sense — hardcoding a pod name breaks when the pod gets replaced, and the move to label-based lookup is a clear improvement.
> 
> I have a couple of questions:
> 
> ### `restartPolicy` placement
> The `restartPolicy` has moved from the pod spec level to the container level:
> 
> ```java
> // Before (pod spec):
> .withRestartPolicy(Constants.RESTART_POLICY_ON_FAILURE)
> 
> // After (container):
> .withContainers(ContainerTemplates.baseImageBuilder(...)
>     .withRestartPolicy(Constants.RESTART_POLICY_NEVER)
>     .build())
> ```
> 
> For Jobs, `restartPolicy` is a pod-level field. Container-level `restartPolicy` is a newer feature intended for init/sidecar containers (Kubernetes 1.28+) — I'm not sure it's honoured for regular containers. Could this end up with no effective restart policy on the pod spec?

We don't want the container to be restarted. This was suggested by Keith in the issue and this is the behavior we want to have the chance to collect the logs when something goes wrong. If not, the same pod is restarted and then deleted, so we never know what is going on.

> 
> ### Timeout handler loses log output
> In the `ConditionTimeoutException` catch block, `log` will always be `""` now since the fetch was removed but not replaced with the label-based lookup that the `KubeClusterException` handler uses:
> 
> ```java
> catch (ConditionTimeoutException e) {
>     // log is "" here — previously it fetched logs from the named pod
>     LOGGER.atError().setMessage("Timeout! Received: {}").addArgument(log).log();
> }
> ```
> 
> Should this also look up pods by label and fetch their logs for diagnosis, similar to the `KubeClusterException` handler?

Yes, this is something I realized talking to my pillow last night. I have to do the same than the other exception.

> 
> ### Broader question: Job vs Pod abstraction
> More of an open question than a blocker — since we're submitting a Job, should we be tracking pods at all? The current approach (both before and after this fix) reaches through the Job to query pods directly, which is what caused the original bug. Would it be simpler to interact at the Job level — e.g. wait for Job completion via the Job API, then retrieve logs from the Job's pod(s)? That would let the Job controller own pod lifecycle entirely.

The problem we have here is that the consumer is running forever until we decided to finish (all expected records have been consumed), the job will never be completed so we need to read the logs at the same time the consumer is consuming the records, we cannot wait until the job is completed.

**Review by SamBarker — COMMENTED** [review]
Thanks for the explanations Fran!

The Job vs Pod point makes total sense — since the consumer runs indefinitely, you can't wait for Job completion to grab logs. Working with the pods directly is the right call.

On the restart policy: changing from `OnFailure` to `Never` is fine, but my concern is about *where* it's set rather than the value. Container-level `restartPolicy` is a Kubernetes 1.28+ feature intended for sidecar/init containers — I'm not sure it's honoured for regular containers. Did you mean to set it at the pod spec level instead?

Did you try fetching logs with `previous=true`? The kubelet should retain the logs for a failed container, so that might be simpler than changing the restart policy.

**Comment by franvila** [comment]
> Thanks for the explanations Fran!
> 
> The Job vs Pod point makes total sense — since the consumer runs indefinitely, you can't wait for Job completion to grab logs. Working with the pods directly is the right call.
> 
> On the restart policy: changing from `OnFailure` to `Never` is fine, but my concern is about _where_ it's set rather than the value. Container-level `restartPolicy` is a Kubernetes 1.28+ feature intended for sidecar/init containers — I'm not sure it's honoured for regular containers. Did you mean to set it at the pod spec level instead?
> 
> Did you try fetching logs with `previous=true`? The kubelet should retain the logs for a failed container, so that might be simpler than changing the restart policy.

I have tested locally using `previous=true` (from [here](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md#log-options)) and it does not ever work. I got always this error:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://192.168.39.235:8443/api/v1/namespaces/kroxylicious-st-1673d7/pods/kafka-consumer-client-kaf-angry-lehmann7-mpqxt/log?pretty=false&previous=true. Message: pods "kafka-consumer-client-kaf-angry-lehmann7-mpqxt" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=pods, name=kafka-consumer-client-kaf-angry-lehmann7-mpqxt, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "kafka-consumer-client-kaf-angry-lehmann7-mpqxt" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
```
and it does not fix our issue with kaf. Setting Container-level policy to `Never` does.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/clients/KafClient.java [hunk 1]
```diff
@@ -134,34 +135,50 @@ public List<ConsumerRecord> consumeMessages(String topicName, String bootstrap,
...
                     }, m -> getNumberOfJsonMessages(m) >= numOfMessages);
         }
         catch (ConditionTimeoutException e) {
-            log = kubeClient().logsInSpecificNamespace(deployNamespace, podName);
-            LOGGER.atError().setMessage("Timeout! Received: {}").addArgument(log).log();
+            List<Pod> pods = kubeClient().listPods(deployNamespace, "app", jobName);
+            pods.forEach(pod -> {
+                String podName = pod.getMetadata().getName();
+                String currentLog = kubeClient().logsInSpecificNamespace(deployNamespace, podName);
+                LOGGER.atError().setMessage("Timeout! Pod '{}', received: {}").addArgument(podName).addArgument(currentLog).log();
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/clients/KafClient.java:171]: In the failed case, aren't the files going to be part of the cluster dump.  What's the point of duplicating the log here?

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java [hunk 2]
```diff
@@ -289,11 +289,11 @@ public static JobBuilder authenticationKafkaGoJob(String jobName, List<String> a
                 .withBackoffLimit(3)
                 .editTemplate()
                 .editSpec()
-                .withRestartPolicy(Constants.RESTART_POLICY_ON_FAILURE)
                 .withVolumes(volumes)
                 .withContainers(ContainerTemplates.baseImageBuilder("kafka-go", Constants.KAF_CLIENT_IMAGE)
                         .withArgs(args)
                         .withVolumeMounts(volumeMounts)
+                        .withRestartPolicy(Constants.RESTART_POLICY_NEVER)
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java]: I think you are relying on an alpha feature.  I'm not sure that'll work on all platforms we want to test on.

https://kubernetes.io/blog/2025/08/29/kubernetes-v1-34-per-container-restart-policy/

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java [hunk 3]
```diff
@@ -289,11 +289,11 @@ public static JobBuilder authenticationKafkaGoJob(String jobName, List<String> a
                 .withBackoffLimit(3)
                 .editTemplate()
                 .editSpec()
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java:271]: Remind me, what it is a about the Go client that means we need different restart rules?

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/clients/KafClient.java (hunk 1 above)
Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/clients/KafClient.java:171]: No they aren't. The pod is removed before the log collector to stabilize the tests (#2399)

Comment (k-wall) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/clients/KafClient.java:171]: ah, okay.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java (hunk 3 above)
Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java:271]: Kaf client is not as stable as other clients and it does not reconnect when the consumer fails to connect, so we need to do it manually.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java (hunk 2 above)
Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java]: Removed and it is working fine

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java (hunk 3 above)
Comment (k-wall) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/templates/testclients/TestClientsJobTemplates.java:271]: We should add a comment to that effect.

**Review by k-wall — APPROVED** [review]
LGTM. Thank you @franvila
