### PR TITLE
fix(tests): add operational readiness check to eliminate topic creation race condition

### LINKED ISSUE #3767: bug: Non-Deterministic Test ListOffsetsAuthzIT.shouldEnforceAccessToTopics
A test failed non-deterministically in GitHub Actions:

## failed test

`io.kroxylicious.it.filter.authorization.ListOffsetsAuthzIT.shouldEnforceAccessToTopics`

https://github.com/kroxylicious/kroxylicious/actions/runs/24763367811/job/72487785562?pr=3684

## stack trace

```
[ERROR] io.kroxylicious.it.filter.authorization.ListOffsetsAuthzIT.shouldEnforceAccessToTopics(VersionSpecificVerification)[3] -- Time elapsed: 0.817 s <<< FAILURE!
net.javacrumbs.jsonunit.core.internal.Opentest4jExceptionFactory$JsonAssertError: 
[Expect proxied response to be the same as the reference response with equivalent AuthZ] JSON documents are different:
Different value found in node "alice", expected: <"{
  "throttleTimeMs" : 0,
  "topics" : [ {
    "name" : "alice-new-topic",
    "partitions" : [ {
      "partitionIndex" : 0,
      "errorCode" : 0,
      "timestamp" : -1,
      "offset" : -1
    }, {
      "partitionIndex" : 20,
      "errorCode" : 3,
      "timestamp" : -1,
      "offset" : -1
    } ]
  }, {
    "name" : "bob-new-topic",
    "partitions" : [ {
      "partitionIndex" : 0,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    }, {
      "partitionIndex" : 20,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    } ]
  }, {
    "name" : "other-topic",
    "partitions" : [ {
      "partitionIndex" : 0,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    }, {
      "partitionIndex" : 20,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    } ]
  } ]
}"> but was: <"{
  "throttleTimeMs" : 0,
  "topics" : [ {
    "name" : "alice-new-topic",
    "partitions" : [ {
      "partitionIndex" : 0,
      "errorCode" : 6,
      "timestamp" : -1,
      "offset" : -1
    }, {
      "partitionIndex" : 20,
      "errorCode" : 3,
      "timestamp" : -1,
      "offset" : -1
    } ]
  }, {
    "name" : "bob-new-topic",
    "partitions" : [ {
      "partitionIndex" : 0,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    }, {
      "partitionIndex" : 20,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    } ]
  }, {
    "name" : "other-topic",
    "partitions" : [ {
      "partitionIndex" : 0,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    }, {
      "partitionIndex" : 20,
      "errorCode" : 29,
      "timestamp" : -1,
      "offset" : -1
    } ]
  } ]
}">.
```

The test expected errorCode 0 (success) for alice-new-topic and bob-new-topic partition 0, but received errorCode 6 (INVALID_TOPIC_EXCEPTION). This suggests a timing issue where the topic is queried before it's fully created or recognized by the Kafka broker, creating a race condition between topic creation and the authorization test.

Note: This is a recurrence of the issue previously reported in #3207 (closed Feb 2026), but with inverted behavior - the old issue expected errorCode 6 but got 0, while this failure expects 0 but gets 6.

### PR DESCRIPTION
**Pull request by k-wall**
## Type of change

- [x] Bugfix

## Description

Fixes intermittent test failures with NOT_LEADER_OR_FOLLOWER / UNKNOWN_TOPIC_OR_PARTITION errors by implementing a comprehensive two-phase topic readiness verification in ClusterPrepUtils.

### Root Cause

The race condition occurred when metadata showed topics as ready, but the broker's internal request handler hadn't synchronized yet. Tests would proceed and fail with error code 6 (NOT_LEADER_OR_FOLLOWER / UNKNOWN_TOPIC_OR_PARTITION).

This could happen even in single-broker scenarios because:
1. Topic creation completes via Admin API
2. Metadata shows partition has a leader (passes readiness check)
3. **Gap**: Broker's request handler hasn't updated its internal leadership cache
4. Test sends ListOffsets request
5. Request handler checks "Am I the leader?" → False (cache not synchronized yet)
6. Response: NOT_LEADER_OR_FOLLOWER (error code 6)

### Solution

Implemented a two-phase readiness verification in `ClusterPrepUtils.createTopicsAndAcls()`:

#### **Phase 1: Enhanced Metadata Readiness**
- Verifies partition leader is assigned (not null)
- Excludes `Node.noNode()` sentinel value (indicates no leader assigned yet)
- Ensures ISR (In-Sync Replicas) is populated

#### **Phase 2: Operational Readiness** (NEW - Key Innovation)
- Calls `admin.listOffsets()` to verify broker can actually serve requests
- Uses the **exact same API code path** as ListOffsets tests
- Proves topics are truly ready to serve client requests, not just metadata-ready

The operational probe is the critical piece - it directly verifies the broker's request handler can process ListOffsets API calls, eliminating the internal state synchronization race.

### Benefits

- **Fixes root cause**: Verifies operational readiness, not just metadata existence
- **All 76 callers benefit**: Every test using `createTopicsAndAcls()` gains reliability
- **Enables cleanup**: Removed obsolete `needsRetry()` workarounds from FetchAuthzIT and OffsetForLeaderEpochAuthzIT
- **Unconditional**: Simple API, no parameters - operational probe runs for everyone

### Verification

The fix was verified through comprehensive testing:

#### **Single Test Runs**
- **ListOffsetsAuthzIT**: 11/11 tests passed
- **FetchAuthzIT**: 15/15 tests passed (without retry logic)
- **OffsetForLeaderEpochAuthzIT**: 3/3 tests passed (without retry logic)

#### **Stress Test**
Ran ListOffsetsAuthzIT 30 times to reproduce the race condition:
```bash
Results:
  Passed: 30
  Failed: 0
  Race conditions detected: 0
```

All iterations passed cleanly with no errorCode mismatches, proving the race condition is completely eliminated.

### Future Simplification

**Note**: We suspect Phase 1 (metadata readiness check via `topicPartitionsHaveALeader()`) may now be superfluous, since Phase 2 (operational readiness probe) implicitly verifies everything Phase 1 checks. If `admin.listOffsets()` succeeds, it proves the topic exists, has a leader, and the broker can serve requests.

However, we're keeping both phases for now to ensure stability across the AuthzIT test suite. Once we're confident the operational probe alone is sufficient, we can remove Phase 1 in a separate PR to simplify the implementation.

Fixes #3767

## Checklist

- [x] PR raised from a fork of this repository and made from a branch rather than main
- [x] Write tests (comprehensive stress testing performed)
- [ ] Update documentation (not applicable - internal test fix)
- [x] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored
- [ ] If applicable to the change, trigger the system test suite
- [ ] If applicable to the change, trigger the performance test suite
- [x] Ensure the PR references relevant issue(s) so they are closed on merging
- [ ] For user facing changes, update CHANGELOG.md (not applicable - internal test fix)

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
LGTM

**Comment by k-wall** [comment]
@SamBarker the first fix was not completely successful.   There's now a proper fix.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/filter/authorization/ClusterPrepUtils.java [hunk 1]
```diff
@@ -55,6 +71,7 @@ static Map<String, Uuid> createTopicsAndAcls(Admin admin,
         }
         var res = admin.createTopics(topicNames.stream().map(topicName -> new NewTopic(topicName, 1, (short) 1)).toList());
         res.all().toCompletionStage().toCompletableFuture().join();
+        // Phase 1: Wait for metadata readiness
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/filter/authorization/ClusterPrepUtils.java:74]: I _think_ we can do anyway with this check and just rely on phase 2.   However, I opt to keep both for a week or so, hopefully to prove that the tests are running stable.

**Review by tombentley — APPROVED** [review]
Many thanks @k-wall.
