### PR TITLE
fix(operator): add readiness probe to proxy operand deployment

### LINKED ISSUE #3345: Operand deployment reports ready even though operand has crashed with a configuration error
This is the second half of #3344.  If the proxy operand fails at startup owing to a filter mis-configuration, the Kubernetes deployment, momentarily, erroneously reports the pod as ready.

As we are supplying neither a `readinessProbe` or a `minReadySeconds` deployment configuration, Kubernetes is assuming the pod is ready right away. `availableReplicas` gets set momentarily to 1 before the container crashes.   This leads anything that is relying of the deployment's readiness (like our tests), to believe the deployment is ready.

### PR DESCRIPTION
**Pull request by SamBarker**
### Type of change

- Bugfix

### Description

Adds a readiness probe to the proxy operand `Deployment`, pointing at
`/livez` on the management port (9190).

Without a readiness probe, Kubernetes assumes a pod is ready
immediately at startup. This means `availableReplicas` can briefly
reach 1 even when the proxy crashes before it ever becomes healthy
(e.g. due to a configuration error), causing anything watching
deployment readiness to incorrectly conclude the rollout succeeded.

The readiness probe is configured with:
- `initialDelaySeconds: 0` — start checking immediately
- `periodSeconds: 1` — check every second
- `failureThreshold: 3`, `successThreshold: 1`, `timeoutSeconds: 1`

The aggressive `periodSeconds` keeps the latency impact on test runs
minimal (a healthy pod is marked ready within ~1s of its management
listener binding).

> **Note for reviewers:** the existing liveness probe has no
> `periodSeconds` set, so it runs at the Kubernetes default of 10s.
> The readiness probe deliberately uses `periodSeconds: 1` to minimise
> test latency. This asymmetry between the two probes may be surprising
> and is worth a follow-up look to decide whether liveness should be
> aligned.

### Additional Context

Fixes #3345 (second half of #3344).

### Checklist

- [x] PR raised from a fork of this repository and made from a branch rather than main.
- [x] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, trigger the performance test suite.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md

### CODE REVIEW

**Comment by SamBarker** [comment]
@k-wall you also mentioned the idea of a startup probe, my understanding is those are better for slow starting containers rather our possibly starting one. So I believe the right choice is a the liveness probe.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/reconciler/kafkaproxy/ProxyDeploymentDependentResource.java [hunk 1]
```diff
@@ -183,6 +183,17 @@ private Container proxyContainer(KafkaProxy primary, KafkaProxyContext kafkaProx
...
                 .endLivenessProbe()
+                .withNewReadinessProbe()
+                    .withNewHttpGet()
+                        .withPath("/livez")
+                        .withPort(new IntOrString(MANAGEMENT_PORT_NAME))
+                    .endHttpGet()
+                    .withInitialDelaySeconds(0)
+                    .withPeriodSeconds(1)
+                    .withSuccessThreshold(1)
+                    .withTimeoutSeconds(1)
```
Comment (robobario) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/reconciler/kafkaproxy/ProxyDeploymentDependentResource.java:194]: they sounds a little aggressive to me. maybe we should be more worried about a GC event taking >1s

what about somethings like
```
.withInitialDelaySeconds(1)
                    .withPeriodSeconds(5)
                    .withSuccessThreshold(1)
                    .withTimeoutSeconds(2)
```

Comment (SamBarker) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/reconciler/kafkaproxy/ProxyDeploymentDependentResource.java:194]: I worry bumping period seconds slows down the integration tests if things aren't ready on the first hit.

GC pauses are a theoretical risk I agree but I don't expect a 1s plus GC pause in the proxy we probably won't be running with huge heaps etc. and if we are it's fairly simple to tune the GC settings

**Review by robobario — APPROVED** [review]
LGTM, I wonder whether you could get the fast start plus a less aggressive readiness with the startup probe. The startup probe can do the 1s period until it's up and then we could have a more relaxed readiness period. But it's non blocking, I think we need a readiness check anyway.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/reconciler/kafkaproxy/ProxyDeploymentDependentResource.java (hunk 1 above)
Comment (k-wall) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/reconciler/kafkaproxy/ProxyDeploymentDependentResource.java:194]: >  I worry bumping period seconds slows down the integration tests if things aren't ready on the first hit.

Agreed.  I think withInitialDelaySeconds of 1 second and period 5 seconds, would mean we incur a 6 second startup time if management was ready within the first second.


> GC pauses are a theoretical risk I agree but I don't expect a 1s plus GC pause in the proxy we probably won't be running with huge heaps etc. and if we are it's fairly simple to tune the GC settings

I wondered about a startup probe with tuning for a quick launch time.  A separate readiness probe could then be tuned to meet the needs of runtime conditions (GC pauses etc).  If we went this way, I think I'd add the startup probe in this PR, that's sufficient to address the issue. I'd defer adding a readiness probe till we can think more. I suspect we should really be exposing the capability to tune the probes.

Full disclosure - I haven't actually implemented a startup probe before.  My comments are based on the Kubernetes documentation.

**Comment by k-wall** [comment]
> @k-wall you also mentioned the idea of a startup probe, my understanding is those are better for slow starting containers rather our possibly starting one. So I believe the right choice is a the liveness probe.

I mentioned the idea again in the comment.  I think the difference between the startup probe and the readiness is merely the phase of the application life to which it is applied.  I think 'slow starting containers' might be just be an example use-case where you want more generous parameters (app loading a big cache on startup etc).

I think we've got the opposite situation.  We expect the startup phase of proxy to complete quickly, but worry that at runtime when the proxy is servicing requests, GC pauses may lead to spurious probe failures. (In the Proxy, GC will characteristics will be highly filter chain dependent).  Trying to balance the probe parameters to suit with both startup and runtime sounds hard.  I think that's what we are doing if we rely on a single readiness probe.

I think by using a startup probe we just focus on  the startup phase.   Yes we probably want readiness probe too, but that's a different issue.

**Comment by SamBarker** [comment]
> > @k-wall you also mentioned the idea of a startup probe, my understanding is those are better for slow starting containers rather our possibly starting one. So I believe the right choice is a the liveness probe.
> 
> I mentioned the idea again in the comment. I think the difference between the startup probe and the readiness is merely the phase of the application life to which it is applied. I think 'slow starting containers' might be just be an example use-case where you want more generous parameters (app loading a big cache on startup etc).
> 
> I think we've got the opposite situation. We expect the startup phase of proxy to complete quickly, but worry that at runtime when the proxy is servicing requests, GC pauses may lead to spurious probe failures. (In the Proxy, GC will characteristics will be highly filter chain dependent). Trying to balance the probe parameters to suit with both startup and runtime sounds hard. I think that's what we are doing if we rely on a single readiness probe.
> 
> I think by using a startup probe we just focus on the startup phase. Yes we probably want readiness probe too, but that's a different issue.

Digging into this a bit I've (well Claude) found  https://github.com/kubernetes/kubernetes/issues/135248 TL:DR is that without a **readiness**  probe we will still see the behaviour you observed: Pods without a readiness probe are automatically marked ready. 
While there does seem to be some questions on the bug if its observable it certainly fits our observed symptoms.   

I'm of the opinion that pining a HTTP endpoint every 1s is cheap enough for now.

It looks like standard practice is to make use of all three probes and expose the configuration to users but I think this PR is the right thing to do now.

**Comment by k-wall** [comment]
Ok, I agree this is a good step forward.
