### PR TITLE
Fix #463 - deregister micrometer hooks, meters and the registry on shutdown

### LINKED ISSUE #463: "Attempted to register a meter with id" errors during integration tests
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**

Running the integration tests on main, I notice ERRORs like this being spewed out.  The messages don't seem to cause harm and the tests still pass. The noise is unpleasant. 

```
2023-07-18 13:04:10 ERROR io.kroxylicious.proxy.internal.MeterRegistries:62 - Attempted to register a meter with id MeterId{name='jvm.gc.pause', tags=[tag(a=b),tag(action=end of minor GC),tag(cause=G1 Humongous Allocation),tag(gc=G1 Young Generation)]} which is already registered but with a different set of tag names
java.lang.IllegalArgumentException: tags for id MeterId{name='jvm.gc.pause', tags=[tag(a=b),tag(action=end of minor GC),tag(cause=G1 Humongous Allocation),tag(gc=G1 Young Generation)]} differ from existing meters registered
	at io.kroxylicious.proxy.internal.MeterRegistries$1.accept(MeterRegistries.java:63)
	at io.micrometer.core.instrument.MeterRegistry.accept(MeterRegistry.java:646)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:612)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:577)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:323)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:444)
	at io.micrometer.core.instrument.binder.jvm.JvmGcMetrics$GcMetricsNotificationListener.handleNotification(JvmGcMetrics.java:211)
	at java.management/sun.management.NotificationEmitterSupport.sendNotification(NotificationEmitterSupport.java:155)
	at jdk.management/com.sun.management.internal.GarbageCollectorExtImpl.createGCNotification(GarbageCollectorExtImpl.java:115)
```

**To Reproduce**
1. `mvn  verify -pl integrationtests`

**Expected behavior**
No MeterRegistry errors logged to console.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Trying to prevent the stack trace originating from the JMX notifications during integration test runs.
The issue is not causing test failures, but the noise is polluting the logs.

### Additional Context

Build hygiene.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [x] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [x] Reference relevant issue(s) and close them after merging
- [x] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious/src/test/java/io/kroxylicious/proxy/micrometer/StandardBindersHookTest.java [hunk 1]
```diff
@@ -25,29 +25,33 @@ public void testNullHookConfigThrows() {
...
     }
 
     @Test
     public void testUnknownBinder() {
-        StandardBindersHook hook = new StandardBindersHook(new StandardBindersHook.StandardBindersHookConfig(List.of("SadClown")));
-        assertThatThrownBy(() -> whenRegistryConfiguredWith(hook)).isInstanceOf(IllegalArgumentException.class);
+        try (StandardBindersHook hook = new StandardBindersHook(new StandardBindersHook.StandardBindersHookConfig(List.of("SadClown")))) {
+            assertThatThrownBy(() -> whenRegistryConfiguredWith(hook)).isInstanceOf(IllegalArgumentException.class);
+        }
     }
```
Comment (k-wall) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/micrometer/StandardBindersHookTest.java:56]: Testing that close actually calls #close on the binder seems tricky.   There's no clean way to actually makes the observation.

Comment (k-wall) [reply kroxylicious/src/test/java/io/kroxylicious/proxy/micrometer/StandardBindersHookTest.java:66]: I found a way I could live with.

File: integrationtests/src/test/resources/log4j2-test.properties [hunk 2]
```diff
@@ -43,13 +43,13 @@ rootLogger.additivity = false
...
 #logger.netty.appenderRef.console.ref = STDOUT
 #
-logger.broker.name = kafka
-logger.broker.level = DEBUG
-logger.broker.additivity = false
-logger.broker.appenderRef.console.ref = STDOUT
-
-logger.net.name = org.apache.kafka.clients.NetworkClient
-logger.net.level = debug
+#logger.broker.name = kafka
```
Comment (robobario) [inline integrationtests/src/test/resources/log4j2-test.properties:46]: Did you mean to turn the noise down here too?

**Review by robobario — APPROVED** [review]
LGTM

File: kroxylicious/src/main/java/io/kroxylicious/proxy/micrometer/StandardBindersHook.java [hunk 3]
```diff
@@ -52,11 +54,25 @@ public void configure(MeterRegistry targetRegistry) {
         for (String binderName : this.config.binderNames) {
             MeterBinder binder = getBinder(binderName);
             binder.bindTo(targetRegistry);
-            log.info("bound " + binderName + " to micrometer registry");
+            if (binder instanceof AutoCloseable closeable) {
```
[the remark this answers is not in the document]
Comment (SamBarker) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/micrometer/StandardBindersHook.java:57]: Should we test for `Closeable` as well?

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java [hunk 4]
```diff
@@ -80,4 +81,13 @@ private static Object tagNames(Meter.Id id1) {
     public Optional<PrometheusMeterRegistry> maybePrometheusMeterRegistry() {
         return Optional.ofNullable(prometheusMeterRegistry);
     }
+
+    @Override
+    public void close() {
+        hooks.forEach(MicrometerConfigurationHook::close);
+        // remove the meters we contributed to the global registry.
+        var copy = List.copyOf(prometheusMeterRegistry.getMeters());
+        copy.forEach(Metrics.globalRegistry::remove);
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java:90]: Shouldn't we have a null check here? Or use `Optional.ifPresent`? 

Is there a particular reason for the defensive copy? I don't suppose the allocation cost really matters during close...

File: integrationtests/src/test/java/io/kroxylicious/proxy/MetricsIT.java [hunk 5]
```diff
@@ -32,11 +31,6 @@
 @ExtendWith(KafkaClusterExtension.class)
 public class MetricsIT {
 
-    @BeforeEach
-    public void beforeEach() {
-        Metrics.globalRegistry.clear();
-    }
-
```
Comment (SamBarker) [inline integrationtests/src/test/java/io/kroxylicious/proxy/MetricsIT.java:39]: In principal I quite like the fact that the test is ensuring the slate is clean before execution even if it is strictly not required.

**Review by SamBarker — APPROVED** [review]
+1 for a quieter build

File: kroxylicious/src/test/java/io/kroxylicious/proxy/micrometer/StandardBindersHookTest.java [hunk 6]
```diff
@@ -8,46 +8,78 @@
...
 
 import static org.assertj.core.api.Assertions.assertThat;
 import static org.assertj.core.api.Assertions.assertThatThrownBy;
+import static org.mockito.Mockito.verify;
 
+@ExtendWith(MockitoExtension.class)
 class StandardBindersHookTest {
 
+    private static final String AUTO_CLOSEABLE_BINDER = "AutoCloseableBinder";
+    @Mock(extraInterfaces = AutoCloseable.class)
```
[the remark this answers is not in the document]
Comment (k-wall) [reply kroxylicious/src/test/java/io/kroxylicious/proxy/micrometer/StandardBindersHookTest.java:28]: Yeah, it was new to me too.  Let's hope we don't need it too much.

File: integrationtests/src/test/java/io/kroxylicious/proxy/MetricsIT.java (hunk 5 above)
Comment (k-wall) [reply integrationtests/src/test/java/io/kroxylicious/proxy/MetricsIT.java:39]: How about asserting that it is before/after empty?  That would at least alert us to meters being left around.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java (hunk 4 above)
Comment (k-wall) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java:90]: `prometheusMeterRegistry.getMeters()` cannot return null. It is documented as `The set of registered meters.`

I used a defensive copy to avoid the possibility of `ConcurrentModificationException`.  However, `prometheusMeterRegistry.getMeters()` actually produces an unmodifiable copy, so my wrap technically superfluous.  That said, the javadoc doesn't actually guarantee that's the case and `MeterRegistry#forEachMeter is backed by the live structure. Their API isn't too consistent.  That makes me want to keep the copy.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/micrometer/StandardBindersHook.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (k-wall) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/micrometer/StandardBindersHook.java:57]: Closeable extends AutoCloseable, so aren't we covered already?

File: integrationtests/src/test/resources/log4j2-test.properties (hunk 2 above)
Comment (k-wall) [reply integrationtests/src/test/resources/log4j2-test.properties:46]: It looks like someone (me - 7d673aee49b3a4c62a5ca8902c680a7c05987341 ) had left those loggers enabled after the multitenant work. That wasn't intentional.

The build was so noisy we were missing stack traces such as the ones that provoked this issue.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/micrometer/StandardBindersHook.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (SamBarker) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/micrometer/StandardBindersHook.java:57]: Oh yeah, ignore me!

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java (hunk 4 above)
Comment (SamBarker) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java:90]: The registry could be `null` iirc

File: integrationtests/src/test/java/io/kroxylicious/proxy/MetricsIT.java (hunk 5 above)
Comment (SamBarker) [reply integrationtests/src/test/java/io/kroxylicious/proxy/MetricsIT.java:39]: Hmm, that's sort of giving the tests multiple reasons to fail which I don't like, but as you say would detect leaks.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java (hunk 4 above)
Comment (k-wall) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/MeterRegistries.java:90]: prometheusMeterRegistry is assigned in the ctor and is not null.
