### PR TITLE
fix(entity-isolation): validate that separator, principal name and generated upstream name are legal kafka resource names.

### LINKED ISSUE #3523: Entity Isolation Filter should validate that separator and principal name conform to Kafka rules for legal resource names.
@tombentley, comment on the documentation for the Entity Isolation FIlter:

>The user doesn't have a free choice about the separator. It has to be something that fits the lexical rules that the broker applies to the correpsonding entity. For topics that's alnum + `.`, `-` and `_`. We should mention this.

This also highlights that the filter itself should:

1. validate that the separator itself is valid for inclusion in a Kafka resource name.  This is a startup time check.
2. validate that the naming resulting from the mapping is a valid Kafka resource name.  This is a runtime check as this depends on the principal name.

The current behaviour if that the the broker would fail, but fail early (in the proxy) is a better approach.

_Originally posted by @tombentley in https://github.com/kroxylicious/kroxylicious/pull/3502#discussion_r2972082207_

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Fixes #3523: validate that separator, principal name and generated upstream name are legal kafka resource names. This change should means we fail early (in the proxy) rather than failing late (in the broker).

In Kafka, for topic names and group names, kafka resource names may contain only ASCII alphanumerics and `.`, `_`, and `-` and must be 249 characters or less.  Transactional ids must not be empty, but otherwise have no restrictions.
See `org.apache.kafka.common.internals.Topic`.

With this change:
* fail at startup if separator contains a characters that is not ASCII alphanumerics or `.`, `_`, and `-`.
* fail at runtime (`UNKNOWN_SERVER_ERROR`) if a principal is used that contains a characters that is not ASCII alphanumerics or `.`, `_`, and `-`.
* fail at runtime (`UNKNOWN_SERVER_ERROR`) if the generated upstream name violates the length restriction (topics and groupids only).

### Additional Context

There's https://cwiki.apache.org/confluence/display/KAFKA/KIP-1233%3A+Maximum+lengths+for+resource+names+and+IDs which is hoping to regularise Kafka resource name restrictions.  It also proposes error code `RESOURCE_IDENTIFIER_TOO_LARGE`  to be used when (non-topic) resource names are too large.  If that ever becomes reality, this filter should consider using it in place of `UNKNOWN_SERVER_ERROR` used today.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [x] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-filters/kroxylicious-entity-isolation/src/main/java/io/kroxylicious/filter/entityisolation/FindCoordinatorEntityIsolationProcessor.java [hunk 1]
```diff
@@ -83,27 +98,37 @@ public boolean shouldHandleResponse(short apiVersion) {
     @SuppressWarnings("java:S2638") // Tightening UnknownNullness
     public CompletionStage<ResponseFilterResult> onResponse(ResponseHeaderData header,
                                                             short apiVersion,
-                                                            @Nullable EntityIsolation.EntityType requestedEntityType,
+                                                            @NonNull CoordinatorType requestedCoordinatorType,
```
Comment (tombentley) [inline kroxylicious-filters/kroxylicious-entity-isolation/src/main/java/io/kroxylicious/filter/entityisolation/FindCoordinatorEntityIsolationProcessor.java:101]: `@NonNull` is the default, so it shouldn't be needed

Comment (k-wall) [reply kroxylicious-filters/kroxylicious-entity-isolation/src/main/java/io/kroxylicious/filter/entityisolation/FindCoordinatorEntityIsolationProcessor.java:101]: It exists to tighten the `@UnknownNullness` declaration on the interface. 

I used `@UnknownNullness` on `EntityIsolationProcessor#onResponse` as it is up to the implementation to decide whether it needs request context or not.  In this case, `FindCoordinatorEntityIsolationProcessor` needs request context. It implements `#createCorrelatedRequestContext`.  It now knows `requestedCoordinatorType` parameter of `onResponse` will be NonNull.  Is that reasonable?
