### PR TITLE
Don't throw threads around like confetti 

### LINKED ISSUE #385: Thread leak
As noticed by @gracegrimwood in chat:
```
[ERROR] io.kroxylicious.mock.MockServerTest.testClientCanSendAndReceiveRPCToMock(ApiAndVersion)[67]  Time elapsed: 2.071 s  <<< ERROR!
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:97)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:92)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:73)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:53)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:45)
	at io.kroxylicious.test.client.KafkaClient.<init>(KafkaClient.java:58)
	at io.kroxylicious.mock.MockServerTest.testClientCanSendAndReceiveRPCToMock(MockServerTest.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	```
Which is triggered by: 
 https://github.com/kroxylicious/kroxylicious/blob/75cc5a28f9d7e7b77df126e1661d772209d5e76c/kroxylicious-test-tools/src/main/java/io/kroxylicious/test/client/KafkaClient.java#L58 creating a new NioEventLoop group which by default creates an eventLoopGroup with `2 * core_count` threads. 
 
 `MockServerTest.testClientCanSendAndReceiveRPCToMock` is a parameterized test with 271 api key and version combinations leading to a huge number of threads being churned through. Locally I see a thread named `nioEventLiioGroup-814-1`.

### PR DESCRIPTION
**Pull request by SamBarker**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Reduce the number of threads created when using the mock server and Kafka Client and use platform native sockets where available.

### Additional Context

Creating a new KafkaClient instance creates a new NioEventLoopGroup using the no args constructor which by defaults to creating `2 * coreCount` threads. When run as part of `io.kroxylicious.mock.MockServerTest#testClientCanSendAndReceiveRPCToMock` ends up running 271 times for a single method resulting in churning through roughly 13,000 threads (which seems a little excessive).

The first commit replaces the no args ctor by supplying a thread count of 1. Which reduces the thread count to roughly 7k threads as the mock server is left alone. 

The second commit goes much further and reduces the thread count for the mock server as well and switches to using platform specific event loops where available. 

Fixes #385

### CODE REVIEW

File: kroxylicious-test-tools/src/main/java/io/kroxylicious/test/client/EventGroupConfig.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        else if (KQueue.isAvailable()) {
+            return new KQueueEventLoopGroup(nThreads);
+        }
+        else {
+            return new NioEventLoopGroup(nThreads);
+        }
+    }
+
+    public EventLoopGroup newWorkerGroup() {
+        return newGroup(1);
```
Comment (SamBarker) [inline kroxylicious-test-tools/src/main/java/io/kroxylicious/test/client/EventGroupConfig.java:60]: This feels a little suspect and controversial but is probably fine for tests.
