### PR TITLE
fix: Handle HAProxy protocol in TLS pipeline

### LINKED ISSUE #287: HA Proxy/TLS use-case broken.
**Describe the bug**

The handling of the HA Proxy message is broken in the TLS case.  The handler is installed after the SSL handler rather than before. The HA Proxy message is always the first thing down the wire and is not subject to SSL.

We should also have integration tests verifying that it is doing the right thing.

**To Reproduce**
1. Configure kroxylicious like this ...
2. Run command '....'
3. See error

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by hrishabhg**
### Type of change

- Bugfix

### Description

Fixes HAProxy PROXY protocol handling when TLS is enabled. In the TLS pipeline, the PROXY header arrives before the SSL handshake completes, so the frontend handler is not yet active. Previously this caused the message to be lost.

This PR:
* Adds `HAProxyMessageHandler` (extends Netty's `SimpleChannelInboundHandler<HAProxyMessage>`) to intercept PROXY protocol messages. `SimpleChannelInboundHandler` provides two key behaviours: it auto-releases the reference-counted `HAProxyMessage` after `channelRead0` returns, and it only matches `HAProxyMessage` instances — all other inbound messages are automatically forwarded via `fireChannelRead`, so Kafka frames pass through to downstream handlers untouched.
* Introduces `HAProxyContext` record that deep-copies all fields (including TLV content as `byte[]`) from the Netty `HAProxyMessage`, so the context remains valid after the message is released.
* Removes `HAProxyMessage` from the `ProxyChannelState` records (`HaProxy`, `SelectingServer`, `Connecting`, `Forwarding`). The state machine no longer carries the raw reference-counted object through state transitions — the durable context lives on `KafkaSession.haProxyContext()`.
* For TLS pipeline: extracts context eagerly and sets a `haProxyMessagePending` flag. When `onClientActive` fires after the SSL handshake, the flag triggers the `ClientActive → HaProxy` state transition without needing the raw message.
* Guards `onClientException` against NPE when `endpointBinding` is null (error before SNI/binding resolution, e.g. malformed PROXY header during TLS handshake).
* Adds root-level `ProxyProtocolConfig` (`proxyProtocol.enabled`) to enable PROXY protocol decoding via YAML configuration.
* Renames `getKafkaSession()` → `kafkaSession()` for consistency (per #3321 review feedback).

Resolves #287

### Node identification strategies

PROXY protocol is enabled globally — it applies to all listeners regardless of the gateway's node identification strategy (`portIdentifiesNode` or `sniHostIdentifiesNode`). When a load balancer sits in front of Kroxylicious, every incoming connection on every port/SNI hostname receives a PROXY header.

With `portIdentifiesNode`, the load balancer must forward each broker port individually (bootstrap + one port per broker node). With `sniHostIdentifiesNode`, a single LB listener with SNI passthrough can handle all brokers on a shared port.

### Follow-up work

* **Operator CRD support**: The Kubernetes operator does not yet expose `proxyProtocol` through the `KafkaProxy` CRD. A subsequent PR will add the field to the CRD spec and wire it through `KafkaProxyReconciler`.
* **Rename `KafkaSession` → `ClientSession`**: `KafkaSession` currently holds per-client state (HAProxy context, auth identity) that is not Kafka-specific. A follow-up will rename it to `ClientSession` and relocate `ClientSubjectManager` concerns there, aligning with the routing design discussed in #3321.

### Additional Context

In a TLS+HAProxy pipeline the message flow is: PROXY header → SSL handshake → SNI resolution → `channelActive`. The PROXY header must be captured early and replayed into the state machine after the frontend handler is initialised.

### Checklist

- [x] Write tests
- [x] Update documentation
- [x] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [x] If applicable to the change, make sure system tests pass.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.

#### Screenshots
Screenshot 2026-04-01 at 9 37 22 PM
Screenshot 2026-04-01 at 9 39 43 PM
Screenshot 2026-04-01 at 9 43 05 PM

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/ProxyProtocolConfig.java [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+/**
+ * Configuration for the HAProxy PROXY protocol.
+ * <p>
+ * When enabled, Kroxylicious expects every incoming connection to begin with a
+ * PROXY protocol header (v1 or v2) as sent by an upstream load-balancer.
+ * The original client address information is extracted and made available
+ * to the proxy session.
+ * </p>
+ *
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/ProxyProtocolConfig.java:18]: Let's add a link to where the PROXY protocol is defined. I think the most recent document is https://www.haproxy.org/download/3.3/doc/proxy-protocol.txt

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java [hunk 2]
```diff
@@ -50,7 +51,8 @@ public record Configuration(
                             @Nullable List<MicrometerDefinition> micrometer,
                             boolean useIoUring,
                             Optional<Map<String, Object>> development,
-                            @Nullable NetworkDefinition network) {
+                            @Nullable NetworkDefinition network,
+                            @Nullable ProxyProtocolConfig proxyProtocol) {
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: I think it would be more in-keeping if this was defined at the virtual cluster level. That's where all the other networking stuff gets configured. It seems unexpected for this to be defined at the top level.

File: kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc [hunk 3]
```diff
@@ -0,0 +1,29 @@
+:_mod-docs-content-type: CONCEPT
+
+[id='con-configuring-proxy-protocol-{context}']
+= Configuring HAProxy PROXY protocol
+
+[role="_abstract"]
+When Kroxylicious is deployed behind a load balancer that uses the https://www.haproxy.org/download/2.9/doc/proxy-protocol.txt[HAProxy PROXY protocol], you can enable PROXY protocol decoding so that the original client connection metadata (source address, destination address, ports) is preserved.
```
Comment (tombentley) [inline kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc]: I'm wondering which version is the best to link to. The most recent version is https://www.haproxy.org/download/3.3/doc/proxy-protocol.txt. The diffs between 2.9 and 3.3 seem to be limited to `PP2_SUBTYPE_SSL_GROUP` and `PP2_SUBTYPE_SSL_SIG_SCHEME`.

File: kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+<1> Top-level PROXY protocol configuration.
+<2> Set to `true` to enable PROXY protocol decoding. Defaults to `false`.
+
+When enabled, Kroxylicious expects *every* incoming connection (on both TLS and plain listeners) to begin with a PROXY protocol header.
+The original client address information is extracted and made available to the proxy session.
+
+[IMPORTANT]
+====
+Only enable this setting when Kroxylicious is behind a load balancer that sends PROXY protocol headers.
+If enabled without a PROXY protocol-capable load balancer, client connections will fail because the proxy expects a PROXY header that the client does not send.
```
Comment (tombentley) [inline kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc]: Can we give a hint about what that failure looks like? From the client side and/or how it would appear in the broker logs?

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java [hunk 5]
```diff
@@ -68,18 +66,17 @@ public HaProxy toHaProxy(HAProxyMessage haProxyMessage) {
...
     /**
-     * A PROXY protocol header has been received on the channel
-     * @param haProxyMessage The information in the PROXY header
+     * A PROXY protocol header has been received on the channel.
+     * The connection metadata is captured in the {@link KafkaSession}'s
+     * {@link io.kroxylicious.proxy.internal.net.HAProxyContext}.
      */
-    record HaProxy(
-                   HAProxyMessage haProxyMessage)
+    record HaProxy()
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java:80]: This record is spelled `HaProxy`, but you're also defined `HAProxyContext` and `HAProxyMessageHandler`. We should be consistent. For classes related to TLS we're using `Tls`, so I would suggest we use `Ha` as the prefix for these class names.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java (hunk 2 above)
Comment (hrishabhg) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: The PROXY protocol header arrives before TLS negotiation, so the HAProxy decoder must be in the pipeline before we know which virtual cluster the connection belongs to (especially for SNI-based routing). This makes per-virtual-cluster configuration tricky.

Additionally, PROXY protocol is a property of the network infrastructure — whether connections carry a PROXY header is determined by the upstream load balancer, not the application. All connections arriving at a Kroxylicious instance will either have PROXY headers or not, so a global setting seems like the natural fit.

Happy to discuss if you see a way to make per-gateway config work here.

Comment (SamBarker) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: I don't think we can assume all connections to an instance are behind identically configured load balancers, clients on the same K8s cluster will arrive via the service and off cluster clients will arrive via a load balancer. 

Though that makes any global options difficult.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java (hunk 5 above)
Comment (hrishabhg) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java:80]: I have renamed to `Ha` -> `HA` as per netty `HAProxyMessageDecoder`. Let me know if you think we should follow `Ha` .

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java (hunk 2 above)
Comment (hrishabhg) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: Good point — I hadn't considered the case where in-cluster clients connect directly via the K8s Service (no PROXY header) while off-cluster clients arrive through a load balancer (with PROXY header).

**Proposal:**
Netty's `HAProxyMessageDecoder` exposes a static `detectProtocol(ByteBuf)` method that can peek at the first bytes and determine whether they're a PROXY protocol header. We could use this to build an auto-detect mode — a small handler that checks the incoming bytes and dynamically adds the decoder only when a PROXY header is present. Similar to how Netty's `OptionalSslHandler` works.

That would allow both proxied and direct connections to work on the same port without needing per-gateway config. Something like:

```yaml
proxyProtocol:
  mode: auto  # auto | required | disabled (default)
```

**Why per-gateway config is problematic:**
The PROXY protocol header arrives before TLS negotiation, so for SNI-based gateways that share the same port, we don't know which gateway the connection belongs to until after the TLS handshake completes. Per-gateway config would mean we can't decide whether to expect a PROXY header until it's too late.

Would that work for the use case you have in mind?

File: kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc (hunk 4 above)
Comment (hrishabhg) [reply kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc]: Done

File: kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc (hunk 3 above)
Comment (hrishabhg) [reply kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc]: Added latest.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java (hunk 2 above)
Comment (SamBarker) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: That sounds reasonable. Though I wonder if we can be smarter by decoupling detection from enforcement.

The idea would be to always install a detection handler unconditionally at the network layer — a lightweight peek at the first bytes using Netty's `HAProxyMessageDecoder`. This sidesteps the SNI timing problem you identified: detection fires before any routing decision, so we don't need to know which gateway the connection belongs to yet. The `proxyProtocol` block would then move to `VirtualClusterGateway` (consistent with where TLS lives) and control enforcement only, with three explicit modes:

- `disabled` (default when absent): header accepted and discarded if present
- `optional`: header used if present, not required
- `required`: connection closed if no header is present

Because detection is always-on and enforcement is evaluated *after* TLS/SNI has identified the gateway, per-gateway config works correctly even for SNI gateways sharing a port — each gateway can independently declare its enforcement mode without any ambiguity at the point the PROXY header arrives.

`disabled` is the right default even though detection is always-on. The PROXY protocol spec is fairly explicit that accepting connections both with and without the header is dangerous — any client that can reach the port directly can inject a spoofed source IP. Making `optional` the default would mean silently trusting whatever source IP a connection claims, with no indication in the config that this is happening. Keeping `disabled` as the default ensures the security implications are visible at the point where someone makes a conscious decision to opt in. `optional` remains useful when the network topology guarantees only trusted load balancers reach the port, but worth documenting clearly as a footgun without that guarantee.

On client IP propagation — once Kroxylicious has the address from the header, how does it become available to filters and other consumers? That doesn't appear to be covered yet and seems like a necessary follow-on.

Comment (tombentley) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: > On client IP propagation — once Kroxylicious has the address from the header, how does it become available to filters and other consumers? That doesn't appear to be covered yet and seems like a necessary follow-on.

I agree: This PR can make the mechanics work. A later PR can figure out the API for using the information that's now available.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java (hunk 5 above)
Comment (tombentley) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java:80]: Personally, I much prefer the regularity of treating initialisms like other words. And I think the precedent was set with `Tls`, so if it's not too much effort can we adopt `Ha`?

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java (hunk 2 above)
Comment (hrishabhg) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: I differ a lot here :) 

1. When `disabled`, detection stays off — no decoder in the pipeline. Detection only kicks in when the gateway mode is `optional` or `required`. Since this is a new feature and not yet mature, keeping `disabled` completely inert is the safer starting point — we can always loosen this later if needed.

2. Since TLS/SNI and gateway identification happen after the PROXY header arrives, the handler should hold the decoded message and defer action until the gateway is known — then accept or reject based on the mode.

3. I'd prefer being transparent and documenting how things work rather than adding policy layers. If an operator configures PROXY protocol at the gateway level, either it works as described, or we enforce that gateways sharing a port must use the same mode — similar to how the same port can't mix TLS and plaintext today. Adding complex per-port mode validation isn't worth the cost at this stage.

----
+1 to Tom's point. I'm thinking of moving client-side state into `KafkaSession` (renamed to `ClientSession`). For example, right now `ProxyChannelStateMachine` has `clientSaslContext()` — this could be refactored so that `ProxyChannelStateMachine` holds a reference to `ClientSession` and accesses client-specific things through it.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java (hunk 5 above)
Comment (tombentley) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelState.java:80]: Thanks @hrishabhg

**Comment by hrishabhg** [comment]
@SamBarker @tombentley the code is manually tested by running the kroxylicious application running behind the envoy and is working as expected. I have attached snapshots in the description.

 I will add the examples in `kroxylicious-operator/packaging/examples` post this PR merge during operator changes.

**Comment by hrishabhg** [comment]
@kroxylicious-robot run system-tests

**Comment by tombentley** [comment]
@kroxylicious-robot run system-tests

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java (hunk 2 above)
Comment (tombentley) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/Configuration.java:55]: > Adding complex per-port mode validation isn't worth the cost at this stage.

I think this is a reasonable balance for now. We either build something elaborate now, or later. My preference is to delay elaborateness; that way when we add bells and whistles it can be on the basis of what users are actually needing. If that never happens we won't have incurred the opportunity costs of over-engineering something now.

File: kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+
+== Proxy protocol modes
+
+The `proxyProtocol.mode` property controls how Kroxylicious handles incoming connections:
+
+`required`:: Every incoming connection *must* begin with a PROXY protocol header.
+Connections without a valid header are rejected immediately with a warning log.
+Use this when Kroxylicious is always behind a PROXY protocol-capable load balancer.
+
+`auto`:: Kroxylicious inspects the first bytes of each connection and automatically detects whether a PROXY protocol header is present.
```
Comment (tombentley) [inline kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc]: `allowed` or `detected` might be slightly more descriptive. "Auto" on its own doesn't provide a very strong hint about _what_ is automatic.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+import io.kroxylicious.proxy.config.ProxyProtocolMode;
+
+/**
+ * Uses {@link HAProxyMessageDecoder#detectProtocol(ByteBuf)} on the first bytes
+ * of a connection to decide whether to install the PROXY protocol decoder.
+ * <p>
+ * In {@link ProxyProtocolMode#REQUIRED} mode, non-PROXY bytes cause the
+ * connection to be closed with a warning. In {@link ProxyProtocolMode#AUTO}
+ * mode, non-PROXY bytes are simply passed through to the Kafka decoder.
+ * </p>
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java:28]: For completeness:

```suggestion
 * This filter is not used when the proxy is in {@link ProxyProtocolMode#DISABLED} mode.
 * </p>
```

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyMessageHandler.java [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+                ctx.channel(),
+                haProxyMessage.sourceAddress(),
+                haProxyMessage.sourcePort(),
+                haProxyMessage.destinationAddress(),
+                haProxyMessage.destinationPort());
+
+        // Extract context into KafkaSession and signal the state machine.
+        // The HaProxyContext deep-copies all fields, so it remains valid
+        // after SimpleChannelInboundHandler releases the message.
+        proxyChannelStateMachine.onHAProxyMessageReceived(haProxyMessage);
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyMessageHandler.java]: Is there any reason not to do the `HaProxyContext.from(msg)` conversion here? Passing around the immutable safe thing seems preferable.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java [hunk 9]
```diff
@@ -0,0 +1,83 @@
...
+        if (proxyDetected) {
+            LOGGER.debug("{}: PROXY protocol detected, adding decoder", ctx.channel());
+            String thisName = ctx.name();
+            ctx.pipeline().addAfter(thisName, HAPROXY_MESSAGE_DECODER_HANDLER_NAME, new HAProxyMessageDecoder());
+            ctx.pipeline().addAfter(HAPROXY_MESSAGE_DECODER_HANDLER_NAME, HAPROXY_MESSAGE_HANDLER_NAME,
+                    new HaProxyMessageHandler(proxyChannelStateMachine));
+            ctx.pipeline().remove(this);
+            ctx.fireChannelRead(buf);
+        }
+        else if (mode == ProxyProtocolMode.REQUIRED) {
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java]: The logic appears flawed in the case the detection returned `NEEDS_MORE_DATA`. Certainly in the case of AUTO mode and `NEEDS_MORE_DATA` I don't see how it's correct to say "No PROXY protocol header detected".

I've not looked closely at the PROXY spec to figure out whether a prefix of a PROXY header could ever be a prefix of the Kafka request, but I think we should handle `NEEDS_MORE_DATA` explicitly so that the code remains easy to reason about.

We should also have tests which cover all the return values of `HAProxyMessageDecoder.detectProtocol()`.

**Review by tombentley — COMMENTED** [review]
Thanks @hrishabhg, I made another pass with a few more comments.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java (hunk 9 above)
Comment (hrishabhg) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java]: For `NEEDS_MORE_DATA`, the plan is to buffer bytes and retry detection on the next `channelRead`. Once enough bytes arrive (~12 for the v2 signature), `detectProtocol()` resolves to `DETECTED` or `INVALID` and we proceed as normal. The existing `preSessionIdleHandler` (`IdleStateHandler` added at pipeline head in `KafkaProxyInitializer`) already closes idle connections, so no extra timeout is needed.

Rough shape of the change:

```java
private ByteBuf cumulation;

@Override
public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
    if (!(msg instanceof ByteBuf buf)) {
        super.channelRead(ctx, msg);
        return;
    }

    if (cumulation == null) {
        cumulation = buf;
    } else {
        cumulation = ctx.alloc().compositeBuffer()
                .addComponents(true, cumulation, buf);
    }

    var result = HAProxyMessageDecoder.detectProtocol(cumulation);
    switch (result.state()) {
        case DETECTED -> {
            // install decoder + handler, forward cumulation
        }
        case NEEDS_MORE_DATA -> {
            // wait for next channelRead, cumulation stays
        }
        case INVALID -> {
            if (mode == ProxyProtocolMode.REQUIRED) {
                // reject
            } else {
                // pass through cumulation to Kafka decoder
            }
        }
    }
}

@Override
public void handlerRemoved(ChannelHandlerContext ctx) {
    if (cumulation != null) {
        cumulation.release();
        cumulation = null;
    }
}
```

`NEEDS_MORE_DATA` only happens with TCP fragmentation delivering < 12 bytes in the first segment. Extremely unlikely in practice, but technically possible.

If this looks good to you, I will go ahead with the implementation.

Comment (hrishabhg) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java]: @tombentley ^

Comment (hrishabhg) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java]: implemented.

Comment (tombentley) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java]: Please accept my apologies @hrishabhg it's been a busy week and this got lost in my inbox. What you have there appears reasonable to me. Thanks.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 10]
```diff
@@ -185,13 +205,24 @@ public String label() {
...
+    }
+
+    /**
+     * Called once the endpoint binding has been resolved (after SNI/plain resolver completes).
+     * Initialises all binding-dependent state and metrics.
+     *
+     * @param endpointBinding the resolved binding
+     * @param transportSubjectBuilder the subject builder for this virtual cluster
+     */
+    public void onBindingResolution(EndpointBinding endpointBinding, TransportSubjectBuilder transportSubjectBuilder) {
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: The two-phase construction introduced here converts 9 previously-`final` fields to `@Nullable` mutable fields (all the metrics counters, timers, activation tokens, `endpointBinding`, `transportSubjectBuilder`). This roughly doubles PCSM's mutable field count and sprinkles null-checks through `toClosed`, `incrementAppropriateDisconnectsMetric`, etc.

An alternative that avoids this: the detection handler and message handler don't need a `ProxyChannelStateMachine` reference at all. They only need somewhere to store the `HaProxyContext`. `KafkaSession` already serves this purpose (this PR adds `setHaProxyContext` / `haProxyContext()` to it).

If the handlers stored the context in `KafkaSession` directly (via a channel attribute or a direct reference passed from `initChannel`), PCSM creation could remain in `addHandlers` — as it was before this PR — taking `(EndpointBinding, TransportSubjectBuilder, KafkaSession)` with all fields final. In `onClientActive`, PCSM would check `kafkaSession.haProxyContext()` and transition to `HaProxy` if present. In the PLAIN path, `onClientRequest` in `ClientActive` state would do the same check.

This would eliminate: this method, the `haProxyMessagePending` flag, `onHaProxyMessageReceived`, the placeholder counter, the `globalRegistry.remove` call, and all the new null-checks on metrics.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 11]
```diff
@@ -185,13 +205,24 @@ public String label() {
     @Nullable
     private KafkaProxyBackendHandler backendHandler;
 
-    public ProxyChannelStateMachine(EndpointBinding endpointBinding,
-                                    TransportSubjectBuilder transportSubjectBuilder) {
+    public ProxyChannelStateMachine(KafkaSession kafkaSession) {
+        this.kafkaSession = kafkaSession;
+        // Placeholder until onBindingResolution() is called; needed because onClientException()
+        // can be triggered before binding is resolved (e.g. bad HaProxy header in TLS pipeline).
+        this.clientToProxyErrorCounter = Metrics.clientToProxyErrorCounter("", null).withTags();
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: This registers a real counter with empty labels in the global Micrometer registry. If the connection fails before `onBindingResolution` is called (e.g. the detection handler rejects a non-PROXY connection in REQUIRED mode and closes the channel), this placeholder stays in the registry permanently — `onBindingResolution` never runs to remove it.

If the two-phase construction approach is kept, a no-op counter or a null field with a guard in `onClientException` would avoid the leak.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 12]
```diff
@@ -200,6 +231,7 @@ public ProxyChannelStateMachine(EndpointBinding endpointBinding,
         clientToProxyDisconnectsIdleCounter = Metrics.clientToProxyDisconnectsCounter(clusterName, nodeId, DisconnectCause.IDLE_TIMEOUT.label()).withTags();
         clientToProxyDisconnectsClientClosedCounter = Metrics.clientToProxyDisconnectsCounter(clusterName, nodeId, DisconnectCause.CLIENT_CLOSED.label()).withTags();
         clientToProxyDisconnectsServerClosedCounter = Metrics.clientToProxyDisconnectsCounter(clusterName, nodeId, DisconnectCause.SERVER_CLOSED.label()).withTags();
+        io.micrometer.core.instrument.Metrics.globalRegistry.remove(clientToProxyErrorCounter);
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: Reaching directly into `io.micrometer.core.instrument.Metrics.globalRegistry` to remove a counter couples this class to the global singleton. This is also fragile — it assumes the counter was registered in the global registry. Both this line and the placeholder counter it cleans up go away if the two-phase construction is eliminated (see comment on `onBindingResolution` above).

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 13]
```diff
@@ -168,8 +180,16 @@ public String label() {
...
+    @Nullable
+    private TransportSubjectBuilder transportSubjectBuilder;
     private final ClientSubjectManager clientSubjectManager = new ClientSubjectManager();
+    /**
+     * Whether an HaProxy message was received before the frontend handler was active
+     * (TLS pipeline). The context is extracted eagerly into {@link KafkaSession};
+     * this flag triggers the {@link ProxyChannelState.HaProxy} state transition
+     * when {@link #onClientActive(KafkaProxyFrontendHandler)} fires.
+     */
+    private boolean haProxyMessagePending;
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: This flag creates a temporal coupling: `onHaProxyMessageReceived` must fire before `onClientActive` in the TLS path, and `onClientActive` must check-and-clear the flag in the right order relative to the state transition.

If the channel-attribute / KafkaSession approach is adopted (see comment on `onBindingResolution`), this flag becomes unnecessary — `onClientActive` would check `kafkaSession.haProxyContext() != null` instead. If the current approach is kept, consider at least eliminating the flag by checking `kafkaSession.haProxyContext() != null` directly rather than maintaining a separate boolean, since the context is already stored in the session.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java [hunk 14]
```diff
@@ -0,0 +1,111 @@
...
+        if (!(msg instanceof ByteBuf buf)) {
+            super.channelRead(ctx, msg);
+            return;
+        }
+
+        if (cumulation == null) {
+            cumulation = buf;
+        }
+        else {
+            cumulation = Unpooled.wrappedBuffer(cumulation, buf);
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyProtocolDetectionHandler.java]: `Unpooled.wrappedBuffer` creates a composite-like wrapper. While this works, a `CompositeByteBuf` via `Unpooled.compositeBuffer().addComponents(true, cumulation, buf)` (or using the channel allocator) would be more idiomatic for Netty cumulation patterns and makes the ownership semantics explicit.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/net/HaProxyContext.java [hunk 15]
```diff
@@ -0,0 +1,59 @@
...
+ * @param sourcePort         the original client port
+ * @param destinationPort    the destination port
+ * @param tlvs               HaProxy v2 TLV extensions keyed by type name, values are {@code byte[]}
+ */
+public record HaProxyContext(
+                             String sourceAddress,
+                             String destinationAddress,
+                             int sourcePort,
+                             int destinationPort,
+                             Map<String, byte[]> tlvs) {
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/net/HaProxyContext.java:34]: The `byte[]` values in this map are mutable — callers can modify TLV content despite the record being documented as an "immutable snapshot". Consider defensive copies on access, or wrapping as read-only `ByteBuffer`, to match the immutability contract in the Javadoc.

File: kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc [hunk 16]
```diff
@@ -0,0 +1,55 @@
...
+The `proxyProtocol.mode` property controls how Kroxylicious handles incoming connections:
+
+`required`:: Every incoming connection *must* begin with a PROXY protocol header.
+Connections without a valid header are rejected immediately with a warning log.
+Use this when Kroxylicious is always behind a PROXY protocol-capable load balancer.
+
+`allowed`:: Kroxylicious inspects the first bytes of each connection and automatically detects whether a PROXY protocol header is present.
+If detected, the header is decoded and the original client address is extracted.
+If not, the bytes are passed through to the Kafka protocol decoder.
+Use this when the same listener may receive both proxied and direct connections.
```
Comment (tombentley) [inline kroxylicious-docs/docs/_modules/configuring/con-configuring-proxy-protocol.adoc:28]: Worth adding a security note here. In `allowed` mode, any client that can connect directly (bypassing the load balancer) can inject a PROXY header with a spoofed source IP. The PROXY protocol spec itself warns against accepting connections both with and without the header unless the network topology guarantees only trusted sources reach the port. An `[IMPORTANT]` admonition similar to the one for `required` mode would be appropriate.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/ProxyProtocolIT.java [hunk 17]
```diff
@@ -0,0 +1,303 @@
...
+
+import static io.kroxylicious.test.tester.KroxyliciousConfigUtils.defaultPortIdentifiesNodeGatewayBuilder;
+import static io.kroxylicious.test.tester.KroxyliciousTesters.mockKafkaKroxyliciousTester;
+import static org.assertj.core.api.Assertions.assertThat;
+
+/**
+ * Integration tests for HaProxy PROXY protocol support.
+ */
+@ExtendWith(NettyLeakDetectorExtension.class)
+class ProxyProtocolIT {
```
Comment (tombentley) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/ProxyProtocolIT.java:61]: Some test coverage gaps worth addressing:
- **ALLOWED + TLS with PROXY header present**: `tlsAllowedModeShouldAcceptDirectTlsConnectionWithoutProxyHeader` covers the "no header" case but not the converse — a TLS connection that *does* send a PROXY header in ALLOWED mode.
- **DISABLED mode**: no integration test verifies that a DISABLED proxy correctly handles a client that sends a PROXY header (it should be treated as a malformed Kafka request and rejected).

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 18]
```diff
@@ -504,7 +569,10 @@ void onServerException(@Nullable Throwable cause) {
      */
     @SuppressWarnings("java:S5738")
     void onClientException(@Nullable Throwable cause) {
-        var tlsEnabled = endpointGateway().getDownstreamSslContext().isPresent();
+        // endpointBinding may be null if the error occurs before binding resolution
+        // (e.g. bad HaProxy header during TLS handshake, before SNI completes).
+        var tlsEnabled = endpointBinding != null
```
Comment (tombentley) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java]: This null-check handles the case where an error occurs before binding resolution — a new code path introduced by this PR. The `clientErrorStates` parameterised test exercises `onClientException` from various states but always after `onBindingResolution` has been called (setUp invokes it). A test case exercising this path with `endpointBinding == null` would confirm the guard works correctly.

**Comment by tombentley** [comment]
@hrishabhg as you can see I used Claude to assist in the review. I filtered out a few of less relevant comments, but the ones above appear to be worth considering.

**Comment by hrishabhg** [comment]
> @hrishabhg as you can see I used Claude to assist in the review. I filtered out a few of less relevant comments, but the ones above appear to be worth considering.

@tombentley Thanks for the thorough review, Tom! I've addressed all the comments:

**two-phase PCSM construction:** Reworked the design so `HaProxyProtocolDetectionHandler` and `HaProxyMessageHandler` store the PROXY context in `KafkaSession` directly, before PCSM exists. PCSM is back to single-phase construction with all fields `final` — no placeholder counters, no `globalRegistry.remove()`, no `haProxyMessagePending` flag. `onClientActive` checks `kafkaSession.haProxyContext()` to replay the HaProxy transition.

**CompositeByteBuf:** Switched to `ctx.alloc().compositeBuffer().addComponents(true, ...)` for idiomatic Netty cumulation.

**defensive byte[] copies:** Added compact constructor that deep-copies TLV values and an accessor that returns cloned arrays.

**security admonition:** Added `[IMPORTANT]` block warning about source address spoofing in `allowed` mode.

**test gaps:** Added `tlsAllowedModeShouldAcceptTlsConnectionWithProxyHeader` and `disabledModeShouldRejectConnectionWithProxyHeader` integration tests.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyMessageHandler.java [hunk 19]
```diff
@@ -45,8 +47,7 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
                     .addKeyValue("destinationAddress", haProxyMessage.destinationAddress())
                     .addKeyValue("destinationPort", haProxyMessage.destinationPort())
                     .log("Received HAProxy message");
-            // Forward to state machine for processing - do not propagate to filters
-            proxyChannelStateMachine.onClientRequest(haProxyMessage);
+            kafkaSession.setHaProxyContext(HaProxyContext.from(haProxyMessage));
```
Comment (SamBarker) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/HaProxyMessageHandler.java]: The PR description says this handler originally extended `SimpleChannelInboundHandler<HAProxyMessage>` specifically for auto-release of the ref-counted `HAProxyMessage`. The actual code extends `ChannelInboundHandlerAdapter`, but the corresponding explicit release was never added.

When this branch handles an `HAProxyMessage` it neither calls `ReferenceCountUtil.release(haProxyMessage)` nor forwards it via `ctx.fireChannelRead(msg)`, so the ref-count is never decremented. Every PROXY protocol connection leaks one `HAProxyMessage` (and the TLV `ByteBuf` content it holds).

The fix is straightforward — either revert to `SimpleChannelInboundHandler<HAProxyMessage>` (the original intent) or add an explicit `ReferenceCountUtil.release(haProxyMessage)` at the end of the `instanceof` branch.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java [hunk 20]
```diff
@@ -333,6 +333,13 @@ void onClientActive(KafkaProxyFrontendHandler frontendHandler) {
                     .addKeyValue("remotePort", this.frontendHandler.remotePort())
                     .log("Allocated session ID for downstream connection");
             toClientActive(STARTING_STATE.toClientActive(), frontendHandler);
+            // If an HaProxy context was stored in KafkaSession (by the detection/message
+            // handlers before PCSM was created), transition ClientActive → HaProxy.
+            if (kafkaSession.haProxyContext() != null) {
+                if (state instanceof ProxyChannelState.ClientActive clientActive) {
+                    toHaProxy(clientActive.toHaProxy());
+                }
+            }
```
Comment (SamBarker) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java:341]: Nit: the `instanceof` pattern-match here is always true at this point — `toClientActive` on line 335 sets `state` to the `ClientActive` instance unconditionally, so the guard can be replaced with a direct call using the `clientActive` already in scope.

File: kroxylicious-docs/docs/_modules/configuring/con-configuration-outline.adoc [hunk 21]
```diff
@@ -33,6 +33,8 @@ virtualClusters:
       # ...
     subjectBuilder:
       # ...
+proxyProtocol: # <10>
+  enabled: false
```
Comment (SamBarker) [inline kroxylicious-docs/docs/_modules/configuring/con-configuration-outline.adoc]: The YAML example shows `proxyProtocol: enabled: false`, but `ProxyProtocolConfig` takes a `mode` field, not `enabled`. The correct YAML is:

```yaml
proxyProtocol:
  mode: disabled
```

The dedicated `con-configuring-proxy-protocol.adoc` page is correct — it's only this outline snippet that has the wrong field name.

**Comment by SamBarker** [comment]
Will merge once the docs, reference counting and tests are fixed

**Comment by hrishabhg** [comment]
> Will merge once the docs, reference counting and tests are fixed

resolved. thanks for pointing out the msg release. I believe during iterations, it got missed out during refactoring.

**Comment by tombentley** [comment]
@robobario I assume you're happy to merge this one in spite of the failing-but-known-flaky ITs, right?

**Comment by robobario** [comment]
> @robobario I assume you're happy to merge this one in spite of the failing-but-known-flaky ITs, right?

Yes

**Comment by tombentley** [comment]
Thanks @hrishabhg it's good to get this one over the line.
