### PR TITLE
operator: Use absolute service host for brokerAddressPattern

### LINKED ISSUE #1606: Broker address used by proxy uses relative DNS name
**Describe the bug**

I've been experimenting with the proxy.

The broker address used by the proxy assumes the client will run within the same namespace as the proxy. In other words, it uses a relative DNS rather than an absolute one.

```
kubectl -n my-proxy run node-list -ti --image=quay.io/kroxylicious/kaf --rm=true --restart=Never -- kaf node ls -b my-cluster.my-proxy.svc.cluster.local:9292
ID    ADDRESS           CONTROLLER
0     my-cluster:9293   true
```

**To Reproduce**
1. Deploy the proxy operator as per kroxylicious-operator/DEV_GUIDE.md
2. Use Strimzi [quickstart](https://strimzi.io/quickstarts/) to deploy Strimzi operator and create `kafka-single-node`.
3. Create a proxy using the following:
```yaml
metadata:
  name: simple
  namespace: my-proxy
spec:
  clusters:
  - name: my-cluster
    upstream:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9092
```
4. Create a topic running the client in the same namespace as the proxy (works)
```
kubectl -n my-proxy run node-list -ti --image=quay.io/kroxylicious/kaf --rm=true --restart=Never -- kaf topic create  -b my-cluster.my-proxy.svc.cluster.local:9292  foo
```
5. Create a topic running the client in the different namespace as the proxy (**fails**)
```
kubectl -n kafka run node-list -ti --image=quay.io/kroxylicious/kaf --rm=true --restart=Never -- kaf topic create  -b my-cluster.my-proxy.svc.cluster.local:9292  bar
Could not create topic bar: dial tcp: lookup my-cluster on 10.96.0.10:53: no such host

pod "node-list" deleted
pod kafka/node-list terminated (Error)
```
**Expected behavior**

I should be able to run the client anywhere on the cluster (assuming sufficient RBAC of course).

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

io.kroxylicious.kubernetes.operator.ClusterService#serviceName should be generating a FQDN.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Enables client pods in arbitrary namespaces to connect to the proxy via the service created by the operator.

The brokerAddressPattern was previously the service name, which is resolved relative to the client pod namespace. So after clients retrieved cluster metadata via the proxy they could not connect to the brokers as they attempted to resolve the broker relative to their own namespace.

ie bootstrapping with `my-cluster.my-proxy.svc.cluster.local:9292` returned node addresses like `my-cluster:${brokerPort}` and the resolution failed in the client.

Closes #1606

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/Services.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+ */
+
+package io.kroxylicious.kubernetes.operator;
+
+import io.fabric8.kubernetes.api.model.HasMetadata;
+
+import edu.umd.cs.findbugs.annotations.NonNull;
+
+public class Services {
+    public static String absoluteServiceHost(@NonNull HasMetadata primary, @NonNull String serviceName) {
```
[the remark this answers is not in the document]
Comment (robobario) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/Services.java:14]: Because it's something more about k8s Service DNS than that particular Service. But happy to put it in there until a second usage crops up.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ClusterService.java [hunk 2]
```diff
@@ -48,6 +50,13 @@ static String serviceName(Clusters cluster) {
         return cluster.getName();
     }
 
+    /**
+     * @return the fully qualified service hostname
+     */
+    static String absoluteServiceHost(@NonNull KafkaProxy primary, @NonNull Clusters cluster) {
```
Comment (tombentley) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ClusterService.java:56]: The annotations on the package (`package-info.java`)  should mean `@NonNull` is the default.

File: kroxylicious-operator/src/test/resources/DerivedResourcesTest/filter-api-not-declared/in-KafkaProxy.yaml [hunk 3]
```diff
@@ -9,6 +9,7 @@ kind: KafkaProxy
 apiVersion: kroxylicious.io/v1alpha1
 metadata:
   name: example
+  namespace: my-proxy
```
Comment (tombentley) [inline kroxylicious-operator/src/test/resources/DerivedResourcesTest/filter-api-not-declared/in-KafkaProxy.yaml:12]: `my-proxy` sounds like it's the name a proxy, not a namespace. I wonder if we should change this to something like `proxy-ns` before we copy+paste it any further.

**Review by tombentley — APPROVED** [review]
A couple more nits, but otherwise this LGTM (assuming it actually works).

**Comment by robobario** [comment]
@tombentley mentioned from Strimzi's experience users can potentially change the internal DNS so we should look at making the `svc.cluster.local` host configurable. Let's add it in a separate PR.

**Comment by robobario** [comment]
ran through the reproduction in #1606

client in `my-proxy` namespace (same namespace as proxy):
```
kubectl -n my-proxy run node-list -ti --image=quay.io/kroxylicious/kaf --rm=true --restart=Never -- kaf topic create  -b my-cluster.my-proxy.svc.cluster.local:9292  foo
✅ Created topic!
      Topic Name:            foo
      Partitions:            -1
      Replication Factor:    1
      Cleanup Policy:        delete
pod "node-list" deleted
```

client in `kafka` namespace (different namespace from proxy):
```
kubectl -n kafka run node-list2 -ti --image=quay.io/kroxylicious/kaf --rm=true --restart=Never -- kaf topic create  -b my-cluster.my-proxy.svc.cluster.local:9292  bar
✅ Created topic!
      Topic Name:            bar
      Partitions:            -1
      Replication Factor:    1
      Cleanup Policy:        delete
pod "node-list2" deleted
```

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ClusterService.java [hunk 4]
```diff
@@ -48,6 +48,13 @@ static String serviceName(Clusters cluster) {
         return cluster.getName();
     }
 
+    /**
+     * @return the fully qualified service hostname
+     */
+    static String absoluteServiceHost(KafkaProxy primary, Clusters cluster) {
+        return serviceName(cluster) + "." + primary.getMetadata().getNamespace() + ".svc.cluster.local";
```
Comment (SamBarker) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ClusterService.java:55]: Doesn't this assume that we are only supporting in cluster access? Don't we need some way of determining the external name? 

or does that get layered on top somewhere else?

**Review by SamBarker — APPROVED** [review]
LGTM

I'm not sure 100% sure about including `primary.getMetadata().getNamespace() + ".svc.cluster.local"` but I think its good enough for this PR.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ClusterService.java (hunk 4 above)
Comment (tombentley) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ClusterService.java:55]: In-cluster is our current objective. Off-cluster is for later, and you end up doing _a la_ Strimzi with things like `NodePort`, Load balancer and `Ingress`. Or I suppose to could also look at layering on top of Gateway API, decorator style.
