### PR TITLE
Fix #1900: Enforce business rule that a proxy must have at least one virtual cluster

### LINKED ISSUE #1900: Null/omitted virtualClusters in config YAML causes unhelpful NullPointerException
**Describe the bug**

**To Reproduce**
1. Create a configuration YAML like:
   ```
   adminHttp:
     endpoints:
       prometheus: {}
   ```
2. start up the proxy
3. It fails with exception like:
   ```
   java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.virtualClusters" is null
	at io.kroxylicious.proxy.config.Configuration.virtualClusterModel(Configuration.java:293)
	at io.kroxylicious.proxy.KafkaProxy.<init>(KafkaProxy.java:93)
	... snip
	at io.kroxylicious.app.Kroxylicious.main(Kroxylicious.java:123)
   ```
**Expected behavior**
A better exception that says virtualCluster is a required property, or states that we require >=1 virtualCluster defined, rather than an NPE.

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Bugfix

### Description

It doesn't make sense to run a proxy without at least on virtual cluster.  Currently, there if one tries to do it, you get a NPE.

This PR changes:

1. The proxy so that the no virtual cluster case is trapped and reported cleanly.
2. The operator is changed so that operator omits to generate a configuration configmap if the proxy is illegal.

Internally, the operator now uses a `reconcilePrecondition` to conditionally create the configuration configmap.  If the configuration would violate a business rule, the map won't be created (or it will be deleted).  (This will mean the Operator pod won't start as the configmap volume mount will be absent).

The operator used the configuration configmap to relay the virtual cluster conditions to the virtual cluster reconciler.  This has been refactored to use a separate `config-state` config map.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [x] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [x] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java [hunk 1]
```diff
@@ -148,15 +149,20 @@ String generateProxyConfig(KafkaProxy primary,
...
+                    null, // no defaultFilters <= each of the virtualClusters specifies its own
+                    virtualClusters,
+                    List.of(), false,
+                    // micrometer
+                    Optional.empty());
+
+            return toYaml(configuration);
+        }
+        catch (IllegalConfigurationException e) {
+            return "# Unable to generate a valid configuration (reason: %s)".formatted(e.getMessage());
```
Comment (tombentley) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java:164]: What's your thinking here?

**Comment by k-wall** [comment]
Still working on this one

**Comment by k-wall** [comment]
I've changed the operand to reject configuration if it doesn't provide at least one virtual clusters.  I needed to make a change to the operator keep the tests passing.  I chose to have the operator create a configmap containing an empty object.  I don't think this is solution we'll ultimately want.  @robobario started a conversation on #1901 about operator behaviour here.  I suggest we merge this PR, and use #1901 to work out the operator behaviour we need.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java (hunk 1 above)
Comment (k-wall) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java]: Please see my comment below.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java [hunk 2]
```diff
@@ -125,13 +126,23 @@ protected ConfigMap desired(KafkaProxy primary,
...
     }
 
-    String generateProxyConfig(KafkaProxy primary,
-                               Context<KafkaProxy> context) {
+    @NonNull
+    private Map<String, String> generateDataMap(KafkaProxy primary, Context<KafkaProxy> context) {
+        try {
+            return Map.of(CONFIG_YAML_KEY, generateProxyConfig(primary, context));
+        }
+        catch (IllegalConfigurationException e) {
```
Comment (k-wall) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java:139]: Would we be better to use a io.javaoperatorsdk.operator.api.reconciler.dependent.Dependent#reconcilePrecondition so that the dependant produced if the Configuration would be invalid?

**Comment by k-wall** [comment]
@SamBarker @robobario I'd appreciate a review on the overall approach.  I've still got several things to iron out in the code.

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/DerivedResourcesTest.java [hunk 3]
```diff
@@ -155,6 +155,14 @@ public Class<R> resourceType() {
 
         @Override
         public Map<String, R> invokeDesired(P primary, Context<P> context) {
+
+            // FIX ME
```
Comment (k-wall) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/DerivedResourcesTest.java:159]: To fix

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigStateConfigMap.java [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+import io.kroxylicious.kubernetes.operator.resolver.ResolutionResult;
+
+import static io.kroxylicious.kubernetes.operator.Labels.standardLabels;
+import static io.kroxylicious.kubernetes.operator.ResourcesUtil.namespace;
+
+/**
+ * Generates a Kube {@code ConfigMap} containing some internal state related to proxy configuration.
+ */
+@KubernetesDependent
+public class ProxyConfigStateConfigMap
```
Comment (robobario) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigStateConfigMap.java:34]: To make sure I've got this, we use a distinct configmap containing the conditions. This will provide a reliable ConfigMap for the virtual kafka cluster reconciler to use for it's status regardless of what's going on with the proxy config ConfigMap and we can choose to materialize or delete the proxy config as we please.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java [hunk 5]
```diff
@@ -94,16 +98,26 @@ public static List<VolumeMount> secureVolumeMounts(ManagedWorkflowAndDependentRe
...
                                 Context<KafkaProxy> context) {
-        Clock clock = KafkaProxyContext.proxyContext(context).clock();
-        var data = new ProxyConfigData();
-        data.setProxyConfiguration(generateProxyConfig(context));
-
-        ProxyModel proxyModel = KafkaProxyContext.proxyContext(context).model();
-        addResolvedRefsConditions(clock, proxyModel, data);
-        addAcceptedConditions(clock, proxyModel, data);
+        // the configuration object won't be present if isMet has returned false
+        // this is the case if the dependant resource is to be removed.
```
Comment (robobario) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java:118]: does desired get called if the precondition is false? seems a bit surprising that it gets the desired state of the dependent resource if JOSDK is going to delete it.

**Review by robobario — COMMENTED** [review]
The approach looks good to me, splitting the state/config maps is a nice idea. Sorry, we've merged more conflicts to main meanwhile.

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigStateConfigMap.java (hunk 4 above)
Comment (k-wall) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigStateConfigMap.java:34]: > To make sure I've got this, we use a distinct configmap containing the conditions. This will provide a reliable ConfigMap for the virtual kafka cluster reconciler to use for it's status regardless of what's going on with the proxy config ConfigMap and we can choose to materialize or delete the proxy config as we please

Exactly

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java (hunk 5 above)
Comment (k-wall) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigConfigMap.java:118]: > does desired get called if the precondition is false? seems a bit surprising that it gets the desired state of the dependent resource if JOSDK is going to delete it.

In the delete case, desired is called in order to identify the object that needs to be deleted.

**Comment by k-wall** [comment]
No problem.   I'll resolve the conflicts and iron out the remaining kinks.

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/DerivedResourcesTest.java [hunk 6]
```diff
@@ -155,6 +155,13 @@ public Class<R> resourceType() {
 
         @Override
         public Map<String, R> invokeDesired(P primary, Context<P> context) {
+
+            if (reconcilePrecondition != null) {
```
Comment (k-wall) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/DerivedResourcesTest.java:159]: I don't like this, but I think this is good enough for now.  
https://github.com/kroxylicious/kroxylicious/issues/2037

**Comment by k-wall** [comment]
@robobario @SamBarker I'm hope this is in good shape.  As I've expressed in Slack, I don't think DerivedResourcesTest is really the approach we want, but I think we address that separately #2037

**Comment by robobario** [comment]
rebased onto main and fixed up conflicts

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigDependentResource.java [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+
+    public ProxyConfigDependentResource() {
+        super(ConfigMap.class);
+    }
+
+    /**
+     * @return The {@code metadata.name} of the desired ConfigMap {@code Secret}.
+     */
+    static String configMapName(KafkaProxy primary) {
+        return ResourcesUtil.name(primary);
```
Comment (robobario) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyConfigDependentResource.java:56]: with the introduction of the second configmap it's now possible to cause problems by having two proxies one named `simple` and `simple-config-state` as both will try to manifest a `simple-config-state` ConfigMap for different reasons.

I think we should add a suffix to this one too, something like `-proxy-config`

**Review by robobario — APPROVED** [review]
LGTM once we've ensured both ConfigMap names have suffixes

**Comment by robobario** [comment]
pushed those changes up

File: kroxylicious-operator/examples/simple/01.KafkaProxy.simple.yaml [hunk 8]
```diff
@@ -8,6 +8,6 @@
 kind: KafkaProxy
 apiVersion: kroxylicious.io/v1alpha1
 metadata:
-  name: simple
+  name: simple-config-state
```
Comment (k-wall) [inline kroxylicious-operator/examples/simple/01.KafkaProxy.simple.yaml:11]: I guess this change was unintentional?

Comment (k-wall) [reply kroxylicious-operator/examples/simple/01.KafkaProxy.simple.yaml:11]: I'll fix, thank you for the changes.
