### PR TITLE
Fix metrics that were always scraped as zero

### LINKED ISSUE #266: Request Metrics are zero
**Describe the bug**
The request metrics (`kroxylicious_inbound_downstream_messages`, `kroxylicious_inbound_downstream_decoded_messages`, `kroxylicious_request_size_bytes`) are scraped as zero despite kroxy handling requests.

**To Reproduce**
1. Start up zookeeper and kafka with the default configuration from the apache distribution
2. Start kroxylicious `java -jar kroxylicious/target/kroxylicious-0.2.0-SNAPSHOT.jar -c kroxylicious/example-proxy-config.yml`
3. Produce some messages via kroxylicious `./bin/kafka-console-producer.sh --topic abc --bootstrap-server localhost:9192`
4. `curl localhost:9193/metrics`
5. observe all metrics are 0

**Expected behavior**
With the example config we should have metrics recorded for message count etc.

**Additional context**
The reason is we are pre-registering the meters with a different set of tags from the ones used later, which causes the later meter's data to silently not be scraped, see [comment here](https://github.com/kroxylicious/kroxylicious/pull/122#issuecomment-1413093573).   A limitation of the underlying prometheus java client.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

The message count and size metrics were always zero. This was because when we pre-registered the metrics we used a different set of tags. Data recorded later with the real tags was effectively invisible. This is a limitation of micrometer combined
with the prometheus java client and is quite silent.

To fix I've pulled more work into `io.kroxylicious.proxy.internal.util.Metrics` so that the pre-register and real usages both use the same code with the same tags. We also configure a meter filter that will explode early if we attempt to register a Meter with a different set of tags to existing filters, this is to make the failure visible.

I also removed pre-registration of the summary, this is because the summary is broken down by apiKey and apiVersion, we would have to pre-register the ~250 combinations to pre-register all possibilities.

### Additional Context

Closes #266

### CODE REVIEW

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java [hunk 1]
```diff
@@ -6,22 +6,55 @@
...
 public class Metrics {
 
     // creating a constant for all Metrics in the one place so we can easily see what metrics there are
 
-    public static final String KROXYLICIOUS_INBOUND_DOWNSTREAM_MESSAGES = "kroxylicious_inbound_downstream_messages";
+    private static final String KROXYLICIOUS_INBOUND_DOWNSTREAM_MESSAGES = "kroxylicious_inbound_downstream_messages";
+
+    private static final String KROXYLICIOUS_INBOUND_DOWNSTREAM_DECODED_MESSAGES = "kroxylicious_inbound_downstream_decoded_messages";
+
+    private static final String KROXYLICIOUS_REQUEST_SIZE_BYTES = "kroxylicious_request_size_bytes";
```
Comment (k-wall) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java:28]: As we use this counter for requests and responses (discriminated by flowing), would rpc_payload_size be a better name?

**Review by k-wall — APPROVED** [review]

**Comment by k-wall** [comment]
> I also removed pre-registration of the summary, this is because the summary is broken down by apiKey and apiVersion, we would have to pre-register the ~250 combinations to pre-register all possibilities.

If we don't pre-register, don't we run the risk of https://github.com/strimzi/strimzi-canary/issues/215.   Maybe that is acceptable, but I normally favour correctness.

That said, I can understand  the reluctance  to register apiKey * apiVersion * virtual cluster * broker metrics.

I wonder if we should continue to preregister but be restrictive on the set of apikeys that we record this metric for.  After all, I think the usual use-case for this stat will be produce and fetch, so perhaps by default we should restrict this metric to those keys.   Configuration could allow a user to configure the set. WDYT?

**Comment by k-wall** [comment]
Could we improve MetricsIT so we actually make sure we are actually recording metrics properly to prevent a regression?

**Comment by robobario** [comment]
> > I also removed pre-registration of the summary, this is because the summary is broken down by apiKey and apiVersion, we would have to pre-register the ~250 combinations to pre-register all possibilities.

I guess it's hard to anticipate what would be alerted on but requestSize per api/version seems unlikely.

**Comment by robobario** [comment]
> I wonder if we should continue to preregister but be restrictive on the set of apikeys that we record this metric for. After all, I think the usual use-case for this stat will be produce and fetch, so perhaps by default we should restrict this metric to those keys. Configuration could allow a user to configure the set. WDYT?

Sounds good to me, maybe for this PR we could start with those two hardcoded and make it configurable in a later PR

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java (hunk 1 above)
Comment (k-wall) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java:28]: Any thoughts on the naming?

**Review by SamBarker — APPROVED** [review]
LGTM

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java (hunk 1 above)
Comment (SamBarker) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/util/Metrics.java:28]: `rpc_payload_size` is definitely better, but I wonder if the `rpc_` prefix is redundant? Maybe just plain `payload_size`. 

Note: If we are renaming this we should note it as a breaking change in the public API in the release notes (I don't think we need to do more than that at this stage)

**Comment by SamBarker** [comment]
> > I wonder if we should continue to preregister but be restrictive on the set of apikeys that we record this metric for. After all, I think the usual use-case for this stat will be produce and fetch, so perhaps by default we should restrict this metric to those keys. Configuration could allow a user to configure the set. WDYT?
> 
> Sounds good to me, maybe for this PR we could start with those two hardcoded and make it configurable in a later PR.
> 
> Also I wonder if we should make the granularity configurable, like only go down to api key by default but allow going to apiVersion granularity based on configuration.

That works for me as a strategy for progress. I think we might want to make things fairly configurable by allowing various levels of granularity for each API key. I think working out how to express that requires an effort on its own.
