### PR TITLE
Fix for #3035 and new ITs demonstrating the virtual cluster/sasl inspection subject builder working end-to-end

### LINKED ISSUE #3035: Config parsing error if SaslInspector with subject builder
For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**

I'm trying to configure the SaslInspector with a subject builder.   The following valid configuration [example-proxy-config.yaml](https://github.com/user-attachments/files/24061895/example-proxy-config.yaml)  fails to parse like this:

```
2025-12-09 18:35:24 INFO  <main> io.kr.pr.StartupShutdownLogger - Kroxylicious is starting
2025-12-09 18:35:25 INFO  <main> io.kr.pr.KafkaProxy - Binding management endpoint: 0.0.0.0:9190
2025-12-09 18:35:25 INFO  <main> io.kr.pr.StartupShutdownLogger - Shutting down
2025-12-09 18:35:27 INFO  <main> io.kr.pr.KafkaProxy - Shut down completed.
2025-12-09 18:35:27 ERROR <main> io.kr.pr.StartupShutdownLogger - Exception on startup
io.kroxylicious.proxy.plugin.PluginConfigurationException: Exception initializing filter factory saslInspection with config Config[enabledMechanisms=null, subjectBuilder=DefaultSaslSubjectBuilderService, subjectBuilderConfig={addPrincipals=[{from=saslAuthorizedId, map=[{replaceMatch=/(.*)/$1/U}], principalFactory=io.kroxylicious.proxy.authentication.UserFactory}]}, requireAuthentication=null]: class java.util.LinkedHashMap cannot be cast to class io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config is in unnamed module of loader 'app')
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory$Wrapper.<init>(FilterChainFactory.java:55)
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory.<init>(FilterChainFactory.java:119)
	at io.kroxylicious.proxy.KafkaProxy.startup(KafkaProxy.java:200)
	at io.kroxylicious.app.Kroxylicious.call(Kroxylicious.java:78)
	at io.kroxylicious.app.Kroxylicious.call(Kroxylicious.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.kroxylicious.app.Kroxylicious.main(Kroxylicious.java:128)
Caused by: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config is in unnamed module of loader 'app')
	at io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService.initialize(DefaultSaslSubjectBuilderService.java:26)
	at io.kroxylicious.filters.sasl.inspection.SaslInspection.buildSubjectBuilder(SaslInspection.java:76)
	at io.kroxylicious.filters.sasl.inspection.SaslInspection.initialize(SaslInspection.java:60)
	at io.kroxylicious.filters.sasl.inspection.SaslInspection.initialize(SaslInspection.java:40)
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory$Wrapper.<init>(FilterChainFactory.java:51)
	... 13 more
io.kroxylicious.proxy.plugin.PluginConfigurationException: Exception initializing filter factory saslInspection with config Config[enabledMechanisms=null, subjectBuilder=DefaultSaslSubjectBuilderService, subjectBuilderConfig={addPrincipals=[{from=saslAuthorizedId, map=[{replaceMatch=/(.*)/$1/U}], principalFactory=io.kroxylicious.proxy.authentication.UserFactory}]}, requireAuthentication=null]: class java.util.LinkedHashMap cannot be cast to class io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config is in unnamed module of loader 'app')
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory$Wrapper.<init>(FilterChainFactory.java:55)
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory.<init>(FilterChainFactory.java:119)
	at io.kroxylicious.proxy.KafkaProxy.startup(KafkaProxy.java:200)
	at io.kroxylicious.app.Kroxylicious.call(Kroxylicious.java:78)
	at io.kroxylicious.app.Kroxylicious.call(Kroxylicious.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.kroxylicious.app.Kroxylicious.main(Kroxylicious.java:128)
Caused by: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService$Config is in unnamed module of loader 'app')
	at io.kroxylicious.proxy.internal.subject.DefaultSaslSubjectBuilderService.initialize(DefaultSaslSubjectBuilderService.java:26)
	at io.kroxylicious.filters.sasl.inspection.SaslInspection.buildSubjectBuilder(SaslInspection.java:76)
	at io.kroxylicious.filters.sasl.inspection.SaslInspection.initialize(SaslInspection.java:60)
	at io.kroxylicious.filters.sasl.inspection.SaslInspection.initialize(SaslInspection.java:40)
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory$Wrapper.<init>(FilterChainFactory.java:51)
	... 13 more

Process finished with exit code 1
```

**To Reproduce**
1. Bring up an instance of Kroxylicious with the configuration supplied above.
2. See error

**Expected behavior**
Kroxylicioius should come up.
\
**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Fixes #3035 - missing configuration annotations meant that the subject builders could not be applied to SaslInspectors

Also added some subject builder IT tests that verify that expected subject is observed by the filter.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [x] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [x] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/SaslInspectionIT.java [hunk 1]
```diff
@@ -255,9 +278,49 @@ void shouldNotConnectWhenClientNotConfiguredForSasl(@SaslMechanism(value = "PLAI
         }
     }
 
+    @Test
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/SaslInspectionIT.java:287]: This verifies that filters actually see the default subject provided by the SaslInspection filter.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/SaslInspectionIT.java [hunk 2]
```diff
@@ -255,9 +278,49 @@ void shouldNotConnectWhenClientNotConfiguredForSasl(@SaslMechanism(value = "PLAI
...
+
+        assertClientsCanAccessCluster(cluster, topic, mechanism, null, 2, clientLoginModule, username, password, headers -> {
+            HeadersAssert.assertThat(headers)
+                    .singleHeaderWithKey(ClientAuthAwareLawyerFilter.HEADER_KEY_AUTHENTICATED_SUBJECT)
+                    .hasValueEqualTo("Subject[principals=[User[name=%s]]]".formatted(username));
+        });
+    }
+
+    @Test
+    void shouldProvideSubjectContainingMappedPrincipal(@SaslMechanism(value = "SCRAM-SHA-256", principals = {
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/SaslInspectionIT.java:311]: This verifies that filters actually see the a subject containing the mapped principal when the subject builder is so configured.

**Comment by robobario** [comment]
Have put up a PR containing [unit tests for deserialization](https://github.com/k-wall/kroxylicious/pull/120), figure it's good to establish some unit tests within the module for config deserialization.
