### PR TITLE
Fix ImmutableEnumChecker violations in runtime and krpc plugin

### LINKED ISSUE #3634: Fix ErrorProne `ImmutableEnumChecker` warnings
See https://errorprone.info/bugpattern/ImmutableEnumChecker

### PR DESCRIPTION
**Pull request by ZhangDT-sky**
### Type of change

- Refactoring

### Description

This PR fixes `ImmutableEnumChecker` findings by removing mutable/non-immutable references from enum fields:

- `RequestHeaderTagger.Tag` no longer stores a `RawTaggedField` instance directly; it now stores immutable tag metadata and constructs tagged fields as needed.
- `EntityType` no longer stores `FieldType` instances directly; it now stores the canonical base type name (`String`).

### Additional Context

`ImmutableEnumChecker` is now enforced as `ERROR`, so these enum patterns must be fixed to keep builds green and avoid future regressions.

### Checklist

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

Closes #3634

### CODE REVIEW

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/RequestHeaderTagger.java [hunk 1]
```diff
@@ -20,33 +20,42 @@
...
+
+        private boolean matches(RawTaggedField rawTaggedField) {
+            return rawTaggedField.tag() == tagId && tagData.equals(new String(rawTaggedField.data(), StandardCharsets.UTF_8));
         }
 
         @VisibleForTesting
         RawTaggedField getRawTaggedField() {
-            return rawTaggedField;
+            return rawTaggedField();
         }
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/RequestHeaderTagger.java]: I wonder if we could avoid the repeated constructions of Strings and RawTaggedField by removing all the logic from the enum and adding a private static RawTaggedField to `RequestHeaderTagger`. In the methods like `removeTags` we switch on the tag.

**Review by robobario — COMMENTED** [review]
Thanks @ZhangDT-sky just that one nitpick then it looks good to go

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/RequestHeaderTagger.java (hunk 1 above)
Comment (ZhangDT-sky) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/util/RequestHeaderTagger.java]: OK！

**Review by robobario — APPROVED** [review]
LGTM
