### PR TITLE
fix: reduce cognitive complexity of ServiceBasedPluginFactoryRegistry#loadProviders (S3776)

### LINKED ISSUE #3618: Reduce cognitive complexity of ServiceBasedPluginFactoryRegistry#loadProviders
Sonar [is flagging](https://sonarcloud.io/project/issues?impactSeverities=HIGH&issueStatuses=OPEN&id=kroxylicious_kroxylicious&open=AZugkvY9DElGv21ItZiD) the [loadProviders method of io.kroxylicious.proxy.config.ServiceBasedPluginFactoryRegistry](https://github.com/kroxylicious/kroxylicious/blob/1fb389beaa269ff1e44625aac05022ff6cc12ad8/kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/ServiceBasedPluginFactoryRegistry.java#L53) for having too high cognitive complexity.

The cognitive complexity is a measure of how many branches are possible within the method. A large method with deeply nested if statements and complex boolean logic will be harder for a human to read and reason about, especially if the method exits from numerous branches.

The aim is to reduce the amount of branching using strategies like decomposing the logic into smaller methods.

### PR DESCRIPTION
**Pull request by msalinas-se**
## Summary

Reduces the cognitive complexity of `loadProviders` by replacing the `if (LOGGER.isWarnEnabled())` guard + `for` loop with a single `forEach` call.

## Why

`LOGGER.atWarn()` (used inside `handleAmbiguousEntry`) is already lazy — it evaluates the log level internally before building the message. The `isWarnEnabled()` guard is therefore redundant and adds unnecessary nesting.

Removing the guard also fixes a subtle correctness issue: `handleAmbiguousEntry` can throw a `RuntimeException` on deprecated name collisions, but the old guard meant that exception would be silently suppressed whenever warn logging was disabled.

## Change

```java
// Before
if (LOGGER.isWarnEnabled()) {
    for (Map.Entry<String, Set<ProviderAndConfigType>> ambiguousEntry : ambiguousEntries) {
        handleAmbiguousEntry(ambiguousEntry, pluginInterface);
    }
}

// After
ambiguousEntries.forEach(ambiguousEntry -> handleAmbiguousEntry(ambiguousEntry, pluginInterface));
```

Closes #3618

### CODE REVIEW

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/ServiceBasedPluginFactoryRegistry.java [hunk 1]
```diff
@@ -60,11 +60,7 @@ private static Map<String, ProviderAndConfigType> loadProviders(Class<?> pluginI
                 Collectors.partitioningBy(e -> e.getValue().size() == 1));
         var ambiguousEntries = partitioned.get(false);
         var unambiguousEntries = partitioned.get(true);
-        if (LOGGER.isWarnEnabled()) {
-            for (Map.Entry<String, Set<ProviderAndConfigType>> ambiguousEntry : ambiguousEntries) {
-                handleAmbiguousEntry(ambiguousEntry, pluginInterface);
-            }
-        }
+        ambiguousEntries.forEach(ambiguousEntry -> handleAmbiguousEntry(ambiguousEntry, pluginInterface));
```
Comment (SamBarker) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/ServiceBasedPluginFactoryRegistry.java]: The problem with this change is that it's performing a comparatively expensive operation to build the log message even if the logger is disabled. 

Now how often warn is disabled and how performance sensitive this code path at both open questions we should think about.

**Review by SamBarker — COMMENTED** [review]
Thanks for the pr @msalinas-se it's not quite the obvious change it appears to be at first.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/ServiceBasedPluginFactoryRegistry.java (hunk 1 above)
Comment (msalinas-se) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/ServiceBasedPluginFactoryRegistry.java]: Thanks for catching that @SamBarker, you're right, I missed that the addKeyValue() arguments are evaluated eagerly, including the Collectors.joining() in the else branch. Removed my previous change and kept the isWarnEnabled() guard. Replaced the for loop with forEach to still reduce the cognitive complexity nesting without the performance regression.

**Review by robobario — APPROVED** [review]
LGTM, thank you @msalinas-se!
