### PR TITLE
fix: sendRequest and short-circuit response do not compose

### LINKED ISSUE #2584: sendRequest and short circuit response Filters do not compose nicely
bit of a bug here, short circuit responses do not play nicely with `sendRequest`.

If a filter uses `sendRequest` and an upstream filter short circuits, then we do not shuffle over the internal frame context like recipient/promise etc, so the caller's promise is not completed when the message gets back to the originator.

_Originally posted by @robobario in https://github.com/kroxylicious/kroxylicious/pull/2583#discussion_r2278245345_

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Transfers the promise and recipient internal fields when a Filter generates a short-circuit response to an out-of-band request initiated by a downstream filter.

Previously, the internal fields were not transferred, breaking the internal request mechanism as the promise was lost forever. It caused the connection to hang and never respond to the client.

Fixes #2584

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/OutOfBandRequestIT.java [hunk 1]
```diff
@@ -71,6 +74,24 @@ void testOutOfBandMessageInterceptedByUpstreamFilters() {
         }
     }
 
+    @Test
+    void testOutOfBandMessageComposesWithErrorResponse() {
+        // this filter should not intercept the out-of-band request or response, it will not either message with its name
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/OutOfBandRequestIT.java]: last part of the comment doesn't read properly.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/OutOfBandRequestIT.java [hunk 2]
```diff
@@ -71,6 +74,24 @@ void testOutOfBandMessageInterceptedByUpstreamFilters() {
         }
     }
 
+    @Test
+    void testOutOfBandMessageComposesWithErrorResponse() {
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/OutOfBandRequestIT.java]: I'm not sure if the ComposesWith part of. the method helps understandability.  `testOutOfBandMessageWithErrorResponse` is better for me, or maybe, a-la @SamBarker, `shouldTolerateOutOfBandMessageWithErrorResponse`

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/frame/DecodedRequestFrame.java [hunk 3]
```diff
@@ -48,4 +49,8 @@ private boolean isZeroAcksProduceRequest() {
         return apiKeyId() == PRODUCE.id && ((ProduceRequestData) body).acks() == 0;
     }
 
+    public DecodedResponseFrame<?> responseFrame(ResponseHeaderData header, ApiMessage message) {
+        return new DecodedResponseFrame<>(apiVersion(), correlationId(), header, message);
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/frame/DecodedRequestFrame.java]: consider failing if `apiKey() != message.apiKey()`.  

essentially I am suggesting pushing code like this into DecodedRequestFrame
```
            if (message.apiKey() != decodedFrame.apiKeyId()) {
                throw new AssertionError(
                        "Filter '" + filterDescriptor() + "': Attempt to respond with ApiMessage of type " + ApiKeys.forId(message.apiKey()) + " but request is of type "
                                + decodedFrame.apiKey());
            }
```

Maybe add a unit test for DecodedRequestFrame

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/InternalRequestFrame.java [hunk 4]
```diff
@@ -38,4 +40,9 @@ public Filter recipient() {
     public CompletableFuture<?> promise() {
         return promise;
     }
+
+    @Override
+    public DecodedResponseFrame<?> responseFrame(ResponseHeaderData header, ApiMessage message) {
+        return new InternalResponseFrame<>(recipient, apiVersion, correlationId, header, message, promise);
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/InternalRequestFrame.java:46]: ditto - consider failing if apiKey() != message.apiKey(). Maybe add a unit test for InternalRequestFrame

**Comment by k-wall** [comment]
nice work, I like your solution to the problem.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/InternalRequestFrame.java (hunk 4 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/InternalRequestFrame.java:46]: done, reworked it so that that assertion is solely contained in `DecodedRequestFrame` and then it calls a protected method to create the frame.
