### PR TITLE
bugfix: operator do not emit empty downstream trust object

### LINKED ISSUE #2176: Operator: downstream-tls example not starting
**Describe the bug**
On main if I run:

```
export QUAY_ORG=myorghere
./scripts/build-operator.sh
./scripts/run-operator.sh
```

and then execute the instructions in `kroxylicious-operator/examples/downstream-tls/README.md` to install certmanager and the proxy configuration, the proxy pod fails to start with exception:

```
2025-05-13 01:25:48 <main> ERROR io.kroxylicious.proxy.StartupShutdownLogger - Exception on startup
java.lang.IllegalArgumentException: Couldn't parse configuration
	at io.kroxylicious.proxy.config.ConfigParser.parseConfiguration(ConfigParser.java:74) ~[kroxylicious-runtime-0.13.0-SNAPSHOT.jar:?]
	...
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class io.kroxylicious.proxy.config.tls.TrustProvider]: Cannot deduce unique subtype of `io.kroxylicious.proxy.config.tls.TrustProvider` (2 candidates match)
 at [Source: (sun.nio.ch.ChannelInputStream); line: 22, column: 16] (through reference chain: io.kroxylicious.proxy.config.Configuration["virtualClusters"]->java.util.ArrayList[0]->io.kroxylicious.proxy.config.VirtualCluster["gateways"]->java.util.ArrayList[0]->io.kroxylicious.proxy.config.VirtualClusterGateway["tls"]->io.kroxylicious.proxy.config.tls.Tls["trust"])
```

the proxy config contains:

```
  data:
    proxy-config.yaml: |-
      ---
      ...
      - name: "my-cluster"
        ...
        gateways:
        - name: "default"
          ...
          tls:
            key:
              privateKeyFile: "/opt/kroxylicious/virtual-cluster/server-certs/server-certificate/tls.key"
              certificateFile: "/opt/kroxylicious/virtual-cluster/server-certs/server-certificate/tls.crt"
            trust: {}
```

I don't think our jackson config can handle the `trust: {}` which is the serialized output of `PlatformTrustProvider`, which cannot be deserialized using Deduction.

**Expected behavior**

If I configure a VKC/Ingress with downstream TLS server certs, but no client trust, then the proxy is configured appropriately and starts up.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Fixes #2176

If you supply downstream TLS server certs but no trust, the operator was manifesting it as an empty object in the configuration YAML. This cannot be decoded using jackson deduction. For now lets change it to not set trust if it isn't supplied and we can improved the configuration API separately.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/DerivedResourcesTest.java [hunk 1]
```diff
@@ -244,6 +248,11 @@ private static List<DynamicTest> testsForDir(List<DesiredFn<KafkaProxy, ?>> depe
                                 assertThat(Files.exists(expectedFile)).describedAs(expectedFile + " does not exist").isTrue();
                                 var expected = loadExpected(expectedFile, resourceType);
                                 assertSameYaml(actualResource, expected);
+                                if (actualResource instanceof ConfigMap cm && cm.getData().containsKey("proxy-config.yaml")) {
```
Comment (robobario) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/DerivedResourcesTest.java:251]: a bit crusty to sniff for this config map entry, but it feels like a good place to check we are emitting something parseable

**Review by tombentley — APPROVED** [review]
