### PR TITLE
Envelope encryption preserve batches within MemoryRecords

### LINKED ISSUE #855: Envelope encryption doesn't preserve MemoryRecord batches
**Describe the bug**
Currently the envelope encryption Filter flattens multiple batches within a MemoryRecords like [this](https://github.com/kroxylicious/kroxylicious/blob/db1282ffd78687d59e5ab18cc0521f41cce9b114/kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilter.java#L154) and then uses the metadata from the first batch when constructing the memory records [here](https://github.com/kroxylicious/kroxylicious/blob/db1282ffd78687d59e5ab18cc0521f41cce9b114/kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilter.java#L184).

If a [Control Batch](https://kafka.apache.org/documentation/#controlbatch) is present in the proxied brokers FetchResponse and is not the first batch in the MemoryRecords, it will be filtered out and no control batch will reach the client. These batches are `used by consumers to filter out aborted transactional messages.`, so we need to pass these on.

**Expected behavior**
Batches in the MemoryRecords are preserved including these semantically important single-message control batches.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Closes #855

With these changes:
1. We preserve the batching of the input MemoryRecords in the encryption filter on the encrypt and decrypt path.
2. Each batch's metadata is preserved. Each batch contains the same records (though they may be transformed).
3. Control batches are not encrypted, but passed through unmodified.
4. We introduce integration tests checking transactional semantics (previously failing due to the control record being exposed to the client as a normal record)
5. Batches with 0 records (due to log compaction) are passed through unmodified, preserving their metadata

### Why?

The encryption filter was not preserving batches within the MemoryRecords it is transforming for a given topic-partition. Consequently we could have done things like:
1. Removing control batches. We created a single batch with metadata matching the first one in the input and then effectively flatmapped all the batches into it. Meaning that on a transaction commit the user would receive the original record and the control record, where the control record would normally be filtered out by the client and not exposed to `poll()`.
2. If the control batch was the first batch, we could roll multiple records into a control batch when it's expected to have a single records.
3. The user may have some reason for compressing batches with different algorithms, we were discarding this and using a single compression scheme.

Generally we want to transparently behave the same as Kafka would, just with our bit of encrypting/decryption transform happening.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/InBandKeyManager.java [hunk 1]
```diff
@@ -117,6 +124,26 @@ private CompletableFuture<KeyContext> makeKeyContext(@NonNull K kekId) {
                 }).toCompletableFuture();
     }
 
+    record BatchDescription(int index, MutableRecordBatch batch, int recordCount) {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/InBandKeyManager.java:127]: this can be removed, all we needed in the end was a recordCount per batch

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/InBandKeyManager.java [hunk 2]
```diff
@@ -170,61 +221,76 @@ private ByteBufferOutputStream allocateBufferForEncode(MemoryRecords records, In
...
+                                kafkaRecord))
+                        .filter(value -> value > 0)
+                        .max()
+                        .orElseThrow();
+                var maxWrapperSize = records.stream()
+                        .mapToInt(kafkaRecord -> sizeOfWrapper(keyContext, maxParcelSize))
+                        .filter(value -> value > 0)
+                        .max()
+                        .orElseThrow();
+                ByteBuffer parcelBuffer = bufferPool.acquire(maxParcelSize);
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/InBandKeyManager.java:278]: buffers are acquired per batch, so there's now more acquires on encrypt

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java [hunk 3]
```diff
@@ -144,6 +145,21 @@ public BatchAwareMemoryRecordsBuilder addBatch(CompressionType compressionType,
                 templateBatch.deleteHorizonMs().orElse(RecordBatch.NO_TIMESTAMP));
     }
 
+    /**
+     * Directly appends a batch, intended to be used for passing through unmodified batches. Writes
+     * the previous batch to the stream if required
+     * @param templateBatch The batch to use as a source of batch parameters
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java:151]: copyPaste gone wrong, it's not a template, we write it directly

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java [hunk 4]
```diff
@@ -144,6 +145,21 @@ public BatchAwareMemoryRecordsBuilder addBatch(CompressionType compressionType,
...
+     * @return this builder
+     */
+    public @NonNull BatchAwareMemoryRecordsBuilder writeBatch(MutableRecordBatch templateBatch) {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java:154]: needs unit tests

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java [hunk 5]
```diff
@@ -144,6 +145,21 @@ public BatchAwareMemoryRecordsBuilder addBatch(CompressionType compressionType,
...
+        if (haveBatch()) {
+            appendCurrentBatch();
+        }
+        templateBatch.writeTo(buffer);
+        builder = null;
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java:159]: should add a comment here, I did this to ensure the buffer was flipped at the end if this is the last batch added.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/InBandKeyManager.java [hunk 6]
```diff
@@ -346,52 +391,78 @@ public CompletionStage<MemoryRecords> decrypt(@NonNull String topicName, int par
...
             return CompletableFuture.completedFuture(records);
         }
-        ByteBufferOutputStream buffer = allocateBufferForDecode(records, bufferAllocator);
-        MemoryRecordsBuilder outputBuilder = recordsBuilder(buffer, records);
-        return decrypt(topicName, partition, recordStream(records).toList(), (kafkaRecord, plaintextBuffer, headers) -> {
-            outputBuilder.appendWithOffset(kafkaRecord.offset(), kafkaRecord.timestamp(), kafkaRecord.key(), plaintextBuffer, headers);
-        }).thenApply(unused -> outputBuilder.build());
+        Set<E> uniqueEdeks = extractEdeks(topicName, partition, records);
+        CompletionStage<Map<E, AesGcmEncryptor>> decryptors = resolveAll(uniqueEdeks);
+        CompletionStage<BatchAwareMemoryRecordsBuilder> objectCompletionStage = decryptors.thenApply(
```
Comment (tombentley) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/InBandKeyManager.java:402]: Can we find a better name than `objectCompletionStage`

**Review by tombentley — APPROVED** [review]

File: kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/record/RecordTestUtils.java [hunk 7]
```diff
@@ -343,7 +343,12 @@ public static MemoryRecords memoryRecords(@NonNull List<Record> records) {
      * @see <a href="https://kafka.apache.org/documentation/#recordbatch">Apache Kafka RecordBatch documentation</a>
      */
     public static MemoryRecords memoryRecordsWithAllRecordsRemoved() {
-        try (MemoryRecordsBuilder memoryRecordsBuilder = defaultMemoryRecordsBuilder(DEFAULT_MAGIC_VALUE)) {
+        return memoryRecordsWithAllRecordsRemoved(0L);
+    }
+
+    @NonNull
+    public static MemoryRecords memoryRecordsWithAllRecordsRemoved(long baseOffset) {
```
Comment (k-wall) [inline kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/record/RecordTestUtils.java:350]: Javadoc

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java [hunk 8]
```diff
@@ -144,6 +145,21 @@ public BatchAwareMemoryRecordsBuilder addBatch(CompressionType compressionType,
                 templateBatch.deleteHorizonMs().orElse(RecordBatch.NO_TIMESTAMP));
     }
 
+    /**
+     * Directly appends a batch, intended to be used for passing through unmodified batches. Writes
+     * the previous batch to the stream if required
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java:150]: Should the javadoc say the batch will be closed too?

Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java:150]: which batch? the previous batch?

**Comment by robobario** [comment]
Planning to make the tests more exhaustive to check that every one of the batch metadata properties is covered.

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/inband/InBandKeyManagerTest.java [hunk 9]
```diff
@@ -105,6 +114,229 @@ void shouldEncryptRecordValue() {
                 .isEqualTo(value);
     }
 
+    @Test
+    void shouldPreserveMultipleBatches() {
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/inband/InBandKeyManagerTest.java:118]: this is quite hard to digest, can we refactor to make it more readily understandable?

Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/inband/InBandKeyManagerTest.java:118]: will do, I'll see if I can pull apart the encrypt/decrypt side

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 10]
```diff
@@ -81,6 +82,34 @@ void roundTripSingleRecord(KafkaCluster cluster, Topic topic, TestKmsFacade<?, ?
         }
     }
 
+    @TestTemplate
+    void roundTripTransactional(KafkaCluster cluster, Topic topic, TestKmsFacade<?, ?, ?> testKmsFacade) throws Exception {
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:86]: good test

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 11]
```diff
@@ -81,6 +82,34 @@ void roundTripSingleRecord(KafkaCluster cluster, Topic topic, TestKmsFacade<?, ?
...
+            producer.commitTransaction();
+            consumer.subscribe(List.of(topic.name()));
+            var records = consumer.poll(Duration.ofSeconds(2));
+            assertThat(records.iterator())
+                    .toIterable()
+                    .singleElement()
+                    .extracting(ConsumerRecord::value)
+                    .isEqualTo(HELLO_WORLD);
+        }
+    }
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:111]: we should probably have a test(s)

1. that ensures isolation is respected (send a second message without commiting and ensure that it is invisible).
2. transaction semantics are respected in the event of rollback.

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/inband/InBandKeyManagerTest.java [hunk 12]
```diff
@@ -105,6 +114,229 @@ void shouldEncryptRecordValue() {
...
+        MutableRecordBatch secondDecrypted = decryptedBatches.get(1);
+        assertThat(secondDecrypted.compressionType()).isEqualTo(emptyBatch.compressionType());
+        assertThat(secondDecrypted.timestampType()).isEqualTo(emptyBatch.timestampType());
+        assertThat(secondDecrypted.baseOffset()).isEqualTo(emptyBatch.baseOffset());
+    }
+
+    private static RecordBatch controlBatch(int baseOffset, byte[] arbitraryValue) {
+        MemoryRecordsBuilder builder = new MemoryRecordsBuilder(ByteBuffer.allocate(1000), RecordBatch.CURRENT_MAGIC_VALUE, CompressionType.NONE,
+                TimestampType.CREATE_TIME, baseOffset, 1L, 1L, (short) 1, 1, false, true, 1, 1);
+        byte[] key = { 0, 0, (byte) ControlRecordType.ABORT.type(), (byte) (ControlRecordType.ABORT.type() >> 8) };
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/inband/InBandKeyManagerTest.java:334]: I didn't spot the method to do this but it's bound to be in the kafka-clients API, we need a key with a specific schema.

File: kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/assertj/RecordBatchAssert.java [hunk 13]
```diff
@@ -64,6 +66,101 @@ public RecordBatchAssert hasNumRecords(int expected) {
         return this;
     }
 
+    public RecordBatchAssert hasMagic(byte magic) {
+        Assertions.assertThat(actual.magic())
```
Comment (k-wall) [inline kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/assertj/RecordBatchAssert.java:70]:
```suggestion
        isNotNull();
        Assertions.assertThat(actual.magic())
```

File: kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/record/RecordTestUtils.java [hunk 14]
```diff
@@ -226,24 +227,70 @@ public static Record record(byte magic,
         return MemoryRecords.readableRecords(mr.buffer()).records().iterator().next();
     }
 
+    /**
+     * Return a singleton RecordBatch containing a single Record with the given key, value and headers.
+     * The batch will use the current magic. The baseOffset and offset of the record will be 0
+     * @see RecordTestUtils#recordBatch(long, String, String, Header[])
+     */
+    public static MutableRecordBatch recordBatch(String key,
```
Comment (k-wall) [inline kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/record/RecordTestUtils.java:235]: could we give this method a name which describes the fact that the batch contains a single record?

File: kroxylicious-filter-test-support/src/test/java/io/kroxylicious/test/assertj/KafkaAssertionsTest.java [hunk 15]
```diff
@@ -61,14 +65,21 @@ void testRecord() {
 
         // value
         recordAssert.hasValueEqualTo("VALUE");
+        recordAssert.hasValueEqualTo("VALUE".getBytes(StandardCharsets.UTF_8));
+        recordAssert.hasValueEqualTo(RecordTestUtils.record("KEy", "VALUE"));
+        recordAssert.hasValueNotEqualTo("NOT_VALUE");
         Assertions.assertThatThrownBy(() -> recordAssert.hasValueEqualTo("NOT_VALUE")).hasMessageContaining("[record value]");
+        Assertions.assertThatThrownBy(() -> recordAssert.hasValueEqualTo("NOT_VALUE".getBytes(StandardCharsets.UTF_8))).hasMessageContaining("[record value]");
```
Comment (k-wall) [inline kroxylicious-filter-test-support/src/test/java/io/kroxylicious/test/assertj/KafkaAssertionsTest.java:72]:
```suggestion
        Assertions.assertThatThrownBy(() -> recordAssert.hasValueEqualTo("NOT_VALUE".getBytes(StandardCharsets.UTF_8))).isInstanceOf(AssertionError.class).hasMessageContaining("[record value]");
```

File: kroxylicious-filter-test-support/src/test/java/io/kroxylicious/test/assertj/KafkaAssertionsTest.java [hunk 16]
```diff
@@ -61,14 +65,21 @@ void testRecord() {
 
         // value
         recordAssert.hasValueEqualTo("VALUE");
+        recordAssert.hasValueEqualTo("VALUE".getBytes(StandardCharsets.UTF_8));
```
Comment (k-wall) [inline kroxylicious-filter-test-support/src/test/java/io/kroxylicious/test/assertj/KafkaAssertionsTest.java:68]: I'd suggest dividing testRecord up into smaller tests, each focus on a single concern: key equality, value equality etc.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java [hunk 17]
```diff
@@ -245,13 +276,16 @@ public BatchAwareMemoryRecordsBuilder appendWithOffset(long offset, Record recor
      * @return the memory records
      */
     public @NonNull MemoryRecords build() {
-        boolean needsFlip = builder == null || !builder.isClosed();
-        maybeAppendCurrentBatch();
-        ByteBuffer buf = this.buffer.buffer();
-        if (needsFlip) {
+        if (closed) {
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java:279]: restructure to have a single return statement

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 18]
```diff
@@ -81,6 +83,113 @@ void roundTripSingleRecord(KafkaCluster cluster, Topic topic, TestKmsFacade<?, ?
...
+            assertThat(records.iterator())
+                    .isExhausted();
+        }
+    }
+
+    interface ExceptionalConsumer<T> {
+        void accept(T t) throws Exception;
+    }
+
+    <K, V> Producer<K, V> withTransaction(Producer<K, V> producer, ExceptionalConsumer<Producer<K, V>> consumer) {
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:182]: AssertJ has a nice ThrowingConsumer for this use-case

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 19]
```diff
@@ -81,6 +83,113 @@ void roundTripSingleRecord(KafkaCluster cluster, Topic topic, TestKmsFacade<?, ?
...
+        producer.beginTransaction();
+        try {
+            consumer.accept(producer);
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:185]: seeing `consumer` in this context shocks my brain because of the collision with KafkaConsumer. Rename var to `action`.

**Review by k-wall — APPROVED** [review]

File: kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/assertj/RecordBatchAssert.java (hunk 13 above)
Comment (robobario) [reply kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/assertj/RecordBatchAssert.java:70]: most of the values are primitives, I'll put null checks on the enums

Comment (robobario) [reply kroxylicious-filter-test-support/src/main/java/io/kroxylicious/test/assertj/RecordBatchAssert.java:70]: ah sorry I misread, that's checking the current thing is not null as a precondition. will add.
