### PR TITLE
bugfix: bootstrapServers containing whitespace parsed unexpectedly

### LINKED ISSUE #3535: Trim IP Addresses in bootstrapServers
**Bug Description**
When using multiple IP addresses in virtual cluster bootstrap server (comma separated), if there are spaces between each entry, it is interpreted as domain name and kroxylicious is trying to resolve it. 

**To Reproduce**
1. Configure kroxylicious like this ...
```yaml
virtualClusters:
- name: plaintext
   targetCluster:
   bootstrapServers: "192.168.0.1:9092, 192.168.0.2:9092, 192.168.0.3:9092"
```
2. Run kroxylicious, and allow some traffic to pass.
4. See error:
```
2026-03-13 03:25:58 <epollEventLoopGroup-5-2> WARN io.kroxylicious.proxy.internal.ProxyChannelStateMachine - Exception from the server channel: 192.168.0.2: Name or service not known. Increase log level to DEBUG for stacktrace
2026-03-13 03:25:58 <epollEventLoopGroup-5-3> WARN io.kroxylicious.proxy.internal.ProxyChannelStateMachine - Exception from the server channel: 192.168.0.3: Name or service not known. Increase log level to DEBUG for stacktrace
```
**Expected Behavior**
If there are spaces between each IP address entry, it should be trimmed, then parsed as IP address instead of domain name.

**Additional context**
Using kroxylicious version 0.15.0

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Tolerate whitespace in target bootstrapServers by stripping whitespace out of the string early.

The problem from the issue was ip addresses being interpreted as hostnames:
> When using multiple IP addresses in virtual cluster bootstrap server (comma separated),
> if there are spaces between each entry, it is interpreted as domain name and kroxylicious is trying to resolve it.

In apache kafka the equivalent property is trimmed and whitespace either side of the comma is stripped away. We have chosen to use CSV to follow the familiar pattern, so I think we should adopt the upstream tolerance for intervening whitespace.

Fixes #3535

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java [hunk 1]
```diff
@@ -56,7 +56,8 @@ public String bootstrapServers() {
     }
 
     public List<HostPort> bootstrapServersList() {
-        return Arrays.stream(bootstrapServers.split(",")).map(HostPort::parse).toList();
+        String trimmed = bootstrapServers.trim();
+        return Arrays.stream(trimmed.split("\\s*,\\s*")).map(HostPort::parse).toList();
```
Comment (robobario) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: not really any worse than before but we could refactor this, if TargetCluster wasn't a record we could do it in the constructor and save string wrangling on each connection. Lets leave it out of this PR though.

Comment (SamBarker) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: I'm not following you, we already have a compact ctor in `TargetCluster` where already validate its not null, and can apply the trim

i.e.
`bootstrapServers = bootstrapServers.replaceAll("\\s", ""); `

Comment (SamBarker) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: Should we maybe add a trim as part of `HostPort::parse` as well?

Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: I mean the split and HostPort building could be done once

Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: ah sorry I see what you mean, rip all the whitespace out early

Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: mm any odd cases where we want whitespace in a host? I'd imagine not

Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: I've pushed up your approach

Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java]: yeah I think that's a good idea to prevent heartache in future

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java [hunk 2]
```diff
@@ -38,6 +38,7 @@ public record TargetCluster(@JsonProperty(value = "bootstrapServers", required =
         if (bootstrapServers == null) {
             throw new IllegalArgumentException("'bootstrapServers' is required in a target cluster.");
         }
+        bootstrapServers = bootstrapServers.replaceAll("\\s", "");
```
Comment (SamBarker) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java:41]: Could use 
```suggestion
        bootstrapServers = Object.requireNotNull(bootstrapServers, "'bootstrapServers' is required in a target cluster.").replaceAll("\\s", "");
```

and drop the if guard, but not sure thats a readability win.

**Review by SamBarker — APPROVED** [review]
LGTM

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/FilterIT.java [hunk 3]
```diff
@@ -431,6 +434,28 @@ void shouldPassThroughRecordUnchanged(KafkaCluster cluster, Topic topic) throws
...
 
+    @Test
+    void bootstrapServersToleratesWhitespace(KafkaCluster cluster, Topic topic) throws Exception {
+        String bootstrapServers = cluster.getBootstrapServers();
+        String bootstrapServersContainingWhitespace = Arrays.stream(bootstrapServers.split(",")).collect(Collectors.joining("  ,  ", "  ", "  "));
+        ConfigurationBuilder configBuilder = KroxyliciousConfigUtils.proxy(bootstrapServersContainingWhitespace);
+        try (var tester = kroxyliciousTester(configBuilder);
+                var producer = tester.producer(Map.of(CLIENT_ID_CONFIG, "shouldPassThroughRecordUnchanged", DELIVERY_TIMEOUT_MS_CONFIG, 3_600_000));
+                var consumer = tester.consumer()) {
+            producer.send(new ProducerRecord<>(topic.name(), "my-key", "Hello, world!")).get();
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/FilterIT.java:445]: nit - we avoid `get()`s within infinite waits as that can lead to foreever hanging tests.
our favoured best practice is using AssertJ's `assertThat(producer.send(new ProducerRecord<>(topic.name(), "my-key", "Hello, world!"))).`succeedsWithin(5, TimeUnit.SECONDS);

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/FilterIT.java [hunk 4]
```diff
@@ -431,6 +434,28 @@ void shouldPassThroughRecordUnchanged(KafkaCluster cluster, Topic topic) throws
...
+            consumer.subscribe(Set.of(topic.name()));
+            var records = consumer.poll(Duration.ofSeconds(10));
+            consumer.close();
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/FilterIT.java:448]: we don't need the close, try-with-resources is good enough for this case.
