### PR TITLE
System tests: Added support to select Vault version

### LINKED ISSUE #998: Envelope Encryption / Vault system tests should use specific Vault Helm Chart version (test repeatability)
**Describe the bug**

Currently, the system tests use the **latest** Vault Helm Chart.  That means the tests aren't repeatable over time and we don't have certainty about what has actually been tested.

We need the integration test framework to use a specific version of the chart.

**Expected behavior**

I think we we should pin to https://github.com/hashicorp/vault-helm/releases/tag/v0.27.0.   

That will give use Vault 1.15, which in in synch with the Docker image used by io.kroxylicious.kms.provider.hashicorp.vault.TestVault#HASHICORP_VAULT

We should make sure that the version is overridable by a environment variable, in case we need to override it.

### PR DESCRIPTION
**Pull request by franvila**
### Type of change

- Bugfix

### Description

Added the support of being able to select the Vault version to used in the system tests. Currently we have to set the default value by hard, because we don't have a config file or so to share the value among the project.

### Additional Context

Fixes #998 

### Checklist

- [ ] Write tests
- [X] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [X] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java [hunk 1]
```diff
@@ -152,4 +162,38 @@ private String mapToValuesParameterArgument(Map<String, String> m) {
...
+     *
+     * @param chartName the chart name
+     * @param releaseVersion the release version
+     * @return the chart versions
+     */
+    public String getChartVersion(String chartName, String releaseVersion) {
+        String chartVersion = "";
+        if (releaseVersion != null && !releaseVersion.isEmpty()) {
+            LOGGER.info("Getting chart version for {}", chartName);
+            ExecResult result = Exec.exec(null, command("search", "repo",
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java:177]: `helm search repo <name> --versions` is an inexact match:

```
hashicorp/vault                 	0.6.0        	1.4.2      	Official HashiCorp Vault Chart
hashicorp/vault                 	0.5.0        	           	Install and configure Vault on Kubernetes.
hashicorp/vault                 	0.4.0        	           	Install and configure Vault on Kubernetes.
hashicorp/vault-secrets-operator	0.4.0        	0.4.0      	Official Vault Secrets Operator Chart
hashicorp/vault-secrets-operator	0.3.4        	0.3.4      	Official Vault Secrets Operator Chart
```

so you need to make sure that you process only the charts you are interested in.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java [hunk 2]
```diff
@@ -152,4 +162,38 @@ private String mapToValuesParameterArgument(Map<String, String> m) {
...
+                    chartName,
+                    "--versions",
+                    "--output=json"), 0, true);
+
+            ObjectMapper mapper = new ObjectMapper();
+            try {
+                ArrayNode rootNode = (ArrayNode) mapper.readTree(result.out());
+                // Looking for the latest version that match with releaseVersion. If set to 1.15, it will look for the latest 1.15.Z
+                for (JsonNode node : rootNode) {
+                    if (node.at("/app_version").asText().startsWith(releaseVersion)) {
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java:187]: That's not safe.  A release version of `1.1` would match 1.19!  You could parse the parts at integers and match those, or make sure a you search string end in dot.  If you do the latter, you need to be sure that the input is just `<major>.<minor>`.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java [hunk 3]
```diff
@@ -152,4 +162,38 @@ private String mapToValuesParameterArgument(Map<String, String> m) {
...
+                        chartVersion = node.at("/version").asText();
+                        break;
+                    }
+                }
+            }
+            catch (JsonProcessingException e) {
+                throw new UncheckedIOException(e);
+            }
+        }
+        return chartVersion;
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java:197]: Best abort if we don't find what we need.  Falling back to latest would mean we test against the wrong code.

**Comment by k-wall** [comment]
@franvila on reflection, I would take the simple approach.  Parsing the output from the tool seems just a bit too fragile.

Just have an environment variable that accepts the `CHART_VERSION`, which defaults to `0.27`, with a comment on it and io.kroxylicious.kms.provider.hashicorp.vault.TestVault#HASHICORP_VAULT to say that when we upgrade, we need to make sure you can the both chart version and vault version stay in sync.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java (hunk 2 above)
Comment (SamBarker) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java:187]: I agree with your motivation that we should look for the latest patch release, but as @k-wall says we need to be a bit more sophisticated about how we do it. 

An other alliterative  you could try is `releaseVersion.split(".")` and `node.at("/app_version").asText().split(".")` and compare the first two array elements to make sure you have found a match. 

That assumes you still only get one result per `major.minor` pair, if not you have to keep iterating to find the highest patch number.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java [hunk 4]
```diff
@@ -152,4 +162,38 @@ private String mapToValuesParameterArgument(Map<String, String> m) {
...
+     * @return the chart versions
+     */
+    public String getChartVersion(String chartName, String releaseVersion) {
+        String chartVersion = "";
+        if (releaseVersion != null && !releaseVersion.isEmpty()) {
+            LOGGER.info("Getting chart version for {}", chartName);
+            ExecResult result = Exec.exec(null, command("search", "repo",
+                    chartName,
+                    "--versions",
+                    "--output=json"), 0, true);
```
Comment (SamBarker) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java:180]: we should add `--fail-on-no-result`

Comment (SamBarker) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/k8s/HelmClient.java:180]: if we know the chart version we are looking for we can use `String.format("--version ^%s", chartVersion)` which should do a semver aware search see the [helm docs](https://helm.sh/docs/helm/helm_search_repo/)

**Review by SamBarker — COMMENTED** [review]
While I like the idea of depending on the vault version (as thats what we care about) and not the chart version the version selection logic just doesn't seem worth it. I agree with @k-wall lets make the env var the chart version. 

Though we should log which version of vault we are actually using.

**Comment by k-wall** [comment]
Maybe we should fail if the vault version installed by the chart does not match what we expect?  I think that'd be easier to implement and give us the assertion we need.

**Comment by franvila** [comment]
> Maybe we should fail if the vault version installed by the chart does not match what we expect? I think that'd be easier to implement and give us the assertion we need. @SamBarker WDYT?

I find a bit odd having `CHART_VERSION` that is not easy to understand why we have a different version for Vault installation for an external user perspective. But if you all agree, we can go with that solution.

How can we detect the proper vault version if we don't have any doc/file where to check it?

**Comment by k-wall** [comment]
> How can we detect the proper vault version if we don't have any doc/file where to check it?

Compare it to version number used included in:

io.kroxylicious.kms.provider.hashicorp.vault.VaultTestKmsFacade#HASHICORP_VAULT

**Comment by SamBarker** [comment]
> I find a bit odd having CHART_VERSION that is not easy to understand why we have a different version for Vault installation for an external user perspective. But if you all agree, we can go with that solution.

Two thoughts 
1. it should be `VAULT_CHART_VERSION` 
2. We are trying to balance ease of use and complexity of implementation and deterministic behaviour. Specifying the vault version directly is better for ease of use but given the helm API's we have its complicated/error prone and leaves us exposed to non deterministic behaviour. Version X of the chart supplies vault 1.15 with configuration ABC and version X+1 supplies vault 1.15 with configuration ABC' and the tests fail...

File: DEV_GUIDE.md [hunk 5]
```diff
@@ -337,6 +337,7 @@ has been applied ineffectively.
 * `SKIP_TEARDOWN`: variable for development purposes to avoid keep deploying and deleting deployments each run. Default value: `false`
 * `CONTAINER_CONFIG_PATH`: directory where `config.json` file is located. This file contains the pull secrets to be used by
 the container engine. Default value: `$HOME/.docker/config.json`
+* `VAULT_CHART_VERSION`: version of Vault to be used for Envelope Encryption. Default value: `0.27.0`
```
Comment (k-wall) [inline DEV_GUIDE.md:340]:
```suggestion
* `VAULT_CHART_VERSION`: version of Vault Helm Chart to be used by the System Tests for Envelope Encryption. Default value: `0.27.0`
```

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java [hunk 6]
```diff
@@ -126,11 +133,50 @@ protected URI getVaultUrl() {
...
+     * @return the boolean
+     */
+    public boolean isCorrectVersionInstalled() {
+        String installedVersion = getVaultVersion();
+        String expectedVersion = VaultTestKmsFacade.HASHICORP_VAULT.split(":")[1];
+
+        return compareTo(installedVersion, expectedVersion) == 0;
+    }
+
+    private int compareTo(String currentVersion, String expectedVersion) {
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java:162]: Don't use the method name compareTo, you risk confusing the reviewer.  They'll likely think `java.lang.Comparable#compareTo`

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java [hunk 7]
```diff
@@ -88,6 +89,27 @@ public boolean isAvailable() {
...
+     *
+     * @return the version
+     */
+    public String getVersionInstalled() {
+        try (var output = new ByteArrayOutputStream();
+                var exec = kubeClient().getClient().pods()
+                        .inNamespace(deploymentNamespace)
+                        .withName(VAULT_POD_NAME)
+                        .writingOutput(output)
+                        .exec("sh", "-c", VAULT_CMD + " version")) {
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java:103]: There's no need for the shell
```suggestion
                        .exec("VAULT_CMD, "version")) {
```

File: kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java [hunk 8]
```diff
@@ -36,7 +36,7 @@
 import static java.nio.charset.StandardCharsets.UTF_8;
 
 public class VaultTestKmsFacade extends AbstractVaultTestKmsFacade {
-    private static final String HASHICORP_VAULT = "hashicorp/vault:1.15";
+    public static final String HASHICORP_VAULT = "hashicorp/vault:1.15";
```
Comment (k-wall) [inline kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java:39]:
```suggestion
    public static final DockerImageName HASHICORP_VAULT = DockerImageName.parse("hashicorp/vault:1.15");
```

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java [hunk 9]
```diff
@@ -126,11 +133,50 @@ protected URI getVaultUrl() {
...
     }
 
+    /**
+     * Is correct version installed boolean.
+     *
+     * @return the boolean
+     */
+    public boolean isCorrectVersionInstalled() {
+        String installedVersion = getVaultVersion();
+        String expectedVersion = VaultTestKmsFacade.HASHICORP_VAULT.split(":")[1];
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java:157]: with the change above, you can use DockerImageName#getVersionPart() and get rid of the split.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java [hunk 10]
```diff
@@ -126,11 +133,50 @@ protected URI getVaultUrl() {
...
+        if (expectedVersion == null) {
+            return 1;
+        }
+        String[] currentParts = currentVersion.split("\\.");
+        String[] expectedParts = expectedVersion.split("\\.");
+
+        for (int i = 0; i < expectedParts.length; i++) {
+            int currentPart = i < currentParts.length ? Integer.parseInt(currentParts[i]) : 0;
+            int expectedPart = Integer.parseInt(expectedParts[i]);
+            if (currentPart < expectedPart)
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java]: you can use java.lang.Integer#compare(currentPart, expectedPart) and return != 0

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java [hunk 11]
```diff
@@ -126,11 +133,50 @@ protected URI getVaultUrl() {
...
+    public boolean isCorrectVersionInstalled() {
+        String installedVersion = getVaultVersion();
+        String expectedVersion = VaultTestKmsFacade.HASHICORP_VAULT.split(":")[1];
+
+        return compareTo(installedVersion, expectedVersion) == 0;
+    }
+
+    private int compareTo(String currentVersion, String expectedVersion) {
+        if (expectedVersion == null) {
+            return 1;
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/resources/vault/KubeVaultTestKmsFacade.java:164]: I'd throw an exception, it'd be clearer what has gone wrong.
```
Objects.requireNotNull(expectedVersion);
```

File: kroxylicious-systemtests/src/test/java/io/kroxylicious/systemtests/EnvelopeEncryptionST.java [hunk 12]
```diff
@@ -54,6 +56,10 @@ void setUp() {
         else {
             NamespaceUtils.createNamespaceWithWait(Vault.VAULT_DEFAULT_NAMESPACE);
             kubeVaultTestKmsFacade.start();
+            assumeThat(kubeVaultTestKmsFacade.isCorrectVersionInstalled())
```
Comment (k-wall) [inline kroxylicious-systemtests/src/test/java/io/kroxylicious/systemtests/EnvelopeEncryptionST.java:59]: Why assumeThat?  Surely we want to fail if there's a conflict.  assumeThat skips the tests.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java [hunk 13]
```diff
@@ -88,6 +89,27 @@ public boolean isAvailable() {
...
+            exec.exitCode().join();
+            // version returned as: Vault v1.15.2 (blah blah), build blah
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java:105]: fail if exitCode != 0.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java [hunk 14]
```diff
@@ -88,6 +89,27 @@ public boolean isAvailable() {
...
+            return output.toString().split(" ")[1].replace("v", "");
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java:106]: fail in an obvious way if the string doesn't match the expectation

Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java:106]: split on whitespace rather than a space and allow 1 or more.  It'll be slightly more robust against inconsequential changes.
```suggestion
            return output.toString().split("\\s+")[1].replace("v", "");
```

File: kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java (hunk 8 above)
Comment (k-wall) [reply kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java:39]: Please make io.kroxylicious.kms.provider.hashicorp.vault.TestVault#HASHICORP_VAULT refer to the same symbol too.

Comment (franvila) [reply kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java]: Mm it is not a trivial change. If I try to get the value from class `VaultTestKmsFacade` it generates a circular dependency between both modules.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java (hunk 7 above)
Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/installation/vault/Vault.java:105]: If I remove the shell, the vault command is not recognize and it fails.

File: kroxylicious-systemtests/src/test/java/io/kroxylicious/systemtests/EnvelopeEncryptionST.java [hunk 15]
```diff
@@ -54,6 +55,10 @@ void setUp() {
         else {
             NamespaceUtils.createNamespaceWithWait(Vault.VAULT_DEFAULT_NAMESPACE);
             kubeVaultTestKmsFacade.start();
+            assertThat(kubeVaultTestKmsFacade.isCorrectVersionInstalled())
```
Comment (k-wall) [inline kroxylicious-systemtests/src/test/java/io/kroxylicious/systemtests/EnvelopeEncryptionST.java:58]: I'd suggest giving KubeVaultTestKmsFacade#startVault() the responsibility to check whether the expected version is install, if no, throw an exception.  It shouldn't really be a concern of the tests.  isCorrectVersionInstalled is then private.

File: kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java (hunk 8 above)
Comment (k-wall) [reply kroxylicious-kms-provider-hashicorp-vault-test-support/src/main/java/io/kroxylicious/kms/provider/hashicorp/vault/VaultTestKmsFacade.java]: Fair enough.. We can sort that out later

**Review by k-wall — APPROVED** [review]
