### PR TITLE
Re-order responses to match the order they are received from client 

### LINKED ISSUE #505: Short-circuit responses can break client-broker ordering guarantees
**Describe the bug**

Currently if we have proxied a message to the broker we could then move onto the next message and short-circuit respond. The client will receive the short-circuit response first, which breaks the contract that they expect responses back in the order they sent them.

The order of events looks like this:
1. client sends message A then message B to kroxylicious
2. kroxylicious forwards message A towards upstream broker
3. kroxylicious short-circuit response to message B, sending a response toward the client
4. the broker responds to message A, kroxylicious forwards it towards the client
5. the client receives B-response, then A-response. **wrong order**

Here's a PR with a [failing integration test](https://github.com/kroxylicious/kroxylicious/pull/504) demonstrating the issue.

**Expected behavior**
Short-circuit responses are a desirable feature. We should try and keep the feature and make it satisfy the client-broker contract.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Resolves #505 

Currently if we have proxied a message to the broker we could then move onto the next message and short-circuit respond. The client will receive the short-circuit response first, which breaks the contract that they expect responses back in the order they sent them.

The order of events looks like this:

1. client sends message A then message B to kroxylicious
2. kroxylicious forwards message A towards upstream broker
3. kroxylicious short-circuit response to message B, sending a response toward the client
4. the broker responds to message A, kroxylicious forwards it towards the client
5. the client receives B-response, then A-response. **wrong order**

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by k-wall — APPROVED** [review]
Looks like a reasonable approach to me.  I can't improve on the responseorderer idea.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+import java.util.Map;
+
+import io.netty.channel.ChannelDuplexHandler;
+import io.netty.channel.ChannelHandlerContext;
+import io.netty.channel.ChannelPromise;
+
+import io.kroxylicious.proxy.frame.Frame;
+
+public class ResponseOrderer extends ChannelDuplexHandler {
+
```
Comment (k-wall) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:21]: Could we add unit tests exercising the case where > 1 responses are outstanding?

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+            if (oldestRequest == null) {
+                super.write(ctx, msg, promise);
+            }
+            else if (oldestRequest == frame.correlationId()) {
+                stack.removeFirst();
+                super.write(ctx, msg, promise);
+                drainQueue(ctx);
+            }
+            else {
+                queue.put(frame.correlationId(), new FutureThing(msg, promise));
```
Comment (k-wall) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:49]: Not for now - we might want a gauge monitoring the depth of this queue.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java (hunk 1 above)
Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:38]: Added unit tests covering basic inbound/outbound forward and these scenarios:

1. request-1 in, response-1 out
2. request-1 in, request-2 in, response-1 out, response-2 out
3. request-1 in, request-2 in, response-2 out, response-1 out (checks that the responses are re-ordered)
3. request-1 in, request-2 in, request-3 in, request-4 in response-2 out, response-4 out, response-1 out, response-3 out (checks the case where we can drain some but not all of the queued responses)

**Comment by robobario** [comment]
@strimzi-ci run perf

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java (hunk 1 above)
Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:38]: edit: and added

request-1 in, request-2 in, request-3 in, response-2 out, response-3 out, response-1 out (checks the case where we can drain multiple pending responses in reaction to the response-1 write)

File: kroxylicious-test-tools/src/main/java/io/kroxylicious/test/client/KafkaClientHandler.java [hunk 3]
```diff
@@ -18,26 +19,56 @@
  * Sends a single request frame, waits for a response then closes the channel
  */
 public class KafkaClientHandler extends ChannelInboundHandlerAdapter {
-    private final DecodedRequestFrame<?> decodedRequestFrame;
-    private final CompletableFuture<DecodedResponseFrame<?>> onResponse = new CompletableFuture<>();
+    private final List<DecodedRequestFrame<?>> decodedRequestFrames;
+    private final DecodedRequestFrame<?> initialRequest;
+    List<DecodedResponseFrame<?>> responses = new ArrayList<>();
+    private final CompletableFuture<List<DecodedResponseFrame<?>>> onResponse = new CompletableFuture<>();
+    private boolean readyToSendRemainingMessages;
```
Comment (SamBarker) [inline kroxylicious-test-tools/src/main/java/io/kroxylicious/test/client/KafkaClientHandler.java:26]: Does this need to be `volatile`?

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+
+import io.netty.channel.ChannelDuplexHandler;
+import io.netty.channel.ChannelHandlerContext;
+import io.netty.channel.ChannelPromise;
+
+import io.kroxylicious.proxy.frame.Frame;
+
+/**
+ * While processing a request from a Client, we want to enable custom Protocol
+ * Filters to decide to send a response toward the Client instead of forwarding
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:25]: We should try and stick to the upstream/downstream language where possible. 
```suggestion
 * Filters to decide to send a response downstream instead of forwarding
```

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java (hunk 1 above)
Comment (SamBarker) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:38]: Reading the Kafka Protocol guide it says:

> The server guarantees that on a single TCP connection, requests will be processed in the order they are sent and responses will return in that order as well. The broker's request processing allows only a single in-flight request per connection in order to guarantee this ordering.

Which would suggest that we only need to worry about a single outstanding request.

However it goes on to say 
> Note that clients can (and ideally should) use non-blocking IO to implement request pipelining and achieve higher throughput. i.e., clients can send requests even while awaiting responses for preceding requests since the outstanding requests will be buffered in the underlying OS socket buffer

Which implies multiple requests can be considered in-flight...

Have you been able to demonstrate multiple requests in flight? I only ask as supporting a single outstanding request is a lot cheaper perf wise than supporting `N`.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+ * they sent the requests.
+ * This class tries to ensure that we respond to requests in the correct order by
+ * remembering which correlationIds are in-flight and enqueuing any responses we
+ * get that are out of order. Then, when we do encounter the response for the
+ * oldest in-flight correlationId we can check if there are any enqueued
+ * responses that can now be forwarded towards the client.
+ */
+public class ResponseOrderer extends ChannelDuplexHandler {
+
+    Deque<Integer> inflightCorrelationIds = new ArrayDeque<>();
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:39]: I'm wondering if these should be maintained as a channel property? Are there uses cases where Filters mights care if there are pending requests?

**Review by SamBarker — APPROVED** [review]
I am wondering if there are cheaper options around only supporting a single pending correlation ID but otherwise this LGTM.

I'm also wondering about a benchmark to understand the costs of the queuing but I'm not sure how easy it would be to isolate the costs from netty (in the benchmark) and thus how valuable it would be.

**Comment by robobario** [comment]
> Have you been able to demonstrate multiple requests in flight? I only ask as supporting a single outstanding request is a lot cheaper perf wise than supporting N.

It depends what you mean by demonstrate. We can provoke the problem by sending multiple messages to Kroxylicious manually. Do you mean reproduce with an official client? The producer configuration has [max.in.flight.requests.per.connection](https://kafka.apache.org/documentation/#producerconfigs_max.in.flight.requests.per.connection) with a default of 5. Which is:
> The maximum number of unacknowledged requests the client will send on a single connection before blocking.

**Comment by robobario** [comment]
Ech it's twisty, we don't know at that point in the code whether it's a zero-ack Produce request if we are working with an opaque frame. There's some code later used to read the acks out of the opaque buffer, which should probably move earlier in the chain.

File: integrationtests/src/test/java/io/kroxylicious/proxy/KrpcFilterIT.java [hunk 6]
```diff
@@ -164,6 +169,26 @@ public void requestFiltersCanRespondWithoutProxying(KafkaCluster cluster, Admin
         }
     }
 
+    @Test
```
Comment (k-wall) [inline integrationtests/src/test/java/io/kroxylicious/proxy/KrpcFilterIT.java:172]: Maybe this test should be in the OutOfBandIT?

**Comment by SamBarker** [comment]
based on https://github.com/kroxylicious/kroxylicious/pull/507#issuecomment-1663546203 yeah ok we need to support multiple pending messages. 

Am I right in saying this is blocked by the PR shifting the `ack=X` extraction?

**Comment by robobario** [comment]
> Am I right in saying this is blocked by the PR shifting the `ack=X` extraction?

Yes

**Comment by k-wall** [comment]
Please review the description on #531 before merging this. It concerns the (mock) KafkaClient.  I took a divergent approach to what's @robobario's done.  We need to decide which approach we prefer.

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java [hunk 7]
```diff
@@ -0,0 +1,212 @@
...
+
+    @Override
+    public void encode(ByteBufAccessor out) {
+        throw new IllegalStateException("Not implemented");
+    }
+
+    @Override
+    public int correlationId() {
+        return correlationId;
+    }
```
Comment (SamBarker) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java:40]: Is there a reason this isn't indented one level?

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java [hunk 8]
```diff
@@ -0,0 +1,212 @@
...
+        orderer = new ResponseOrderer();
+        embeddedChannel.pipeline().addFirst(orderer);
+    }
+
+    @Test
+    void testInboundFrameForwarded() {
+        TestFrame request = new TestFrame(1);
+        whenWriteInboundMessage(request);
+        thenInboundContains(request);
+        thenOrdererStateEquals(1, 0);
```
Comment (SamBarker) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java:85]: I appreciate this would lead to a bunch of duplication, but I wonder if we should just inline `thenOrdererStateEquals` or make it two separate checks e.g.
```suggestion
        thenThereAreRequestInFlight(1);
        thenThereareQueuedResponses(0);
```

As I don't really feel that `thenOrdererStateEquals` tells a reader whats going on.

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java [hunk 9]
```diff
@@ -0,0 +1,212 @@
...
+        TestFrame response = new TestFrame(1);
+        whenWriteOutboundMessage(response);
+        thenOrdererStateEquals(0, 0);
+        thenOutboundContains(response);
+    }
+
+    @Test
+    void testMultipleInflightMessagesThatRespondInOrder() {
```
Comment (SamBarker) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java:142]:
```suggestion
    void testThatResponseOrderIsPreserved() {
```
?

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java [hunk 10]
```diff
@@ -0,0 +1,212 @@
...
+        thenOutboundContains(response2);
+        thenOutboundIsEmpty();
+    }
+
+    @Test
+    void testMultiplePendingAreDrained() {
+        whenWriteInboundMessage(new TestFrame(1));
+        whenWriteInboundMessage(new TestFrame(2));
+        whenWriteInboundMessage(new TestFrame(3));
+        thenOrdererStateEquals(3, 0);
```
Comment (SamBarker) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java:211]: Do we need this assertion? Given we have other tests that have confirmed this state?

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java [hunk 11]
```diff
@@ -0,0 +1,212 @@
...
+        whenWriteOutboundMessage(response2);
+        thenOrdererStateEquals(3, 2);
+        thenOutboundIsEmpty();
+
+        TestFrame response3 = new TestFrame(1);
+        whenWriteOutboundMessage(response3);
+        thenOrdererStateEquals(0, 0);
+        thenOutboundContains(response3);
+        thenOutboundContains(response);
+        thenOutboundContains(response2);
```
Comment (SamBarker) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java:227]: I find the naming of the response frames a bit funky. I get that this is the third response hence `response3` but its also the response to `frame 1` so I think it would read better if  was named for the frame it was the response for.

```suggestion
        TestFrame responseToFrame1 = new TestFrame(1);
        whenWriteOutboundMessage(responseToFrame1);
        thenOrdererStateEquals(0, 0);
        thenOutboundContains(responseToFrame1);
        thenOutboundContains(responseToFrame2);
        thenOutboundContains(responseToFrame3);
```

Though I'm tempted to say we should introduce 
```java
thenOutboundContainsInOrder(responseToFrame1, responseToFrame2, responseToFrame3);

void thenOutboundContainsInOrder(Object... responses) {
    List<Object> outboundMessages = new ArrayList<>();
    while (Object o = embeddedChannel.flushOutbound().readOutbound() != null) {
        outboundMessages.add(o);
    }
    assertThat(outboundMessages).containsInOrder(responses);
```

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java (hunk 5 above)
Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:40]: I can't think of a use case

**Review by SamBarker — APPROVED** [review]
Looking good @robobario

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java (hunk 5 above)
Comment (SamBarker) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/ResponseOrderer.java:40]: yeah, I guess its quite contrived to think of a filter choosing to only take an async action if and only iff auto read is already off.

File: kroxylicious-test-tools/src/main/java/io/kroxylicious/test/codec/KafkaResponseDecoder.java [hunk 12]
```diff
@@ -16,12 +16,14 @@
...
 
 import io.kroxylicious.test.client.CorrelationManager;
+import io.kroxylicious.test.client.SequencedResponse;
 
 /**
  * KafkaResponseDecoder
  */
 public class KafkaResponseDecoder extends KafkaMessageDecoder {
 
+    int i = 0;
```
[the remark this answers is not in the document]
Comment (robobario) [reply kroxylicious-test-tools/src/main/java/io/kroxylicious/test/codec/KafkaResponseDecoder.java:26]: these netty handler adapters should be single threaded I believe

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java (hunk 7 above)
Comment (robobario) [reply kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java:40]: ah yeahp, the maven plugin doesn't like records defined within classes, need to sort that out

Comment (SamBarker) [reply kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java:40]: Sigh. Ok

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java (hunk 11 above)
Comment (robobario) [reply kroxylicious/src/test/java/io/kroxylicious/proxy/internal/ResponseOrdererTest.java]: I went through and made them follow that pattern `responseForFrame1` throughout the more complex scenarios

**Review by SamBarker — APPROVED** [review]
Thanks @robobario the tests read a lot better now
