### PR TITLE
Handle ApiVersions unsupported version downgrade

### LINKED ISSUE #1611: Proxy doesn't work with kafka-clients:3.9.0
**Describe the bug**
When using java kafka-clients (https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients/3.9.0) producer in version 3.9.0 proxy is unable to handle requests.
We're getting following errors

> 	Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Can't size version 4 of ApiVersion
2024-11-20 08:54:22 <epollEventLoopGroup-5-1> WARN  io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler:485 - Netty caught exception from the frontend: org.apache.kafka.common.errors.UnsupportedVersionException: Can't size version 4 of ApiVersion
io.netty.handler.codec.EncoderException: org.apache.kafka.common.errors.UnsupportedVersionException: Can't size version 4 of ApiVersion
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.kroxylicious.proxy.internal.ResponseOrderer.write(ResponseOrderer.java:69) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:964) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:300) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.kroxylicious.proxy.internal.KafkaProxyBackendHandler.channelRead(KafkaProxyBackendHandler.java:62) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.kroxylicious.proxy.internal.FilterHandler.forwardResponse(FilterHandler.java:370) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.handleResponseFilterResult(FilterHandler.java:243) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.lambda$configureResponseFilterChain$8(FilterHandler.java:194) ~[kroxylicious-runtime-0.9.0.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at io.kroxylicious.proxy.internal.FilterHandler.configureResponseFilterChain(FilterHandler.java:194) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.readDecodedResponse(FilterHandler.java:176) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.channelRead(FilterHandler.java:105) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.kroxylicious.proxy.internal.FilterHandler.forwardResponse(FilterHandler.java:370) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.handleResponseFilterResult(FilterHandler.java:243) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.lambda$configureResponseFilterChain$8(FilterHandler.java:194) ~[kroxylicious-runtime-0.9.0.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) [?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) [?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) [?:?]
	at io.kroxylicious.proxy.internal.FilterHandler.configureResponseFilterChain(FilterHandler.java:194) [kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.readDecodedResponse(FilterHandler.java:176) [kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.FilterHandler.channelRead(FilterHandler.java:105) [kroxylicious-runtime-0.9.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1495) [netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1358) [netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1407) [netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) [netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469) [netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [netty-transport-classes-epoll-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) [netty-transport-classes-epoll-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) [netty-transport-classes-epoll-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.113.Final.jar:4.1.113.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

**To Reproduce**
1. use proxy version 0.9.0
2. produce records using kafka-clients:3.9.0

**Expected behavior**
Records are passed to target kafka cluster

**Additional info**
* we're using TLS and SNI routing
*  target kafka cluster is 3.7.0
* connection from kafka-clients:3.9.0 to kafka cluster 3.7.0 without the proxy in between worked

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Closes #1611

When proxy receives an unknown ApiVersionsRequest version it:
1. does not parse any bytes beyond the latest header version known bytes.
   (making the same assumption as the broker, that future header versions
   will be backwards compatible)
2. constructs a frame containing a special v0 ApiVersionsRequest and
   forwards it on
3. intercepts that frame with an internal filter, which detects the
   message is special and then responds with an ApiVersionsResponse with
   the error code set to UNSUPPORTED_VERSION and the api versions array
   populated with the supported versions for ApiVersions.

So the broker is not exposed to this special request.

We need to handle the client sending an ApiVersionsRequest at a version
higher than the proxy understands. The broker handles this by not
decoding the message body, and responding with a v0 ApiVersionsResponse
containing an UNSUPPORTED_VERSION error code and the api_versions array
populated with the supported versions for ApiVersions. This enables the
client to retry with the highest supported ApiVersions version. Prior to
Kafka 2.5.0 it just responded with an empty api_versions array and the
client would retry with a v0 request. This means that the broker would
never see the client software name and version, which is why they
changed to sending back the supported version. See KIP-511.

This proxy behaviour means in some cases clients will now experience two
UNSUPPORTED_VERSION responses in a row, one from the proxy and then one
from the broker, if the broker again supported a lower ApiVersions
version than the proxy. From our investigations the java client and 
librdkafka support this flow.

We also considered other flows where the proxy forwards on a v0
ApiVersionsRequest to the broker and then intercepts the response to
tactically set the error code and versions. But this could cause
problematic api interactions on the server side. For example the SASL
server authenticator currently cannot tolerate two valid
ApiVersionsRequests in a row. There may be no clients affected currently
(java SASL clientsends a v0 request so is unaffected), but since we can
identify this possible bad interaction and the core clients support the extra
retry we think it's safer to put the unusual behaviour onto the clients
rather than exposing the broker to unusual sequences of messages.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java [hunk 1]
```diff
@@ -105,10 +119,24 @@ protected Frame decodeHeaderAndBody(ChannelHandlerContext ctx, ByteBuf in, final
...
+    private @NonNull DecodedRequestFrame<ApiVersionsRequestData> createV0ApiVersionRequestFrame(ChannelHandlerContext ctx,
+                                                                                                int correlationId) {
+        if (log().isTraceEnabled()) { // avoid boxing
+            log().trace("{}: downgrading apiVersion request to v0", ctx);
+        }
+        RequestHeaderData requestHeaderData = new RequestHeaderData();
+        requestHeaderData.setCorrelationId(correlationId);
+        requestHeaderData.setRequestApiKey(ApiKeys.API_VERSIONS.id);
+        requestHeaderData.setRequestApiVersion((short) 0);
+        ApiVersionsRequestData apiVersionsRequestData = SPECIAL_DOWNGRADED_REQUEST_DATA;
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java:135]: You are using the singleton instance of SPECIAL_DOWNGRADED_REQUEST_DATA so that the DowngradeFilter can distinguish between a client using version 0 and the downgrade case.

An alternative would be to subclass ApiVersionsRequestData as DowngradedApiVersionsRequestData and let the  filter use an `instanceof`.

**Comment by k-wall** [comment]
I have tested in detail but I think the approach looks good.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java (hunk 1 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java:135]: Good idea Keith, I have reimplemented it this way and overridden a few methods so that if anything attempted to write the special message as byte the `size` and `write` methods will throw, as an extra defence in case we lost the short-circuiting in a refactor.

**Review by SamBarker — APPROVED** [review]
I think this makes sense but I haven't tried it out locally (and wont be able to while travelling)

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/ApiVersionsDowngradeIT.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+/**
+ * <p>
+ * In addition to the behaviour tested by {@link ApiVersionsIT} we also need to handle the client
+ * sending ApiVersions requests at an apiVersion higher than the proxy understands. With no proxy
+ * involved, the behaviour is the broker will respond with a v0 apiversions response and the error
+ * code is set to UNSUPPORTED_VERSION and the api_versions array populated with the supported versions
+ * for ApiVersions, so that the client can retry with the highest supported ApiVersions version.
+ * </p>
+ * <br>
+ * In this case the proxy will respond with it's own v0 response populated with the proxies supported
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/ApiVersionsDowngradeIT.java:42]:
```suggestion
 * In this case the proxy will respond with its own v0 response populated with the proxies supported
```

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java [hunk 3]
```diff
@@ -21,9 +22,12 @@
 import io.kroxylicious.proxy.frame.RequestFrame;
 import io.kroxylicious.proxy.internal.util.Metrics;
 
+import edu.umd.cs.findbugs.annotations.NonNull;
+
 public class KafkaRequestDecoder extends KafkaMessageDecoder {
 
     private static final Logger LOGGER = LoggerFactory.getLogger(KafkaRequestDecoder.class);
+    public static final ApiVersionsRequestData SPECIAL_DOWNGRADED_REQUEST_DATA = new ApiVersionsRequestData();
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java:30]:
```suggestion
```
dead code.

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java [hunk 4]
```diff
@@ -85,6 +88,17 @@ protected Frame decodeHeaderAndBody(ChannelHandlerContext ctx, ByteBuf in, final
         }
         final RequestFrame frame;
         if (decodeRequest) {
+            short highestProxyVersion = apiKey.latestVersion(true);
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java:91]: I wondered about `enableUnstableLastVersion = true`.  I wondered if this could mean a production environment could start using unstable versions spontaneously.  I decided that `true` is okay.  The client and broker would need to also have the same configuration for this is to be true. 

I think what you have done is okay.

**Comment by k-wall** [comment]
@robobario I think your approach is good.  I wanted to get some confidence of some tests against a real client https://github.com/robobario/kroxylicious/pull/15.  WDYT?   I also still want to do some testing against a librdkafka based client, I didn't quite reach that today.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/ApiVersionsDowngradeIT.java [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+        }
+    }
+
+    private static @NonNull OpaqueRequestFrame createHypotheticalFutureRequest() {
+        short unsupportedVersion = (short) (ApiKeys.API_VERSIONS.latestVersion(true) + 1);
+        RequestHeaderData requestHeaderData = getRequestHeaderData(API_VERSIONS_ID, unsupportedVersion, CORRELATION_ID);
+        short requestHeaderVersion = ApiKeys.API_VERSIONS.requestHeaderVersion(unsupportedVersion);
+        ObjectSerializationCache cache = new ObjectSerializationCache();
+        int headerSize = requestHeaderData.size(cache, requestHeaderVersion);
+        int bodySize = 4;
```
[the remark this answers is not in the document]
Comment (robobario) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/ApiVersionsDowngradeIT.java:83]: thanks i was searching around for that, I know I've seen it in Kroxy code before

[the remark this answers is not in the document]
Comment (robobario) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/ApiVersionsDowngradeIT.java:83]: I changed to `byte[]` instead so we only need the one var and can use `length`

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/DowngradeApiVersionsRequestData.java [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+
+import io.kroxylicious.proxy.frame.DecodedRequestFrame;
+
+import static io.kroxylicious.proxy.internal.codec.DowngradeRequestHeaderData.apiVersionsRequestDowngradeHeader;
+
+/**
+ * This subclass is used when we receive an ApiVersions request at an api version higher
+ * than the proxy supports. It should be handled internally with a short-circuit response
+ * and not forwarded to any broker.
+ */
```
[the remark this answers is not in the document]
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/DowngradeApiVersionsRequestData.java:22]: good point, I'll make them private classes of ApiVersionsDowngradeFilter to hide them away further

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java (hunk 4 above)
Comment (robobario) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/codec/KafkaRequestDecoder.java:91]: here's the commit where it was [added](https://github.com/kroxylicious/kroxylicious/pull/389/commits/7f2e4e51eac41a0fe645cc2e59974398432b0066)

I feel like I discussed it somewhere, but can't dig it up. The commit says:

> 3. `ApiMessageType#highestSupportedVersion()` has been removed/replaced
with `ApiMessageType$highestSupportedVersion(boolean enableUnstableLastVersion)`
I've made Kroxylicious support the unstable last version as it should be the
decision of the backing broker whether to accept unstable versions, the
proxy should handle them.

So yeah, the thought was by default the proxy shouldn't interfere if the client/broker want to use unstable versions.

**Comment by robobario** [comment]
Thanks @k-wall I've incorporated https://github.com/robobario/kroxylicious/pull/15. Some differences:

1. I've made it the `ApiVersionsServiceImpl`'s responsibility to know the latest supported version
2. I also made it sanity check at construction time that the user hasn't configured a latest version lower than the oldest version.
3. rebased things around so that the version override mechanism is in place before making the KIP-511 changes, if this PR gets unwieldy it should be easy to extract it into it's own PR now.
4. added in an ApiVersionsIT checking the intersection logic applies the overrides

**Comment by robobario** [comment]
@SamBarker I've gone ahead and incorporated a change from Keith which is an enabler for integration testing:

1. java client on X, proxy on X-1, broker on X

with real clients.

The user can override the max version for an ApiKey via an experimental proxy configuration, so we can pretend the proxy doesn't understand `v4` and trigger the fallback mechanism.

This lets us test that at least in this one case the java client can deal with a downgrade at the proxy (with plain and SASL)

**Comment by robobario** [comment]
a comment from @tombentley , we should consider distinguishing these from `experimental` but user facing configurations and make sure you have to jump through some hoops to switch these features on, so that this clearly some 'for-testing-only' feature. For example by setting an env/system var like `KROXYLICIOUS_ENABLE_INTERNAL_EXTENSIONS`, or having an environment enum where we could pass `Environment.DEVELOPMENT` to `KafkaProxy`. The field might be better named `internal` then `experimental`.

**Review by k-wall — APPROVED** [review]
lgtm

**Comment by k-wall** [comment]
I spent a bit more time testing this change today.  All looks good.  I tested against Redpanda (broker) and kafkajs (pure JS client).  In all cases, the api-versions downgrading seems to be good.

It'd be good to get some tests from using other clients into the testsuite, but I think this can wait.

**Comment by robobario** [comment]
Have pushed up something so users and tests have to opt into these internal features

This adds a concept of proxy environment where we identify two current
environments:
1. PRODUCTION: a proxy configured for production, internal development
   extensions are disallowed
2. DEVELOPMENT: a proxy configured for testing, internal development
   extensions are allowed

By default the proxy selects PRODUCTION as it's environment and will
fail to start with an exception if any internal configurations are
specified in the config file.

To opt in to the development environment the user must supply either:
1. a system prop `-DKROXYLICIOUS_ENVIRONMENT=DEVELOPMENT`
2. an env var `KROXYLICIOUS_ENVIRONMENT=DEVELOPMENT`
with the system-prop taking precedence.

Integration tests behave the same way, configuring the proxy with a
PRODUCTION environment, you have to set it to DEVELOPMENT explicitly
in your test to use any internal configurations.

**Comment by k-wall** [comment]
@robobario thanks, I'll review the new work soon.

Did you have chance to look at https://github.com/robobario/kroxylicious/pull/16?

**Comment by robobario** [comment]
> Did you have chance to look at https://github.com/robobario/kroxylicious/pull/16?

Nope, missed that.

File: kroxylicious-app/src/main/java/io/kroxylicious/app/Kroxylicious.java [hunk 7]
```diff
@@ -35,13 +35,18 @@ public class Kroxylicious implements Callable<Integer> {
 
     private static final Logger LOGGER = LoggerFactory.getLogger("io.kroxylicious.proxy.StartupShutdownLogger");
     private static final String UNKNOWN = "unknown";
-    private final BiFunction<PluginFactoryRegistry, Configuration, KafkaProxy> proxyBuilder;
+    public static final String KROXYLICIOUS_ENVIRONMENT = "KROXYLICIOUS_ENVIRONMENT";
```
Comment (k-wall) [inline kroxylicious-app/src/main/java/io/kroxylicious/app/Kroxylicious.java:38]: KROXYLICIOUS_ENVIRONMENT is a bit vague.   I'd suggest DEVELOPMENT_MODE which defaults to false.

File: kroxylicious-app/src/test/java/io/kroxylicious/app/KroxyliciousIT.java [hunk 8]
```diff
@@ -43,11 +51,76 @@ class KroxyliciousIT {
...
+        SubprocessKroxyliciousFactory kroxyliciousFactory = new SubprocessKroxyliciousFactory(tempDir, (environment, processBuilder) -> {
+            // no-op so that io is not inherited
+        }, List.of());
+        var tester = kroxyliciousTester(proxy("fake:9092").withInternal(Map.of("a", "b")), kroxyliciousFactory);
+        Process lastProcess = kroxyliciousFactory.lastProcess;
+        assertThat(lastProcess).isNotNull();
+        assertThat(lastProcess.onExit()).succeedsWithin(5, TimeUnit.SECONDS);
+        byte[] bytes = lastProcess.getInputStream().readAllBytes();
+        String output = new String(bytes, StandardCharsets.UTF_8);
+        assertThat(output).contains("internal configuration for proxy present in production environment");
```
Comment (k-wall) [inline kroxylicious-app/src/test/java/io/kroxylicious/app/KroxyliciousIT.java:67]: To avoid introducing the term "internal" we could just say "development mode configurations present without developer mode enabled"

**Comment by k-wall** [comment]
lgtm
