### PR TITLE
Fix #2091: OauthBearer factory needs to add the JWKS endpoint to the allow-list.

### LINKED ISSUE #2091: Kafka 4.0.0 : Oauthbearer fail without change properties
**Describe the bug**
Kafka 4.0.0 introduces a new "mandatory" system property when using `SASL_SSL` with `OAUTHBEARER`.
The property is described here : https://kafka.apache.org/documentation/#systemproperties_org.apache.kafka.sasl.oauthbearer.allowed.urls
Because of that, the proxy fails to start when upgrading from `0.11.0` to `0.12.0`

**To Reproduce**
```yaml
filterDefinitions:
  - name: jwt
    type: OauthBearerValidation
    config:
      jwksEndpointUrl: https://my.jwks.url
defaultFilters:
- jwt
```

**Expected behavior**
As a proxy owner, I want to upgrade from `0.11` to `0.12` without disruption.

**YAML files and logs**

```
io.kroxylicious.proxy.plugin.PluginConfigurationException: Exception initializing filter factory jwt with config Config[jwksEndpointUrl=https://my.jwks.url, jwksEndpointRefreshMs=null, jwksEndpointRetryBackoffMs=null, jwksEndpointRetryBackoffMaxMs=null, scopeClaimName=null, subClaimName=null, authenticateBackOffMaxMs=null, authenticateCacheMaxSize=null, expectedAudience=null, expectedIssuer=null]: https://my.jwks.url is not allowed. Update system property 'org.apache.kafka.sasl.oauthbearer.allowed.urls' to allow https://my.jwks.url
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory$Wrapper.<init>(FilterChainFactory.java:55)
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory.<init>(FilterChainFactory.java:114)
	at io.kroxylicious.proxy.KafkaProxy.startup(KafkaProxy.java:138)
	at io.kroxylicious.app.Kroxylicious.call(Kroxylicious.java:73)
	at io.kroxylicious.app.Kroxylicious.call(Kroxylicious.java:35)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2423)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.kroxylicious.app.Kroxylicious.main(Kroxylicious.java:123)
```

**Additional context**

- A test is missing to assert the `configure` step of `OAuthBearerValidatorCallbackHandler` in `OauthBearerValidation`
- We can certainly set the JWKS url defined by the user as authorized by default in JAVA Properties
```java
Config configWithDefaults = initConfigWithDefaults(config);
System.setProperty("org.apache.kafka.sasl.oauthbearer.allowed.urls", config.jwksEndpointUrl().toString());
oauthHandler.configure(
        createSaslConfigMap(configWithDefaults),
        OAUTHBEARER_MECHANISM,
        createDefaultJaasConfig());
```

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Bugfix

### Description

In Kafka 4.0.0, the OauthBearer server side needs to add the JWKS endpoint URL to an allow list
in order for the Kafka libraries to interact with it.

With this change, the OauthBearer factory will automatically set the Kafka `org.apache.kafka.sasl.oauthbearer.allowed.urls` system property to include the JWKS endpoint (if it does not already include the value).  To support embedded use-cases, the factory will undo the system properties changes on closure (this is a best effort approach).

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [x] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationIT.java [hunk 1]
```diff
@@ -94,8 +94,10 @@ class OauthBearerValidationIT {
     private static OauthServerContainer oauthServer;
 
     @BeforeAll
-    public static void beforeAll() {
-        // required to permit Kafka to interact with our endpoint.
+    static void beforeAll() {
+        // Kafka 4.0 requires that the org.apache.kafka.sasl.oauthbearer.allowed.urls sys property is set in order to use Oauth Bearer.
+        // The Kafka Broker and Proxy requires that JWKS_ENDPOINT_URL is in the allow list.
+        // The Kafka Client requires that TOKEN_ENDPOINT_URL is in the allow list.
         System.setProperty(ALLOWED_SASL_OAUTHBEARER_URLS_CONFIG, JWKS_ENDPOINT_URL + "," + TOKEN_ENDPOINT_URL);
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationIT.java:101]: This is a bit of a compromise - in two ways:

* It'd be much better if Kafka didn't rely on a system property for configuring the allow list, or at least had separate client and server side properties.   Maybe an RFE against Kafka would be a good idea.  That would allow the test to be much more precise.

* Separately, for this IT test case, the Kafka Broker needs the JWKS_ENDPOINT_URL in allow list too.   Ideally, we'd use a Container based Kafka so we had precise control, but we've got no way to influence the system properties for the Container's JVM.

So, we sledgehammer it - and set both Token and JWKS endpoints from the IT test.  I've written the unit test in such a way to give us confidence that Kroxylicious will do the right thing.

**Comment by k-wall** [comment]
@callaertanthony would you be able to review & confirm if the change resolves the defect. thank you.

File: kroxylicious-filters/kroxylicious-oauthbearer-validation/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationTest.java [hunk 2]
```diff
@@ -132,8 +143,55 @@ void mustCloseOauthHandler() throws Exception {
...
+                .isNotEmpty()
+                .contains(config.jwksEndpointUrl().toString());
+    }
+
+    static Stream<Arguments> closeShouldRestoreOauthAllowList() {
+        return Stream.of(
+                Arguments.argumentSet("clears system property after close",
+                        (Consumer<String>) unused -> System.clearProperty(ALLOWED_SASL_OAUTHBEARER_URLS_CONFIG),
+                        (BiConsumer<String, String>) (initial, propValue) -> assertThat(propValue).isNull()),
+                Arguments.argumentSet("preserves existing system property value",
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-oauthbearer-validation/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationTest.java:166]: Think the naming here should be improved as `existing system property value` can easily be confused with `other endpoint values`. Maybe it could be something like `preserves existing system property that exactly matches config value`.

File: kroxylicious-filters/kroxylicious-oauthbearer-validation/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationTest.java [hunk 3]
```diff
@@ -132,8 +143,55 @@ void mustCloseOauthHandler() throws Exception {
...
+                        (Consumer<String>) initial -> System.setProperty(ALLOWED_SASL_OAUTHBEARER_URLS_CONFIG, initial),
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-oauthbearer-validation/src/test/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidationTest.java:167]: `initial` makes me think of the System prop before initialization. Maybe this should be called `configValue` in the lambdas?

File: kroxylicious-filters/kroxylicious-oauthbearer-validation/src/main/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidation.java [hunk 4]
```diff
@@ -43,10 +46,15 @@ public class OauthBearerValidation implements FilterFactory<OauthBearerValidatio
 
     private final OAuthBearerValidatorCallbackHandler oauthHandler;
 
+    @VisibleForTesting
+    static final String ALLOWED_SASL_OAUTHBEARER_URLS_CONFIG = "org.apache.kafka.sasl.oauthbearer.allowed.urls";
```
[the remark this answers is not in the document]
Comment (k-wall) [reply kroxylicious-filters/kroxylicious-oauthbearer-validation/src/main/java/io/kroxylicious/proxy/filter/oauthbearer/OauthBearerValidation.java:50]: I didn't do this because it felt wrong to import a symbol from a package with internals in its name `org.apache.kafka.common.config.internals`

**Review by robobario — APPROVED** [review]
LGTM (pending review from Anthony)

**Review by callaertanthony — APPROVED** [review]
