### PR TITLE
Stabilize nondeterministic test

### LINKED ISSUE #3162: InternalCompletableFuture non-deterministic test
https://github.com/kroxylicious/kroxylicious/actions/runs/21050713316/job/60536095417?pr=3013

```
Error:  Failures: 
Error:    InternalCompletableFutureTest.exceptionHandlingWorkIsExecutedOnEventLoop:424 
Expecting
  <InternalCompletableFuture[Failed with the following stack trace:
org.opentest4j.AssertionFailedError: 
Expecting value to be true but was false
	at io.kroxylicious.proxy.internal.InternalCompletableFutureTest.assertThread(InternalCompletableFutureTest.java:568)
	at io.kroxylicious.proxy.internal.InternalCompletableFutureTest.captureThreadWithResult(InternalCompletableFutureTest.java:552)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:1011)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:995)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:503)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:148)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1195)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
]>
to be completed within 2L Seconds.
```

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Attempts to resolve #3162

We have seen instability in InternalCompletableFutureTest

Running the test on repeat in my IDE showed up failures on the:
```
actualThread.compareAndSet(null, Thread.currentThread())
```

So under some conditions it appears that prior tests could affect subsequent ones through this static variable, I guess some async code is updating the actualThread after a test has completed.

To fix it we create a ThreadCaptor per test so that there is not some global state they are competing to update. Each test uses it's own ThreadCaptor instance to obtain the thread that executed some work.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/InternalCompletableFutureTest.java [hunk 1]
```diff
@@ -29,16 +30,13 @@
...
-import edu.umd.cs.findbugs.annotations.Nullable;
-
 import static org.assertj.core.api.Assertions.assertThat;
 import static org.junit.jupiter.params.provider.Arguments.argumentSet;
 
 // we are asserting actual and expected in the correct order, the static actualThread triggers this warning
 @SuppressWarnings("java:S3415")
 class InternalCompletableFutureTest {
 
-    private static final AtomicReference<Thread> actualThread = new AtomicReference<>();
```
Comment (SamBarker) [inline kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/InternalCompletableFutureTest.java:41]: ahh yeah, that should be an instance field.

**Review by SamBarker — APPROVED** [review]
feels like it would have been simpler to just initialise the atomicReference in setup

**Comment by robobario** [comment]
will try out instance field, wasn't too sure how it interacted with ParameterizedTest

**Comment by robobario** [comment]
ah yeap it's tricky. you need a static method for the MethodSource and can't ref an instance variable

File: kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/InternalCompletableFutureTest.java (hunk 1 above)
Comment (robobario) [reply kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/internal/InternalCompletableFutureTest.java:41]: yeah just went back to have a look, but the reason it was done this way is we reference it from static methods used with `@MethodSource`. The parameterized tests need a static method which wouldn't be able to reference an instance field.

**Comment by SamBarker** [comment]
argh threading be hard.
