### PR TITLE
bugfix: kroxylicious main method exited immediately

### LINKED ISSUE #310: Kroxylicious main method exits (does not block until shutdown by signal or internal error)
**Describe the bug**
When you run kroxylicious as a jar (`io.kroxylicious.proxy.Kroxylicious#main`) it exits immediately. This was introduced with #279 as the `acceptorChannels` used in `KafkaProxy` to block until acceptorChannel close is now never added to and is empty when `KafkaProxy#block` is called.

**To Reproduce**
1. `mvn clean install -Pdist -Dquick`
2. `java -jar kroxylicious/target/kroxylicious-0.2.0-SNAPSHOT.jar -c kroxylicious/example-proxy-config.yml`
Kroxy will stop immediately.

**Expected behavior**
The kroxylicious process should then stay alive, blocking until it is killed or exits.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

As part of an enhancement (#279) some code that added acceptor Channels to a queue so they we could block until they close was lost.

Fixes #310

### CODE REVIEW

File: integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+     * Start proxy as a subprocess, so we have a way to signal it to shut down. If we instead run the
+     * main method in-process, when we terminate it, the backing netty services remain running and
+     * prevent the test from completing.
+     */
+    public static AutoCloseable startProxy(String config, Path tempDir) throws IOException {
+        Path configPath = tempDir.resolve("config.yaml");
+        Files.writeString(configPath, config);
+        String java = System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";
+        String classpath = System.getProperty("java.class.path");
+        ProcessBuilder processBuilder = new ProcessBuilder(java, "-cp", classpath, "io.kroxylicious.proxy.Kroxylicious", "-c", configPath.toString());
```
Comment (robobario) [inline integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java:118]: update to use `Kroxylicious.class.getName()` instead

File: integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+                        .build())
+                .addNewFilter().withType("ApiVersions").endFilter()
+                .addNewFilter().withType("BrokerAddress").endFilter();
+    }
+
+    /**
+     * Start proxy as a subprocess, so we have a way to signal it to shut down. If we instead run the
+     * main method in-process, when we terminate it, the backing netty services remain running and
+     * prevent the test from completing.
+     */
```
Comment (SamBarker) [inline integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java:112]: I think this is fine as a one off but if we start needing this as a more generic pattern we should look at managing it through a JUnit extension implementing [CloseableResource](https://junit.org/junit5/docs/5.8.2/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtensionContext.Store.CloseableResource.html)

File: kroxylicious/src/main/java/io/kroxylicious/proxy/KafkaProxy.java [hunk 3]
```diff
@@ -108,7 +108,11 @@ public KafkaProxy startup() throws InterruptedException {
         var bindFutures = networkBindings.stream()
                 .map(networkBinder -> networkBinder.bind(networkBinder.tls() ? tlsServerBootstrap : plainServerBootstrap))
                 .collect(Collectors.toSet());
-        bindFutures.forEach(channelFuture -> channelFuture.addListener(f -> LOGGER.info("Listening : {}", channelFuture.channel().localAddress())));
+        bindFutures.forEach(channelFuture -> channelFuture.addListener(f -> {
+            var channel = ((ChannelFuture) f).channel();
+            acceptorChannels.add(channel);
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/KafkaProxy.java:113]: I think this works for now but something about it bothers me (the shape of how we do blocking not the fix itself).

**Review by SamBarker — APPROVED** [review]
I want to revisit the blocking at some point but this seems like a good fix for now.

File: integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java (hunk 2 above)
Comment (robobario) [reply integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java:112]: Yep, I imagine this only existing until we come up with some more solid idea of how we distribute kroxy. I think then it would become an external test checking that whatever distribution artifacts we produce work (so exercising the docker image/tarball etc)

File: kroxylicious/src/main/java/io/kroxylicious/proxy/KafkaProxy.java (hunk 3 above)
Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/KafkaProxy.java:113]: Yeap, will have a go after merging this. It feels like we should be able to do something like collect up all the channels after the `sync` on all the bind futures and make a composed `allOf` type future out of all the closeFutures that we can block on without looping.
