### PR TITLE
refactor: Fix ErrorProne StatementSwitchToExpressionSwitch warnings 

### LINKED ISSUE #3711: Fix ErrorProne `StatementSwitchToExpressionSwitch` warnings
```
[WARNING] kroxylicious-kms-providers/kroxylicious-kms-provider-aws-kms/src/test/java/io/kroxylicious/kms/provider/aws/kms/AwsV4SigningHttpRequestBuilderTest.java:[184,8] [StatementSwitchToExpressionSwitch] This statement switch can be converted to a new-style arrow switch
[WARNING] kroxylicious-kms-providers/kroxylicious-kms-provider-aws-kms/src/test/java/io/kroxylicious/kms/provider/aws/kms/AwsV4SigningHttpRequestBuilderTest.java:[234,12] [StatementSwitchToExpressionSwitch] This statement switch can be converted to a new-style arrow switch
[WARNING] kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/ProxyChannelStateMachine.java:[734,12] [StatementSwitchToExpressionSwitch] This statement switch can be converted to a new-style arrow switch
[WARNING] kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyExceptionMapper.java:[264,8] [StatementSwitchToExpressionSwitch] This statement switch can be converted to a new-style arrow switch
[WARNING] kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/executor/Exec.java:[258,12] [StatementSwitchToExpressionSwitch] This statement switch can be converted to a new-style arrow switch
```

1. fix the warnings
2. Add StatementSwitchToExpressionSwitch to the pom.xml [here](https://github.com/kroxylicious/kroxylicious/blob/00329f397e4071bce8f9aded561e889581376512/pom.xml#L1349) to make this warning fail the build in future.

### PR DESCRIPTION
**Pull request by m1a2st**
### Type of change

_Select the type of your PR_

- Refactoring

### Description

Fixes ErrorProne `StatementSwitchToExpressionSwitch` warnings by converting statement switches to arrow switch expressions.

### Additional Context

https://github.com/kroxylicious/kroxylicious/issues/3711

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/executor/Exec.java [hunk 1]
```diff
@@ -256,14 +256,10 @@ private static void throwExceptionForErrorPattern(String msg, String err, ExecRe
...
-                    kubeClusterException = new KubeClusterException.NotFound(execResult, msg);
-                    break;
-                case "AlreadyExists":
-                    kubeClusterException = new KubeClusterException.AlreadyExists(execResult, msg);
-                    break;
-                default:
-                    break;
+                case "NotFound" -> kubeClusterException = new KubeClusterException.NotFound(execResult, msg);
+                case "AlreadyExists" -> kubeClusterException = new KubeClusterException.AlreadyExists(execResult, msg);
+                default -> {
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/executor/Exec.java]: I believe the default block is redundant and can be removed.  This will clean up the sonar issue.

**Review by k-wall — COMMENTED** [review]
Happy  to approve/merge once the minor issue in Exec is resolved.
thank you @m1a2st

**Review by k-wall — CHANGES_REQUESTED** [review]
As noted above.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/executor/Exec.java (hunk 1 above)
Comment (m1a2st) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/executor/Exec.java]: I have addressed this

Comment (robobario) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/executor/Exec.java]: and now sonar is unhappy with lack of the default block :grin: I think we should `@SuppressWarnings` the remaining sonar issues.

Comment (m1a2st) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/executor/Exec.java]: Let’s make Sonar happy.

**Review by robobario — APPROVED** [review]
LGTM, thanks @m1a2st

**Review by k-wall — APPROVED** [review]
LGTM
