### PR TITLE
fix: record encryption deterministically fails with large messages

### LINKED ISSUE #2504: The Encryptor has no more operations allowed when Event exceeds 1MB
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**
We have users reporting issues on some edge case Events which when enriched exceed 1MB. We initially thought it was the plans but the plans allow 2MB and direct to broker the Events work fine. However when sent via Kroxylicious for encryption we are seeing the following error in the Kroxylicious Logs

`WARN  io.kroxylicious.proxy.internal.FilterHandler: - [id: 0x76ad2e60, L:/IP:52200 - R:BOOTSTRAP_SERVER/IP:9094]: Filterrequest for RecordEncryptionFilter@1136274190 PRODUCE ended exceptionally - closing connection. Cause message io.kroxylicious.filter.encryption.dek.DekUsageException: The Encryptor has no more operations allowed`

The response the Producers are seeing is

`WARN [Producer clientId=perf-producer-client] Got error produce response with correlation id 5 on topic-partition test.performance.0-0, retrying (2147483646 attempts left). Error: NETWORK_EXCEPTION. Error Message: Disconnected from node 3 (org.apache.kafka.clients.producer.internals.Sender)`

**To Reproduce**
Our configuration is as follows

```
management:
  endpoints:
    prometheus: {}
filterDefinitions:
  - name: encryption
    type: RecordEncryption
    config:
      kms: AwsKmsService
      kmsConfig:
        endpointUrl: https://kms.eu-west-2.amazonaws.com
        ec2MetadataCredentials:
          iamRole: kafka-proxy-inter1-instance-role-dev
          credentialLifetimeFactor: 0.8
        region: eu-west-2
      selector: TemplateKekSelector
      selectorConfig:
        template: kms-key
defaultFilters:
  - encryption
virtualClusters:
  - name: oauth
    targetCluster:
      bootstrapServers: KAFKA_BOOTSTRAP_SERVERS
      tls:
        key:
          privateKeyFile: /var/ssl/private/kafka_proxy_backend.key
          certificateFile: /var/ssl/private/kafka_proxy_backend.crt
        trust:
          storeFile: /var/ssl/private/kafka_proxy_backend.truststore.jks
          storePassword:
            password: PASSWORD
          storeType: PKCS12
    gateways:
      - name: oauth-gateway
        portIdentifiesNode:
          bootstrapAddress: ADVERTISED_SERVER
          nodeIdRanges:
            - name: oauth-nodes
              start: 1
              end: 4
        tls:
          key:
            privateKeyFile: /var/ssl/private/kafka_proxy_frontend.key
            certificateFile: /var/ssl/private/kafka_proxy_frontend.crt
          trust:
            storeFile: /var/ssl/private/kafka_proxy_frontend.truststore.jks
            storePassword:
              password: a018b8658b966e1f598218672a582d7f6fab46e11b92c5228524e04720ccb8e9
            storeType: PKCS12
          protocols:
            allowed:
              - TLSv1.3
              - TLSv1.2
          cipherSuites:
            allowed:
              - TLS_AES_256_GCM_SHA384
              - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
              - TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
              - TLS_AES_128_GCM_SHA256
              - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              - TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
              - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
              - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
              - TLS_RSA_WITH_AES_256_GCM_SHA384
              - TLS_RSA_WITH_AES_128_GCM_SHA256
    logNetwork: false
    logFrames: false
```

We are using the kafka-producer-perf-test tool from our Confluent builds to replicate and had narrowed the issue down to sending a record-size of 1048319. 1048318 works again and again. We figured with the 2 bytes added by Kafka 1048318 + 2 is 1MB in binary 1048320.

When sending 1048319 the addition of the 2 bytes is pushing the 1MB and the encryption is failing, or that is our theory.

```
[root@IP bin]# kafka-producer-perf-test --topic test.performance.0 --num-records 1 --record-size 1048318 --throughput 1 --producer.config /tmp/proxy.props
1 records sent, 1.098901 records/sec (1.10 MB/sec), 831.00 ms avg latency, 831.00 ms max latency, 831 ms 50th, 831 ms 95th, 831 ms 99th, 831 ms 99.9th.
[root@IP bin]# kafka-producer-perf-test --topic test.performance.0 --num-records 1 --record-size 1048319 --throughput 1 --producer.config /tmp/proxy.props
[2025-07-30 13:39:08,815] WARN [Producer clientId=perf-producer-client] Got error produce response with correlation id 5 on topic-partition test.performance.0-0, retrying (2147483646 attempts left). Error: NETWORK_EXCEPTION. Error Message: Disconnected from node 3 (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:08,816] WARN [Producer clientId=perf-producer-client] Received invalid metadata error in produce request on partition test.performance.0-0 due to org.apache.kafka.common.errors.NetworkException: Disconnected from node 3 Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:08,999] WARN [Producer clientId=perf-producer-client] Got error produce response with correlation id 9 on topic-partition test.performance.0-0, retrying (2147483645 attempts left). Error: NETWORK_EXCEPTION. Error Message: Disconnected from node 3 (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:08,999] WARN [Producer clientId=perf-producer-client] Received invalid metadata error in produce request on partition test.performance.0-0 due to org.apache.kafka.common.errors.NetworkException: Disconnected from node 3 Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:09,318] WARN [Producer clientId=perf-producer-client] Got error produce response with correlation id 12 on topic-partition test.performance.0-0, retrying (2147483644 attempts left). Error: NETWORK_EXCEPTION. Error Message: Disconnected from node 3 (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:09,319] WARN [Producer clientId=perf-producer-client] Received invalid metadata error in produce request on partition test.performance.0-0 due to org.apache.kafka.common.errors.NetworkException: Disconnected from node 3 Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:09,807] WARN [Producer clientId=perf-producer-client] Got error produce response with correlation id 15 on topic-partition test.performance.0-0, retrying (2147483643 attempts left). Error: NETWORK_EXCEPTION. Error Message: Disconnected from node 3 (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:09,808] WARN [Producer clientId=perf-producer-client] Received invalid metadata error in produce request on partition test.performance.0-0 due to org.apache.kafka.common.errors.NetworkException: Disconnected from node 3 Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:10,753] WARN [Producer clientId=perf-producer-client] Got error produce response with correlation id 18 on topic-partition test.performance.0-0, retrying (2147483642 attemptsleft). Error: NETWORK_EXCEPTION. Error Message: Disconnected from node 3 (org.apache.kafka.clients.producer.internals.Sender)
[2025-07-30 13:39:10,754] WARN [Producer clientId=perf-producer-client] Received invalid metadata error in produce request on partition test.performance.0-0 due to org.apache.kafka.common.errors.NetworkException: Disconnected from node 3 Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
```

You can keep sending 1048318 and it works over and over, but change to 1048319 and it fails. 1048318 will work immediately afterwards, so it recovers.

It seems to be something to do with however it calculates numEncryptions in Dek.generateParameters (line 224). I've been trying to find out where it calculates that figure and what it means. Is it there to control chunking of the encrypted records?

**Expected behavior**
Events over 1MB to have no issues as we can send direct to the broker with none, so would also expect Kroxylicious to encrypt any Event that is within the configured plans we have set for topics. I.e. 2MB plan would allow 2MB Event

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Fixes #2504 

> **TL;DR:** This PR fixes a bug where encryption would consistently fail for large message batches (> 1MB). The retry mechanism was incorrectly re-using a partially consumed `Encryptor`. The fix ensures a **new** `Encryptor` is requested from the DEK for any retry attempt.

### The Problem

When a Kafka client sent a large batch of messages that required an encrypted output buffer larger than the initial 1MB, the operation would consistently fail and return an error to the client.

### The Root Cause

The encryption logic follows these steps:
1.  An `Encryptor` object is requested from the Data Encryption Key (DEK) service, authorized for `N` encryption operations to match the `N` records in the batch.
2.  An initial 1MB buffer is allocated for the encrypted output.
3.  As each record is prepared for encryption, the `Encryptor`'s available operation count is decremented.

If the 1MB buffer proved insufficient, a `BufferTooSmallException` was thrown. The process was designed to catch this, increase the buffer size, and retry the entire batch.

The bug was that the **same `Encryptor` object was used for the retry**. By this point, its operation count had already been partially decremented from the first failed attempt. The remaining operation count was now less than the total number of records in the batch, guaranteeing that the retry would also fail.

### The Solution

The fix is to **request a new `Encryptor`** for the retry operation. When a `BufferTooSmallException` occurs:
- The existing, partially used `Encryptor` is discarded.
- A fresh `Encryptor` with the full operation count is fetched from the DEK.
- The encryption is attempted again with the larger buffer.

This change ensures that retries for large messages can succeed. While this may leave some authorized operations from the original `Encryptor` unused, it correctly enforces the security model by preventing any over-spending of encryption allowances. Contrast with #2506 a potential solution that can credit operations back to the Encryptor.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManager.java [hunk 1]
```diff
@@ -148,15 +149,18 @@ private CompletionStage<MemoryRecords> attemptEncrypt(@NonNull String topicName,
...
                                          @NonNull EncryptionScheme<K> encryptionScheme,
                                          @NonNull MemoryRecords memoryRecords,
-                                         @NonNull Dek<E>.Encryptor encryptor,
                                          @NonNull IntFunction<ByteBufferOutputStream> bufferAllocator) {
         ByteBuffer recordBuffer = ByteBuffer.allocate(recordBufferInitialBytes);
         do {
-            try {
+            // create a new encryptor for each attempt as it's requested encryption operations may be partially consumed by the attempt
+            // leaving us with too few operations remaining to encrypt the batches
+            try (Dek<E>.Encryptor encryptor = dek.encryptor(allRecordsCount)) {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManager.java:163]: dek exhaustion exceptions etc should still be caught up in `attemptEncrypt` and trigger rotation/retry the same way, if the `encryptor` call throws.

File: kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java [hunk 2]
```diff
@@ -68,6 +68,29 @@ void testMultipleThreadsCooperateToMinimiseDekCreations() {
...
+    void shouldGrowBuffer() {
+        // Given
+        InMemoryKms kms = getInMemoryKms();
+        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
+        final DekManager<UUID, InMemoryEdek> dekManager = new DekManager<>(new AsyncKms<>(kms, executor), 10000);
+        EncryptionDekCache<UUID, InMemoryEdek> cache = new EncryptionDekCache<>(dekManager, executor, EncryptionDekCache.NO_MAX_CACHE_SIZE, Duration.ofHours(1),
+                Duration.ofHours(1));
+        var encryptionManager = createEncryptionManager(dekManager, cache, executor);
+        var kekId = kms.generateKey();
+        var value = new byte[3 * 1024 * 1024];
```
Comment (tombentley) [inline kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java]: Give we're testing how the buffer growth interacts with dek allocation, I think we should be commenting something about the magic numbers in this test.

Comment (robobario) [reply kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java]: have renamed the var and added a constant for the initial buffer size so it's defined in terms of that

**Comment by robobario** [comment]
Wondering what other behaviour would be good to test here. Maybe we could test at the limit, that if this happens at the edge of an exhausted DEK, that it can succeed with the new DEK

File: kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManager.java (hunk 1 above)
Comment (robobario) [reply kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManager.java:163]: unit test added for this behaviour, demonstrating an encrypt can succeed when retrying just as a DEK is exhausted by the too-small-buffer encrypt attempt

**Review by tombentley — APPROVED** [review]

**Comment by robobario** [comment]
I think we should, in a separate PR, think more about the buffer sizing. 

1. Users may want to resize the init and max size to suit their messages and broker max message size.
2. We could potentially use the MemoryRecords size in bytes + (recordsCount * fixed_overhead) to size the buffer, using that as a starting point if it's between initSize and maxSize.
3. Or we could track the maximum encrypted size in bytes globally or per-topic and use that as the init size if it's > default.

**Comment by robobario** [comment]
thought I'd wait for a review from @SamBarker @k-wall , feel free to make changes or merge if you're happy with the approach.

File: kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java [hunk 3]
```diff
@@ -38,6 +38,8 @@
 
 class InBandEncryptionManagerTest {
 
+    public static final int RECORD_BUFFER_INITIAL_BYTES = 1024 * 1024;
```
Comment (SamBarker) [inline kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java:41]: nit: the constant from the prod code is visible with the same name, maybe just import that?

File: kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java [hunk 4]
```diff
@@ -68,6 +70,65 @@ void testMultipleThreadsCooperateToMinimiseDekCreations() {
...
 
+    @Test
+    void shouldGrowBuffer() {
+        // Given
+        InMemoryKms kms = getInMemoryKms();
+        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
+        final DekManager<UUID, InMemoryEdek> dekManager = new DekManager<>(new AsyncKms<>(kms, executor), 10000);
+        EncryptionDekCache<UUID, InMemoryEdek> cache = new EncryptionDekCache<>(dekManager, executor, EncryptionDekCache.NO_MAX_CACHE_SIZE, Duration.ofHours(1),
+                Duration.ofHours(1));
+        var encryptionManager = createEncryptionManager(dekManager, cache, executor);
```
Comment (SamBarker) [inline kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java:81]: we could probably pull this out to a setup method

File: kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java [hunk 5]
```diff
@@ -68,6 +70,65 @@ void testMultipleThreadsCooperateToMinimiseDekCreations() {
         assertThat(cache.invalidationCount()).isEqualTo(numEncryptionOperations - 1);
     }
 
+    @Test
+    void shouldGrowBuffer() {
+        // Given
+        InMemoryKms kms = getInMemoryKms();
+        ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
+        final DekManager<UUID, InMemoryEdek> dekManager = new DekManager<>(new AsyncKms<>(kms, executor), 10000);
```
Comment (SamBarker) [inline kroxylicious-filters/kroxylicious-record-encryption/src/test/java/io/kroxylicious/filter/encryption/encrypt/InBandEncryptionManagerTest.java:78]: Should we reduce the max encryptions here?

**Comment by SamBarker** [comment]
@robobario please could you also address the sonar nits

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/RecordEncryptionFilterIT.java [hunk 6]
```diff
@@ -123,6 +125,37 @@ void roundTripSingleRecord(KafkaCluster cluster, Topic topic, TestKmsFacade<?, ?
...
+
+        NamedFilterDefinition namedFilterDefinition = buildEncryptionFilterDefinition(testKmsFacade, UnresolvedKeyPolicy.PASSTHROUGH_UNENCRYPTED);
+        builder.addToFilterDefinitions(namedFilterDefinition);
+        builder.addToDefaultFilters(namedFilterDefinition.name());
+
+        try (var tester = kroxyliciousTester(builder);
+                var producer = tester.producer(Map.of(ProducerConfig.MAX_REQUEST_SIZE_CONFIG, 2000000));
+                var consumer = tester.consumer()) {
+
+            String largerThanInitialEncryptionBuffer = Strings.repeat("a", RecordEncryption.RECORD_BUFFER_INITIAL_BYTES + 1);
```
Comment (k-wall) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/RecordEncryptionFilterIT.java:146]: nit: Use the JDK rather than Guava java.lang.String#repeat

**Review by k-wall — APPROVED** [review]
lgtm - thanks @robobario
