### PR TITLE
Obtain upstream ApiVersions when proxy is not SASL offloading

### LINKED ISSUE #337: Kroxylicious swallows messages without responding if no filters are configured
**Describe the bug**

If I configure no filters into my config YAML the proxy starts but messages will silently be dropped as Kroxy errors internally when constructing the filter chain.

```
[Thread-0] INFO io.kroxylicious.proxy.internal.net.NetworkBindRequest - Binding <any>:9192
[epollEventLoopGroup-7-1] WARN io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler - Netty caught exception from the frontend: Cannot invoke "java.util.List.stream()" because the return value of "io.kroxylicious.proxy.config.Configuration.filters()" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "io.kroxylicious.proxy.config.Configuration.filters()" is null
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory.createFilters(FilterChainFactory.java:39)
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer.lambda$addHandlers$4(KafkaProxyInitializer.java:166)
	at io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler.channelRead(KafkaProxyFrontendHandler.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```
	
We should handle this more gracefully by either tolerating 0 filters, or exploding at configuration time if we find no filters configured.

### LINKED ISSUE #441: Kroxylicious can fail to proxy older broker versions with newer clients.
**Describe the bug**
If I put Kroxylicious in between a version 3.0.2 broker and a version 3.4.0 client, they fail to communicate. (likely holds true for any broker version <3.2 and any client version >3.2, if there have been any api changes between the two versions)

edit: bug is a bit strong since it's intentional, but still good to have a ticket to address it

**To Reproduce**
1. Run a kafka 3.0.2 broker (likely fails with any broker older than 3.2)
2. Run kroxylicious built from `main` using `kroxylicious/example-proxy-config.yaml`
3. Using a newer Kafka distribution (I used 3.4.0), produce directly to Kafka `bin/kafka-console-producer.sh --topic t1 --bootstrap-server localhost:9092` and observe it working succeeding.
4. Produce to kroxylicious with  `bin/kafka-console-producer.sh --topic t1 --bootstrap-server localhost:9192` and observe errors about failed connections
5. Look in the 3.0.2 kafka distribution at `logs/server.log` to see lots of lines like:
```
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: METADATA, apiVersion: 12, connectionId: 127.0.0.1:9092-127.0.0.1:45216-19, listenerName: ListenerName(PLAINTEXT), principal: User:ANONYMOUS
Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Can't read version 12 of MetadataRequestTopic
```

**Expected behavior**
Kroxylicious should be able to gracefully proxy interactions between newer clients and older brokers.

**Additional context**
This is caused because Kroxylicious is currently handling the generation of the ApiVersions response, [here](https://github.com/kroxylicious/kroxylicious/blob/95291c0f43ec9e0dad0d70e8eb4fa2fdece32bfe/kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java#L196). Using a hardcoded ApiVersions response for a 3.2 broker.

This also means APIs introduced after 3.2 will not be used if the client and proxied broker are >3.2

[This commit ](https://github.com/kroxylicious/kroxylicious/commit/88aa4ea0a466ef77f3e5e2c3a60956e2bb4dffe4)explains why it is like this.

> Add NetFilter abstraction for pluggable connection logic
> NetFilter provides a plugin abstraction for how the connection to a
> backend Kafka cluster happens.
> 
> It can consume information from earlier handler in the Netty pipeline
> including:
> 
> * Network peer information from the TCP layer
> * SNI information from the TLS handshake
> * Client information propagated by HAProxy using the PROXY protocol
> * SASL authentication information from the KafkaAuthnHandler
> 
> Using this a `NetFilter` implementation can decide whether and which
> backend cluster the client should be connected to, and with what
> protocol filters.
> 
> Because clients may send `ApiVersions` requests before any other request
> this means we need to be able to send an `ApiVersions` response from the
> proxy without knowing which backend cluster the client will ultimately
> connect to. For now we're just using a fixed response read from a
> classpath resource, however we should really improve this, but example by
> figuring out an "inclusive response" from a set of backend clusters at
> runtime.
> 
> Note that this means we have decoupled client connection and
> authentication from cluster connection. Therefore bad clients
> without valid credentials have no effect on any cluster.
> 
> Also provided is a `SimpleNetFilter` implementation of the `NetFilter`
> interface, which support a single cluster and a fixed list
> of protocol filters.
> 
> Fixes https://github.com/kroxylicious/kroxylicious/issues/68
> Fixes https://github.com/kroxylicious/kroxylicious/issues/67

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Enhancement / new feature

### Description

If Kroxylicious is not handling SASL offload (currently it never handles SASL offload) then we initiate NetFilter#selectServer if we receive an `ApiVersions` request and buffer the message. After the connect is successful we send the buffered message to the backend. We also install the ApiVersionsFilter if we are not handling SASL offload so that we are intersecting the Kroxylicious supported versions with the upstream versions without further configuration.

ApiVersionsFilter becomes an internal concern, it is no longer available via the BuiltinFilterContributor and is installed into the filter chain automatically by kroxylicious where appropriate.

Also, as a consequence, many tests no longer install any custom filters. This used to throw exceptions but it is now allowed. There could be cases where users want to use Kroxylicious as a proxy with no interception. 

Closes #441
Closes #337

### Additional Context

Why:
Currently Kroxylicious responds with a hardcoded ApiVersions response. This is intentional, to support the proxy handling SASL authentication before we make a connection to the upstream broker, protecting the broker from unauthorized requests and enabling NetFilter to use the authorized id as a criteria for backend server selection. The response is hardcoded to the ApiVersions values for a kafka 3.2 broker.

This means that if we are proxying a broker older than v3.2, Kroxy will be declaring it supports api versions that it doesn't know about, causing errors when you try to use a newer client that supports those newer API versions. Conversely if the backing broker is newer and supports new api versions, the client would be told that the broker only supports v3.2 APIs and the client can't take advantage of new APIs.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by robobario** [comment]
Would be good to add an integration test.

Also, unsure if this is the right change. I see it as more of a delaying tactic to offer a smoother integration with Kafka as long as SASL offload is not offered.

 We could also say we are happy for now with only supporting brokers >3.2 and using APIs at v3.2. Maybe an ugly way that could still support users accessing newer APIs would be to have a configurable level, `virtual cluster abc supports v3.4`.
 
There was also a suggestion in a PR of connecting to all/some brokers in the VirtualCluster to discover their ApiVersions and maintaining these persistent connections to track changes. This might be adequate though there are edge cases around feature flags and broker restarts.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 1]
```diff
@@ -253,6 +266,9 @@ public void initiateConnect(HostPort remote, List<FilterAndInvoker> filters) {
         if (logFrames) {
             pipeline.addFirst("frameLogger", new LoggingHandler("io.kroxylicious.proxy.internal.UpstreamFrameLogger"));
         }
+        if (dp.isAuthenticationOffloadEnabled()) {
```
Comment (k-wall) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:269]: I'm slightly puzzled here.  I was expecting to see the filter unconditionally added when the `isAuthenticationOffloadEnabled` is false.

**Comment by k-wall** [comment]
> Would be good to add an integration test.

+1
maybe mock server test candidate?

+1 Also, unsure if this is the right change. I see it as more of a delaying tactic to offer a smoother integration with Kafka as long as SASL offload is not offered.

I do think this is the right pragmatic step.  

> There was also a suggestion in a PR of connecting to all/some brokers in the VirtualCluster to discover their ApiVersions and maintaining these persistent connections to track changes. 

I was thinking this was only necessary in the SASL offload case.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 1 above)
Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:269]: Doh, the boolean check is backwards. That's right, I wanted it to always be added for the non-offload case.

> If the case where it is true, we've already sent the response anyway.

For the non-SASL-offloading case we will have buffered the api versions request in the `KafkaProxyFrontendHandler` and eventually when the outbound channel is active we forward the buffered message, by then the filters appear to be installed in the pipeline, there is code checking we are in the CONNECTED state at that point and so should have set up the filters. The integration test I've added shows it working okay on the first request.

> I was think ApiVersion filter was becoming an internal concern (like BrokerAddressFilter). Is my mental model wrong?

You are correct, I've made further changes, removing it from all example configurations and the BuiltinFilterContributor, it should be an internal concern.

> aside: Is a Kafka Client allow to request ApiVersions more than once?

Not sure, though I realized that the `ApiVersionsFilter` wasn't being included in the decode predicate, so subsequent requests on the same connection wouldn't have been decoded.

**Comment by robobario** [comment]
Also pushed up a test for a suspicious behaviour of the ApiVersionsFilter. That is that it does not remove unknown ApiKeys returned by the broker. If clients attempted to request these ApiKeys then Kroxylicious would throw an exception in the KafkaRequestDecoder when it's trying to determine what the ApiKey is. I think we should remove filter out unknown ApiKeys, removing them from the response.

File: integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java [hunk 2]
```diff
@@ -52,7 +52,8 @@ public void shouldProxyWhenRunAsStandaloneProcess(KafkaCluster cluster, Admin ad
                 new NewTopic(TOPIC_1, 1, (short) 1),
                 new NewTopic(TOPIC_2, 1, (short) 1))).all().get();
 
-        try (var tester = kroxyliciousTester(withDefaultFilters(proxy(cluster)), new SubprocessKroxyliciousFactory(tempDir));
+        ConfigurationBuilder builder = proxy(cluster);
```
Comment (robobario) [inline integrationtests/src/test/java/io/kroxylicious/proxy/KroxyStandaloneIT.java:55]: hmm removing the `withDefaultFilters` using IDEA must have extracted these variables, will inline them tomorrow

File: integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+import io.kroxylicious.test.client.KafkaClient;
+import io.kroxylicious.test.tester.KroxyliciousConfigUtils;
+import io.kroxylicious.test.tester.MockServerKroxyliciousTester;
+
+import static io.kroxylicious.test.tester.KroxyliciousTesters.mockKafkaKroxyliciousTester;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+/**
+ * For the kafka RPCs that Kroxylicious can intercept, Kroxylicious should only offer API versions
+ * that it can encode/decode using it's version of the kafka-clients lib. It should also only offer API versions
```
Comment (k-wall) [inline integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java:24]:
```suggestion
 * that it can encode/decode using its version of the kafka-clients lib. It should also only offer API versions
```

File: integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+            assertEquals((short) 4, singletonVersion.maxVersion());
+        }
+    }
+
+    private static void givenMockRespondsWithApiVersionsForApiKey(MockServerKroxyliciousTester tester, ApiKeys keys, short minVersion, short maxVersion) {
+        ApiVersionsResponseData mockResponse = new ApiVersionsResponseData();
+        ApiVersionsResponseData.ApiVersion version = new ApiVersionsResponseData.ApiVersion();
+        version.setApiKey(keys.id).setMinVersion(minVersion).setMaxVersion(maxVersion);
+        mockResponse.apiKeys().add(version);
+        tester.setMockResponse(new Response(ApiKeys.API_VERSIONS, (short) 3, mockResponse));
```
Comment (k-wall) [inline integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java:105]: avoiding the magic number
```suggestion
        tester.setMockResponse(new Response(ApiKeys.API_VERSIONS, org.apache.kafka.common.message.ApiVersionsRequestData.HIGHEST_SUPPORTED_VERSION, mockResponse));
```

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 5]
```diff
@@ -253,7 +267,12 @@ public void initiateConnect(HostPort remote, List<FilterAndInvoker> filters) {
         if (logFrames) {
             pipeline.addFirst("frameLogger", new LoggingHandler("io.kroxylicious.proxy.internal.UpstreamFrameLogger"));
         }
-        addFiltersToPipeline(filters, pipeline);
+        final List<FilterAndInvoker> filterAndInvokers = new ArrayList<>();
```
Comment (k-wall) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:270]: we've already got the KafkaProxyInitializer adding internal filters. would the responsibility to add this one better belong there?

**Review by k-wall — APPROVED** [review]

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 5 above)
Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: Missed that, moved it into the Initializer
