### PR TITLE
Fix #1715

### LINKED ISSUE #1715: Allow bootstrapServers instead of bootstrap_servers
**Describe the bug**

VirtualCluster accepted a property called `bootstrap_servers` which is the only place where the configuration uses underscore naming. Every other configurable property is `camelCase`. So let's add support for calling it `bootstrapServers` and use `@JsonAlias("bootstrap_servers")` for backwards compatibility.

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Bugfix

### Description

Fix #1715

### CODE REVIEW

**Review by callaertanthony — APPROVED** [review]

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java [hunk 1]
```diff
@@ -17,7 +18,7 @@
 /**
  * Represents the target (upstream) kafka cluster.
  */
-public record TargetCluster(@JsonProperty(value = "bootstrap_servers", required = true) String bootstrapServers,
+public record TargetCluster(@JsonProperty(value = "bootstrapServers", required = true) @JsonAlias("bootstrap_servers") String bootstrapServers,
```
Comment (k-wall) [inline kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java:21]: We normally add a @deprecated annotation with a since=<ver> value when we deprecated something.  This helps us find things to remove when the time comes.   We can't do that here, but I think adding a comment with the same information would help."

**Review by k-wall — APPROVED** [review]
One nit, but otherwise LGTM.  Thanks @tombentley!

File: kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java (hunk 1 above)
Comment (tombentley) [reply kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/config/TargetCluster.java:21]: It would also be nice to log a warning when someone uses a deprecated property, which `@JsonAlias` doesn't allow. We could use a separate property, which would allow us to use @Deprecated and warn logging.

**Comment by tombentley** [comment]
The sonar fail is about test coverage on new code, and it appears to be incorrect -- the new code is tested by the `ConfigurationTest`. I'm therefore going to merge this.
