### PR TITLE
Fix the 'spec.tls.trustAnchorRef supports referents: configmaps' error when trying to use secret to provide trust for upstream TLS

### LINKED ISSUE #3270: 'spec.tls.trustAnchorRef supports referents: configmaps' when trying to use secret to provide trust (main)
**Describe the bug**

I'm trying to use the feature on main (not released) for providing trust for my upstream from a Secret, rather than a ConfigMap.
I realise our work on #3224 was incomplete. 

**To Reproduce**
1. Follow DEV_GUIDE.md to deploy the operator from main.
2. Run OperatorMain from the IDE
3. Deploy the https://github.com/k-wall/kroxylicious/tree/issue-3270/kroxylicious-operator/packaging/examples/upstream-tls. - the example is tweaked to provide trust from a secret.
4. Run command `kubectl get ks -n my-proxy -o yaml my-cluster`.  Behold the reconciliation error.

```
apiVersion: kroxylicious.io/v1alpha1
kind: KafkaService
metadata:
  annotations:
    kroxylicious.io/referent-checksum: AAAAACi1ChQ
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kroxylicious.io/v1alpha1","kind":"KafkaService","metadata":{"annotations":{},"name":"my-cluster","namespace":"my-proxy"},"spec":{"bootstrapServers":"my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093","nodeIdRanges":[{"end":2,"start":0}],"tls":{"trustAnchorRef":{"key":"ca.pem","kind":"ConfigMap","name":"my-cluster-clients-ca-cert"}}}}
  creationTimestamp: "2026-02-11T14:13:11Z"
  generation: 2
  name: my-cluster
  namespace: my-proxy
  resourceVersion: "3335"
  uid: 1a4b25ee-09e8-41a3-badf-01b6ab060092
spec:
  bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
  nodeIdRanges:
  - end: 2
    start: 0
  tls:
    trustAnchorRef:
      group: ""
      key: ca.pem
      kind: Secret
      name: my-cluster-clients-ca-cert
status:
  conditions:
  - lastTransitionTime: "2026-02-11T14:20:00.532673Z"
    message: 'spec.tls.trustAnchorRef supports referents: configmaps'
    observedGeneration: 2
    reason: ReferencedGroupKindNotSupported
    status: "False"
    type: ResolvedRefs
  observedGeneration: 2
```

**Expected behavior**

The KafkaService should accept the Secret as a source of trust material.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by ShubhamRwt**
### Type of change

- Bugfix

### Description

This PR fixes #3270. This PR refactors the KafkaServiceReonciler and the ResourceUtil class to incorporate the changes for supporting Secret in `TrustAnchorRef` section in upstream tls

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

**Comment by ShubhamRwt** [comment]
@k-wall Hi, can you also try this fix on your end. It works for me

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceBootstrapReconcilerIT.java [hunk 1]
```diff
@@ -145,11 +146,30 @@ void shouldEventuallyResolveOnceTrustAnchorCreated() {
 
     }
 
+    @Test
+    void shouldEventuallyResolveOnceTrustAnchorCreatedSecret() {
```
Comment (k-wall) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceBootstrapReconcilerIT.java]:
```suggestion
    void shouldEventuallyResolveOnceTrustAnchorSecretCreated() {
```

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceBootstrapReconcilerIT.java [hunk 2]
```diff
@@ -129,7 +130,7 @@ void shouldUpdateStatusOnceTlsCertificateSecretDeleted() {
     @Test
     void shouldEventuallyResolveOnceTrustAnchorCreated() {
```
Comment (k-wall) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceBootstrapReconcilerIT.java]:
```suggestion
    void shouldEventuallyResolveOnceTrustAnchorConfigMapCreated() {
```

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceReconcilerTest.java
Comment (k-wall) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceReconcilerTest.java]:
```suggestion
    public static final ConfigMap TRUST_ANCHOR_PEM_CONFIG_MAP = new ConfigMapBuilder()
```

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceReconcilerTest.java [hunk 3]
```diff
@@ -119,6 +119,15 @@ class KafkaServiceReconcilerTest {
             .addToData("ca-bundle.pem", "value")
             .build();
 
+    public static final Secret PEM_SECRET = new SecretBuilder()
```
Comment (k-wall) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/KafkaServiceReconcilerTest.java]:
```suggestion
    public static final Secret TRUST_ANCHOR_PEM_SECRET = new SecretBuilder()
```

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java
Comment (k-wall) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java]: configmaps or secrets

**Review by k-wall — COMMENTED** [review]
I made some suggestions in this PR https://github.com/ShubhamRwt/kroxylicious/pull/11

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java [hunk 4]
```diff
@@ -505,18 +505,26 @@ private static <T extends HasMetadata> boolean isStatusFresh(T resource, Functio
...
                                                                                               String path,
                                                                                               StatusFactory<T> statusFactory) {
-        if (isConfigMap(trustAnchorRef.getRef())) {
-            Optional<ConfigMap> configMapOpt = context.getSecondaryResource(ConfigMap.class, eventSourceName);
-            if (configMapOpt.isEmpty()) {
-                return new ResourceCheckResult<>(statusFactory.newFalseConditionStatusPatch(resource, ResolvedRefs,
-                        Condition.REASON_REFS_NOT_FOUND,
-                        path + ": referenced configmap not found"), List.of());
+        if (isConfigMap(trustAnchorRef.getRef())
+                || (trustAnchorRef.getRef().getKind() != null && isSecret(trustAnchorRef.getRef()))) {
```
Comment (k-wall) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java]: I found the bifurcation a bit displeasing.  I made an alternative suggestion in the PR which keeps the code path more linear - WDYT?

Comment (ShubhamRwt) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java]: I had a look Kieth, the changes looks good to me in the PR. I tried not to refactor the code a lot but the changes you suggested seems more clear to me

**Comment by ShubhamRwt** [comment]
Do the above changes works fine on your end i.e is it now picking key from Secret correctly @k-wall ?

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java (hunk 4 above)
Comment (ShubhamRwt) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java]: I left a comment too on why that code path can have issues

Comment (k-wall) [reply kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ResourcesUtil.java]: we talked on the the PR, I think we are in agreement the change I am suggesting is okay.

File: kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/ResourcesUtilTest.java
Comment (k-wall) [inline kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/ResourcesUtilTest.java:882]: Let's add more cases to this parameterized test to cover secrets providing trust.

Comment (ShubhamRwt) [reply kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/ResourcesUtilTest.java:882]: Sure, I will do that

Comment (ShubhamRwt) [reply kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/ResourcesUtilTest.java:882]: This test is focusing on the VirtualClusterReconciler so we will fix this in a separate PR as discussed on slack

Comment (k-wall) [reply kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/ResourcesUtilTest.java:882]: Ah you are right.  The testing responsibilities don't seem quite right, but let's move on for now.
