### PR TITLE
Fix Sonar warnings: single method call in assertThatThrownBy lambdas (#3619)

### LINKED ISSUE #3619: Only make one method call within each assertThatThrownBy lambda
Sonar is [flagging several usages](https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&rules=java%3AS5778&issueStatuses=OPEN%2CCONFIRMED&id=kroxylicious_kroxylicious) where there are more than one calls within a testing lambda that could throw.

Fix the problems in:
* ConnectionExpirationFilterConfigTest#shouldRejectNegativeMaxAge
* ConnectionExpirationFilterConfigTest#shouldRejectNegativeJitter
* ConnectionExpirationFilterConfigTest#shouldRejectJitterGreaterThanMaxAge
* NettySettingsTest#shouldRejectNegativeShutdownQuietPeriod
* NettySettingsTest#shouldRejectNegativeShutdownTimeout
* NettySettingsTest#shouldRejectNegativeAuthenticatedIdleTimeout
* NettySettingsTest#shouldRejectNegativeUnauthenticatedIdleTimeout

The idea is that we want to unit test that an exception is thrown by a specific method call. If the lambda contains multiple locations that can throw, it is now ambiguous and the test may mislead future readers.

For example in:

```
assertThatThrownBy(() -> new 
ConnectionExpirationFilterConfig(Duration.
ofSeconds(-60), null))
                .isInstanceOf(IllegalArgumentException.class);
```
we intend to test that the `ConnectionExpirationFilterConfig` constructor throws an IllegalArgumentException. However, the test could pass if Duration.ofSeconds threw, giving us false confidence.

The test should have one reason to fail, so that it is clear to the reader what has gone wrong, and prevent misleading results.

The fix is to extract any setup into variables or constants defined outside the lambda, leaving the method call under test as the only call within the lambda.

### PR DESCRIPTION
**Pull request by ZhangDT-sky**
### Type of change

- [ ] Bugfix
- [ ] Enhancement / new feature
- [x] Refactoring
- [ ] Documentation

### Description

Refactored test methods in `ConnectionExpirationFilterConfigTest` and `NettySettingsTest` to ensure only one method call exists within each `assertThatThrownBy` lambda.
Setup calls (like `Duration.ofSeconds`) are now extracted to local variables before the assertion to prevent ambiguous test results.

### Additional Context

Addresses Sonar rule `java:S5778`.
Fixes #3619.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/config/NettySettingsTest.java [hunk 1]
```diff
@@ -20,28 +20,28 @@ class NettySettingsTest {
 
     @Test
     void shouldRejectNegativeShutdownQuietPeriod() {
-        assertThatThrownBy(() -> new NettySettings(Optional.empty(), NEGATIVE, EMPTY, EMPTY, EMPTY))
+        assertThatThrownBy(() -> new NettySettings(EMPTY, NEGATIVE, EMPTY, EMPTY, EMPTY))
```
Comment (SamBarker) [inline kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/config/NettySettingsTest.java]: Urgh, thats annoying `EMPTY` is `Optional<Integer>` so can't be injected here (it doesn't compile). Not 100% sure what the right answer is here, probably `Optional<Duration> EMPTY_DURATION = Optional.empty()` which then gets used here.

Comment (ZhangDT-sky) [reply kroxylicious-runtime/src/test/java/io/kroxylicious/proxy/config/NettySettingsTest.java]: I’ve fixed this now.  
You were right: the first `NettySettings` parameter is `Optional<Integer>`, so I split the empties in `NettySettingsTest` into typed values (`EMPTY_INT` and `EMPTY_DURATION`) and passed them to the correct argument positions.

**Comment by SamBarker** [comment]
I'm guessing from `D:\wookspace` your running on windows. I don't know if anyone else has tried building or running on windows. I don't think we have been very careful about path separators. Generally assuming a unix like runtime target. 

Let us know if there are issues with Windows.

**Comment by ZhangDT-sky** [comment]
@SamBarker  
😅 Yep, that was my mistake — I accidentally leaked a local Windows path in the commit message while amending for DCO, and I’ve fixed that message now.

Thanks for the heads-up. I’ll treat Unix-like environments as the target and will flag any Windows-specific path separator/build issues if I run into them.
