### PR TITLE
[System Tests] Fixed sporadic error in RestartKafkaBroker test

### LINKED ISSUE #1520: [System Tests] RestartKafkaBrokers test is reporting an error many times
**Describe the bug**
The RestartKafkaBrokers test is reporting an error because the broker is not restarted as expected, but it is out of scope the test.

**To Reproduce**
Run the RestartKafkaBrokers test

**Expected behavior**
The broker should be restarted successfully. If this is something that is happening a lot I'd suggest to be less restricted about checking if it is restarted successfully or not, we just want a broker to be removed and check that the messages are still being received.

**YAML files and logs**

```
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [300000] milliseconds for [Pod] with name:[my-cluster-kafka-0] in namespace [kafka].

	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:946)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:98)
	at io.kroxylicious.systemtests.utils.KafkaUtils.restartBroker(KafkaUtils.java:126)
	at io.kroxylicious.systemtests.steps.KafkaSteps.restartKafkaBroker(KafkaSteps.java:85)
	at io.kroxylicious.systemtests.KroxyliciousST.restartKafkaBrokers(KroxyliciousST.java:96)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

[KroxyliciousST_restartKafkaBrokers_cluster_dump_2024_09_20_08_39_08.zip](https://github.com/user-attachments/files/17073198/KroxyliciousST_restartKafkaBrokers_cluster_dump_2024_09_20_08_39_08.zip)

**Additional context**

### PR DESCRIPTION
**Pull request by franvila**
### Type of change

- Bugfix

### Description

The null checking has been replaced to avoid sporadic errors due to a race condition (sometimes null object is not detected because is faster than the code).

### Additional Context

Fixes #1520 

### Checklist

- [x] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [x] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [x] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Comment by franvila** [comment]
@strimzi-ci run system tests

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java [hunk 1]
```diff
@@ -123,7 +122,6 @@ public static boolean restartBroker(String deployNamespace, String clusterName)
             throw new KubeClusterException.NotFound("Kafka cluster name not found!");
         }
         kubeClient().getClient().pods().inNamespace(deployNamespace).withName(podName).withGracePeriod(0).delete();
-        kubeClient().getClient().pods().inNamespace(deployNamespace).withName(podName).waitUntilCondition(Objects::isNull, 5, TimeUnit.MINUTES);
```
Comment (SamBarker) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java:126]: Perhaps is null was the wrong check but waiting for something to signal the teardown feels right as otherwise waitForDeployment can pass on the only pod being active, I think.

Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java:126]: You are right, I have missed the possibility of `delete` method to fail and then the following wait won't be taken into account because it is already running. I'll add another check to be sure the pod is null or at least the status is not running, to wait later to be running again.

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Comment by franvila** [comment]
@strimzi-ci run system tests

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/DeploymentUtils.java [hunk 2]
```diff
@@ -158,6 +158,22 @@ public static boolean checkLoadBalancerIsWorking(String namespace) {
...
 
+    /**
+     * Wait for deployment to be restarted.
+     *
+     * @param namespaceName the namespace name
+     * @param podName the pod name
+     * @param timeout the timeout
+     */
+    public static void waitForDeploymentToBeRestarted(String namespaceName, String podName, Duration timeout) {
+        await().alias("await pod to be deleted or in non-running phase")
```
Comment (k-wall) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/DeploymentUtils.java:169]: This is racey.   If the pod is restarted quickly, the client (the test) may never see if pod in the absent or not running state, so the test will fail spuriously.

A safe approch is to rely on the fact that the replacement pod will have a new  `metadata.Uid`.  Record the `uid` before initiating the restart, then await for the pod to exist and have a new `uid`.  I believe that approach will avoid the race condition.

Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/DeploymentUtils.java:169]: This is what I had before Sam's comment:
```
DeploymentUtils.waitForDeploymentRunning(deployNamespace, podName, Duration.ofMinutes(5));
return !Objects.equals(podUid, getPodUid(deployNamespace, podName));
```
We already check for the pod `uid`. So I will leave it as it was.

**Comment by franvila** [comment]
@strimzi-ci run system tests

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java (hunk 1 above)
Comment (SamBarker) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java:126]: I think we should expand the wait condition to pass if the pod is either in `Succeeded` (maybe `Failed` should be considered ok too) or is `null` based on https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ 

Though reading about [forced termination](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination-forced) makes me think part of the problem is using `0` grace period. As that deletes the pod from the API server without waiting for cleanup.

Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java:126]: In the other comment from Keith, we realized that we are checking the `Uid` of the pod as well, so I believe with this two checkings (pod is running and new pod has a different uid) is enough to assure that the pod has been restarted.

Comment (SamBarker) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java:126]: Yeah I know, but only after 5 mins of waiting .

Ok let's merge this and see if it stops being flaky.

**Review by SamBarker — APPROVED** [review]

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java (hunk 1 above)
Comment (franvila) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java:126]: > Though reading about [forced termination](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination-forced) makes me think part of the problem is using `0` grace period. As that deletes the pod from the API server without waiting for cleanup.

Reading this article for forcing the termination, I read this lines that are what we want:
```
When a force deletion is performed, the API server does not wait for confirmation from the kubelet
 that the Pod has been terminated on the node it was running on. It removes the Pod in the API 
immediately so a new Pod can be created with the same name
```

Comment (SamBarker) [reply kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/utils/KafkaUtils.java:126]: Yeah it's deleting it from the API server without waiting to make sure it gets deleted from the node, it could stay running indefinitely. Though unreported by the api server so maybe not our problem
