### PR TITLE
Fix #1436 : remove forwardPartialRequests feature of record validation filter

### LINKED ISSUE #1436: Record Validation Filter: zero-ack produce requests combined with partial batch forwarding causes memory leak and OOM
**Describe the bug**

If I have a RecordValidationFilter with `forwardPartialRequests` enabled, and a producer that is producing lots of zero-ack produce requests we are leaking memory.

1. We put data in a correlation map about the failed topic partitions and then expect to augment them back into the response.
2. In the zero-ack produce request case there is no response to augment and the correlated data sits in the map forever
3. This can grow until OOM

**To Reproduce**

1. run up a kafka broker on 9092

Configure a filter that blocks null values on all topics with forwardPartialRequests enabled

```yaml
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: localhost:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9192
    logNetwork: false
    logFrames: false
filters:
- type: RecordValidation
  config:
      rules: []
      defaultRule:
        valueRule:
          allowNulls: false                                                 
          allowEmpty: true
      forwardPartialRequests: true
```

hammer the proxy with zero-ack produce requests where some partitions contain only invalid records and some partitions contain only valid records to prompt the partial request forwarding logic to kick in.

```
package org.example;

import org.apache.kafka.clients.admin.Admin;
import org.apache.kafka.clients.admin.AdminClientConfig;
import org.apache.kafka.clients.admin.NewTopic;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;

import java.util.List;
import java.util.Map;

public class Main {
    public static void main(String[] args) {
        Admin admin = Admin.create(Map.of(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092"));
        int numPartitions = 20;
        String topic = "test5";
        try {
            admin.createTopics(List.of(new NewTopic(topic, numPartitions, (short) 1))).all().get();
        } catch (Exception e) {
            System.out.println(e);
        }
        KafkaProducer<String, String> producer = new KafkaProducer<>(Map.of(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9192", ProducerConfig.LINGER_MS_CONFIG, 1000, ProducerConfig.ACKS_CONFIG, "0"), new StringSerializer(), new StringSerializer());
        int i = 0;
        while(true) {
            int partition = i++ % numPartitions;
            producer.send(new ProducerRecord<>(topic, partition, "key", partition % 2 == 0 ? null : "it's present"));
        }
    }
}
```

observe Kroxylicious memory in jconsole or equivalent head to the heap limit and requests eventually start to slow down to a crawl:
Screenshot from 2024-08-16 15-45-09

**Expected behavior**

Not a big old memory leak, that's for sure.

It's unclear what record validation bejaviour should be in the context of zero-ack requests. The producer is firing and forgetting, with no response from the broker expected. We still want to prevent the bad data hitting the broker. Maybe we need some metrics to let the user know we are preventing writes.

We also need to ensure we do not respond to zero-ack requests. Currently we respond from the filter if we invalidate the whole ProduceRequest because all topic-partitions contain invalid records or we are transactional and any record in the request was invalid.

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Why: in the commentary of #1436 it was concluded that the inclusion of `forwardPartialRequests` option in the RecordValidation filter was an error. The problem being that if a client is sending incorrect data, then stopping immediately is the safe course of action.   Accepting some data and rejecting other is likely to lead to more harm than good.

We said we wanted to drop the feature (without deprecation).

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Update documentation
- [ ] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/config/ValidationConfig.java [hunk 1]
```diff
@@ -7,89 +7,23 @@
...
-        return Objects.hash(forwardPartialRequests, rules, defaultRule);
-    }
+public record ValidationConfig(@JsonProperty("rules") List<TopicMatchingRecordValidationRule> rules,
+                               @JsonProperty("defaultRule") RecordValidationRule defaultRule) {
 
     @Override
     public String toString() {
         return "ValidationConfig{" +
-                "forwardPartialRequests=" + forwardPartialRequests +
                 ", rules=" + rules +
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/config/ValidationConfig.java:27]:
```suggestion
                "rules=" + rules +
```

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java [hunk 2]
```diff
@@ -70,31 +68,21 @@ public CompletionStage<RequestFilterResult> onProduceRequest(short apiVersion, R
...
-            LOGGER.debug("some topic-partitions contained invalid data: {}, forwarding valid topic-partitions", result);
-            request.topicData().removeIf(topicProduceData -> result.isAllPartitionsInvalid(topicProduceData.name()));
-            for (ProduceRequestData.TopicProduceData topicDatum : request.topicData()) {
-                topicDatum.partitionData().removeIf(partitionProduceData -> !result.isPartitionValid(topicDatum.name(), partitionProduceData.index()));
-            }
-            correlatedResults.put(header.correlationId(), result);
-            return context.forwardRequest(header, request);
-        }
         else {
             LOGGER.debug("some topic-partitions for transactional request with id: {}, contained invalid data: {}, invalidation entire request",
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java:87]: our else branch is no longer a transactional request (and as commented above the if-else can be removed now that there is only one possible outcome)

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java [hunk 3]
```diff
@@ -70,31 +68,21 @@ public CompletionStage<RequestFilterResult> onProduceRequest(short apiVersion, R
...
             else {
                 return context.forwardRequest(header, request);
             }
         });
     }
 
-    private CompletionStage<RequestFilterResult> handleInvalidTopicPartitions(RequestHeaderData header, ProduceRequestData request, FilterContext context,
+    private CompletionStage<RequestFilterResult> handleInvalidTopicPartitions(ProduceRequestData request, FilterContext context,
                                                                               ProduceRequestValidationResult result) {
         if (result.isAllTopicPartitionsInvalid()) {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java:81]: both branches now do the same thing, previously this was a guard to prevent going into the partial response logic if all TPs were invalid. Now it doesn't have a purpose, except maybe producing a more readable log. The if-else should be removed.

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java [hunk 4]
```diff
@@ -70,31 +68,21 @@ public CompletionStage<RequestFilterResult> onProduceRequest(short apiVersion, R
...
             LOGGER.debug("all topic-partitions for request contained invalid data: {}", result);
             ProduceResponseData response = invalidateEntireRequest(request, result);
             return context.requestFilterResultBuilder().shortCircuitResponse(response).completed();
         }
-        // do not forward partial produce data if request is transactional because the whole produce must eventually succeed or fail together
-        else if (request.transactionalId() == null && forwardPartialRequests) {
-            LOGGER.debug("some topic-partitions contained invalid data: {}, forwarding valid topic-partitions", result);
-            request.topicData().removeIf(topicProduceData -> result.isAllPartitionsInvalid(topicProduceData.name()));
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java:91]: `isAllPartitionsInvalid(String topic)` is now dead code

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java [hunk 5]
```diff
@@ -70,31 +68,21 @@ public CompletionStage<RequestFilterResult> onProduceRequest(short apiVersion, R
...
-            for (ProduceRequestData.TopicProduceData topicDatum : request.topicData()) {
-                topicDatum.partitionData().removeIf(partitionProduceData -> !result.isPartitionValid(topicDatum.name(), partitionProduceData.index()));
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java:93]: `isPartitionValid(String topicName, int partitionIndex)` is now dead code

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/config/ValidationConfig.java [hunk 6]
```diff
@@ -7,89 +7,23 @@
...
 
 /**
  * Configuration for Produce Request validation. Contains a description of the rules for validating
  * the data for all topic-partitions with a ProduceRequest and how to handle partial failures (where
  * some topic-partitions are valid and others are invalid within a single ProduceRequest)
+ *
+ * @param rules describes a list of rules, associating topics with some validation to be applied to produce data for that topic
+ * @param defaultRule the default validation rule to be applied when no rule is matched for a topic within a ProduceRequest
  */
-public class ValidationConfig {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/config/ValidationConfig.java:20]: nice!

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java [hunk 7]
```diff
@@ -48,20 +48,18 @@
 public class RecordValidationFilter implements ProduceRequestFilter, ProduceResponseFilter {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/RecordValidationFilter.java:48]: javadoc on class has a paragraph about forwarding partial data

File: kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/config/ValidationConfig.java [hunk 8]
```diff
@@ -7,89 +7,23 @@
...
 
 import java.util.List;
-import java.util.Objects;
 
-import com.fasterxml.jackson.annotation.JsonCreator;
 import com.fasterxml.jackson.annotation.JsonProperty;
 
 /**
  * Configuration for Produce Request validation. Contains a description of the rules for validating
  * the data for all topic-partitions with a ProduceRequest and how to handle partial failures (where
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-record-validation/src/main/java/io/kroxylicious/proxy/filter/validation/config/ValidationConfig.java:15]: the bit about handling partial failures can be removed

**Review by robobario — APPROVED** [review]
LGTM with remaining dead code/docs purged

**Comment by k-wall** [comment]
@robobario thanks @robobario,   I've removed the last of the dead code and corrected the comments.   Please take another look.

**Review by robobario — APPROVED** [review]
LGTM
