### PR TITLE
Fix #3003

### LINKED ISSUE #3003: OffsetFetchGroupBatchingEnforcement can thrown NPE
**Describe the bug**

If I fix #3002, I then notice running:

```
 kafka-consumer-groups --bootstrap-server localhost:9192 --command-config file.properties --describe --group kwall1
```

causes the following WARN to be logged within the proxy.

```
2025-12-04 18:16:52 WARN  <multiThreadIoEventLoopGroup-5-14> io.kr.pr.in.FilterHandler - 355b4a55-72ba-471f-a6df-9e66263f0c67: Filter 'request' for authz OFFSET_FETCH ended exceptionally - closing connection. Cause message java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.apache.kafka.common.message.OffsetFetchRequestData$OffsetFetchRequestGroup.topics()" is null
```

The issue is the enforcement coding isn't taking into account that the topics array within OffsetFetch is nullable (`nullableVersions`).

```json
      { "name": "Topics", "type": "[]OffsetFetchRequestTopics", "versions": "8+", "nullableVersions": "8+",
        "about": "Each topic we would like to fetch offsets for, or null to fetch offsets for all topics.", "fields": [] )
```

**To Reproduce**
1. Configure kroxylicious like this ...
2. Run command '....'
3. See error

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Bugfix

### Description

Fixes #3003. This gets a bit complicated. 
* The request schema switched from single-group to batched at version 8. 
* This means there are two places where `topics` can be null (indicating "all topics"): at the top level for older versions, and in each group when a version uses batches
* When an all topics request is used we have to apply authorization on the response path.
* But `CompositeEnforcement`, which was how we we separating the version-dependent logic into two classes, didn't support intercepting the response. That's because (as per https://github.com/kroxylicious/kroxylicious/issues/2916) the Filter API doesn't provide convenient access to the api version in the response. 
* I _could_ have fitted `CompositeEnforcement` out with state tracking, so it stored the request version to be used later in the response handler, so that it could decide which real enforcement to call. But this felt really ugly, given that each of those real enforcement classes each had its own correlationId state mapping for the response merging logic. 
* Those two response classes were each going to need very similar code to handling the all topics case, so while in theory using `CompositeEnforcement` enabled a clean separation of concerns, I think the truth is that that's just often not possible, either in the `OffsetFetch` case or in general. For example, this was the only API where we'd been able to use `CompositeEnforcement`, but there were a number of other APIs where we'd also had to deal with non-version dependent complexity.
* So in the end I decided it was simplest to merge the two classes and let them use common code for handling the all topics case. Since this was the only API which was using `CompositeEnforcement`, I have removed it.

### CODE REVIEW

File: kroxylicious-filters/kroxylicious-authorization/src/main/java/io/kroxylicious/filter/authorization/OffsetFetchEnforcement.java [hunk 1]
```diff
@@ -0,0 +1,337 @@
...
+    @Override
+    short maxSupportedVersion() {
+        return LAST_VERSION_WITH_TOPIC_NAMES;
+    }
+
+    private static boolean isAllTopics(RequestHeaderData header,
+                                       OffsetFetchRequestData request) {
+        boolean batched = header.requestApiVersion() >= FIRST_VERSION_USING_GROUP_BATCHING;
+        if (batched) {
+            return request.groups().stream()
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-authorization/src/main/java/io/kroxylicious/filter/authorization/OffsetFetchEnforcement.java]: unfortunately, the shape of the batched API gives us the possibility for a multiple group query where
- one or more groups specifies named topics
- one or more groups uses topics null (all semantics)

If you submit a request like this, isAllTopics will be false, and we'll NPE later on.  

If you argue that no reasonable client would ever use the API in that way (the use-cases are quite distinct, after all), let's fail the request up front.

**Review by k-wall — APPROVED** [review]
One niggle to answer, but otherwise LGTM

File: kroxylicious-filters/kroxylicious-authorization/src/main/java/io/kroxylicious/filter/authorization/OffsetFetchEnforcement.java (hunk 1 above)
Comment (tombentley) [reply kroxylicious-filters/kroxylicious-authorization/src/main/java/io/kroxylicious/filter/authorization/OffsetFetchEnforcement.java]: Great point, thank you. 

I guess it would be simplest to just do authz on the response path. That should be safe because offset fetch should be side-effect free. It would simplify the code because all cases would then be handled in the same way. 

I'll look at doing this next week.

**Review by robobario — APPROVED** [review]
LGTM

File: kroxylicious-filters/kroxylicious-authorization/src/main/java/io/kroxylicious/filter/authorization/OffsetFetchEnforcement.java (hunk 1 above)
Comment (k-wall) [reply kroxylicious-filters/kroxylicious-authorization/src/main/java/io/kroxylicious/filter/authorization/OffsetFetchEnforcement.java]: > I guess it would be simplest to just do authz on the response path. 

I'm not sure.   That would mean sometimes the authz layer lets requests for resources that are denied through to the broker and other cases not.  That's make reasoning about the authz decisions the broker will be asked to make hard.    Perhaps always filtering on both request and response path is a clearer business rule?
