### PR TITLE
[SystemTests] added preload images to avoid issues when running the tests

### LINKED ISSUE #3374: NonJVMClientST failed due to test-client pod not starting after 1 minute
https://github.com/kroxylicious/kroxylicious/actions/runs/22557614107/job/65338284517?pr=3358

> org.awaitility.core.ConditionTimeoutException: Condition with alias 'await pod to leave pending phase' didn't complete within 1 minutes because lambda expression in io.kroxylicious.systemtests.utils.DeploymentUtils expected the predicate to return <true> but it returned <false> for input of <Optional[Pending]>.
> 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
> 	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
> 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
> 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:712)
> 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:729)
> 	at io.kroxylicious.systemtests.utils.DeploymentUtils.waitForLeavingPendingPhase(DeploymentUtils.java:175)
> 	at io.kroxylicious.systemtests.utils.DeploymentUtils.waitForPodRunSucceeded(DeploymentUtils.java:189)
> 	at io.kroxylicious.systemtests.steps.KafkaSteps.createTopic(KafkaSteps.java:94)
> 	at io.kroxylicious.systemtests.steps.KafkaSteps.createTopic(KafkaSteps.java:61)
> 	at io.kroxylicious.systemtests.NonJVMClientsST.produceConsumeMessagesWithClients(NonJVMClientsST.java:104)

Looking at the describe of the pod in the [dumped logs](https://github.com/kroxylicious/kroxylicious/actions/runs/22557614107/artifacts/5714256342):

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  63s   default-scheduler  Successfully assigned non-j-v-m-client-st-6e7a71/admin-client-cli-create-qmn68 to minikube
  Normal  Pulling    63s   kubelet            spec.containers{admin}: Pulling image "quay.io/strimzi-test-clients/test-clients:0.12.0-kafka-4.1.0"
```

Maybe it was just a slow pull of quay.io/strimzi-test-clients/test-clients:0.12.0-kafka-4.1.0

### PR DESCRIPTION
**Pull request by franvila**
### Type of change

- Bugfix

### Description

Sometimes, the strimzi-test-client image is not loaded on time (1 minute) because it is a little bit heavy (around 300 MB), so we have implemented the same solution as [in the Operator ITs](https://github.com/kroxylicious/kroxylicious/blob/3bafb913405c0b4a4902197f9aca05c6fa240283/kroxylicious-operator/src/test/java/io/kroxylicious/kubernetes/operator/OperatorTestUtils.java#L64).

To avoid any issue with another client image, we have added the preload for all images.

### Additional Context

Fixes #3374 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [x] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [x] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

**Comment by SamBarker** [comment]
Thank you for this fix, Fran — flaky tests caused by slow image pulls are really frustrating and this is a smart approach to address it. The design of adding `preloadImage()` to the `KafkaClient` interface is clean and the per-client overrides make sense (particularly the `KafClient` one where you can't use a shell command because of the `scratch`-based image — nice catch).

One suggestion on `NonJVMClientsST.preloadImages()`. I can see what you're going for — you want to preload all the images this test actually uses, not just the one selected by the `KAFKA_CLIENT` env var. That's the right instinct.

The reflection approach works, but it's a bit fragile: it relies on the undocumented convention that concrete client factory methods in `KafkaClients` don't start with `get`, and it will always try to preload kcat even on non-x86 architectures where `clientCombinations()` deliberately excludes it.

Conveniently, you already have a method that knows exactly which clients this test needs and handles the architecture conditional: `clientCombinations()`. You could drive the preload directly from it:

```java
private void preloadImages() {
    clientCombinations()
        .flatMap(args -> Arrays.stream(args.get()))
        .filter(KafkaClient.class::isInstance)
        .map(KafkaClient.class::cast)
        .distinct()
        .forEach(KafkaClient::preloadImage);
}
```

This way the preload list is always in sync with what the test actually runs, and kcat is only preloaded on architectures where it's used.

File: kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/clients/KafClient.java [hunk 1]
```diff
@@ -63,12 +63,29 @@ public KafClient() {
...
         this.deployNamespace = namespace;
         return this;
     }
 
+    @Override
+    public void preloadImage() {
+        // kaf does not support run an image with a command (it is built using scratch), so we need to launch it without any
+        String image = getImage();
+        LOGGER.info("Preloading Test Kafka Client Image from {}", image);
+        var pod = kubeClient().getClient().run().withName("preload-operand-image")
```
Comment (SamBarker) [inline kroxylicious-systemtests/src/main/java/io/kroxylicious/systemtests/clients/KafClient.java:82]: nit: the fixed name means we can't re-load in parallel I think thats fine in the STs right now but we should probably adjust at some point.
