### PR TITLE
Fix #671: release fails to replace kroxylicious-api.version in BOM

### LINKED ISSUE #671: release fails to replace kroxylicious-api.version in BOM
**Describe the bug**

The BOM has a maven property [`kroxylicious-api.version`](https://github.com/kroxylicious/kroxylicious/blob/450f49e9f75ac331f72b971837def1278e3523d8/kroxylicious-bom/pom.xml#L25) which is set to a value, `0.3.0-SNAPSHOT.`  There's nothing in the release process that actually sets that variable to the released version.

There is a step in the [`release-api.sh`](https://github.com/kroxylicious/kroxylicious/blob/450f49e9f75ac331f72b971837def1278e3523d8/scripts/release-api.sh#L26) but the capitalisation/punctuation of that variable is different `kroxyliciousApi.version`.

The intent here is not clear.   Do we really mean to have two separate variables?  

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

As reported by #671, the release script fails to relace  kroxylicious-api.version in the pom of the BOM.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: scripts/release-api.sh [hunk 1]
```diff
@@ -23,7 +23,7 @@ fi
 echo "Setting API version to ${RELEASE_API_VERSION}"
 mvn -q versions:set -DnewVersion="${RELEASE_API_VERSION}" -DprocessAllModules=true -pl :kroxylicious-bom,${API_MODULES} -DgenerateBackupPoms=false
 mvn -q clean install -Pquick -pl :kroxylicious-bom,${API_MODULES}  #quick sanity check to ensure the API modules still build
```
Comment (SamBarker) [inline scripts/release-api.sh:25]: Not actually part of your PR but maybe this should be `mvn clean verify` instead of `install`

**Review by SamBarker — APPROVED** [review]
LGTM

File: scripts/release-api.sh (hunk 1 above)
Comment (k-wall) [reply scripts/release-api.sh:25]: I think you are right. I can fix this as part #672
