### PR TITLE
Tolerate multiple messages being read from client during connection

### LINKED ISSUE #513: Kroxylicious throws an Exception if multiple messages are sent to it while connecting to upstream
**Describe the bug**
While reproducing #505 I modified the test client to send multiple messages to Kafka. This resulted in the KafkaProxyFrontendHandler throwing an error because it read another message from the channel while in the CONNECTING state.

**To Reproduce**
1. Run kafka and kroxylicious
2. install netcat

`AAAANAASAAMAAAAAABBjb25zb2xlLXByb2R1Y2VyABJhcGFjaGUta2Fma2EtamF2YQYzLjQuMAA=` is a base64d ApiVersions request. We send it twice to provoke an error
```
base64 -d - <<<AAAANAASAAMAAAAAABBjb25zb2xlLXByb2R1Y2VyABJhcGFjaGUta2Fma2EtamF2YQYzLjQuMAA=AAAANAASAAMAAAAAABBjb25zb2xlLXByb2R1Y2VyABJhcGFjaGUta2Fma2EtamF2YQYzLjQuMAA= | nc -x  127.0.0.1 9192
Sent 112 bytes to the socket
00000000  00 00 00 34  00 12 00 03  00 00 00 00  00 10 63 6F  ...4..........co
00000010  6E 73 6F 6C  65 2D 70 72  6F 64 75 63  65 72 00 12  nsole-producer..
00000020  61 70 61 63  68 65 2D 6B  61 66 6B 61  2D 6A 61 76  apache-kafka-jav
00000030  61 06 33 2E  34 2E 30 00  00 00 00 34  00 12 00 03  a.3.4.0....4....
00000040  00 00 00 00  00 10 63 6F  6E 73 6F 6C  65 2D 70 72  ......console-pr
00000050  6F 64 75 63  65 72 00 12  61 70 61 63  68 65 2D 6B  oducer..apache-k
00000060  61 66 6B 61  2D 6A 61 76  61 06 33 2E  34 2E 30 00  afka-java.3.4.0.
```
netcat terminates without a response and the Kroxylicious logs contain.
```
[epollEventLoopGroup-5-1] WARN io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler - Netty caught exception from the frontend: Unexpected channelRead() message of class io.kroxylicious.proxy.frame.DecodedRequestFrame, state=CONNECTING
java.lang.IllegalStateException: Unexpected channelRead() message of class io.kroxylicious.proxy.frame.DecodedRequestFrame, state=CONNECTING
	at io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler.illegalState(KafkaProxyFrontendHandler.java:144)
	at io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler.channelRead(KafkaProxyFrontendHandler.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
``` 

If you run it against kafka you get:

```
base64 -d - <<<AAAANAASAAMAAAAAABBjb25zb2xlLXByb2R1Y2VyABJhcGFjaGUta2Fma2EtamF2YQYzLjQuMAA=AAAANAASAAMAAAAAABBjb25zb2xlLXByb2R1Y2VyABJhcGFjaGUta2Fma2EtamF2YQYzLjQuMAA= | nc -x  127.0.0.1 9092
Sent 112 bytes to the socket
00000000  00 00 00 34  00 12 00 03  00 00 00 00  00 10 63 6F  ...4..........co
... snip ...
00000060  61 66 6B 61  2D 6A 61 76  61 06 33 2E  34 2E 30 00  afka-java.3.4.0.
...snip...<=ABReceived 446 bytes from the socket
00000000  00 00 01 BA  00 00 00 00  00 00 3D 00  00 00 00 00  ..........=.....
... snip ...
000001B0  00 00 00 01  01 08 00 00  00 00 00 00  00 00        ..............  
...snip...<=ABReceived 446 bytes from the socket
00000000  00 00 01 BA  00 00 00 00  00 00 3D 00  00 00 00 00  ..........=.....
... snip ...
000001B0  00 00 00 01  01 08 00 00  00 00 00 00  00 00        ..............  
```

**Expected behavior**
The behaviour should match Kafka, we should be able to send multiple messages to Kroxylicious before the backend connection is established and Kroxylicious should proxy and filter both messages.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Enqueue further messages handled by KafkaProxyFrontendHandler while it is in the CONNECTING or CONNECTED state before it has received the OUTBOUND_ACTIVE signal from the outbound channel. Then write them all to the outbound when it becomes active and null out the queue.

Resolves #513

### Additional Context

It is possible for clients to send multiple messages to the broker immediately. In this case, even though we try to disable autoread of the inbound channel we can still read multiple messages from the socket and have to handle multiple messages while we are establishing the connection to upstream.

The Kafka Broker handles this case fine so we should too.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 1]
```diff
@@ -84,10 +85,12 @@ public class KafkaProxyFrontendHandler
     private String sniHostname;
 
     private ChannelHandlerContext inboundCtx;
-    // The message buffered while we connect to the outbound cluster
-    // There can only be one such because auto read is disabled until outbound
+
+    // Messages buffered while we connect to the outbound cluster
+    // The size should be limited because auto read is disabled until outbound
```
Comment (robobario) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:90]: Note I haven't put any depth limit on this because we disable inbound autoread, it should only be filled with as many messages as are pulled in from the socket by the initial read.

Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:90]: We could opt to put some limit on this though.

File: integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java [hunk 2]
```diff
@@ -384,6 +384,23 @@ void requestFiltersCanRespondWithoutProxyingRespondsInCorrectOrder() throws Exce
...
+        try (var tester = mockKafkaKroxyliciousTester(s -> proxy(s).addToFilters(new FilterDefinitionBuilder("RejectingCreateTopic").build()));
+                var client = tester.simpleTestClient()) {
+            tester.addMockResponseForApiKey(new ResponsePayload(METADATA, METADATA.latestVersion(), new MetadataResponseData()));
+            Request requestA = new Request(METADATA, METADATA.latestVersion(), "clientA", new MetadataRequestData());
+            Request requestB = new Request(METADATA, METADATA.latestVersion(), "clientB", new MetadataRequestData());
+            var futureA = client.get(requestA);
+            var futureB = client.get(requestB);
+            Response responseA = futureA.get(10, TimeUnit.SECONDS);
+            Response responseB = futureB.get(10, TimeUnit.SECONDS);
+            assertThat(responseA.payload()).isNotNull();
```
Comment (robobario) [inline integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java:399]: should add some way of disambiguating responseA and responseB, maybe use different request types

File: integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java [hunk 3]
```diff
@@ -384,6 +384,23 @@ void requestFiltersCanRespondWithoutProxyingRespondsInCorrectOrder() throws Exce
         }
     }
 
+    @Test
+    void clientsCanSendMultipleMessagesImmediately() throws Exception {
```
Comment (robobario) [inline integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java:388]: note that there are a couple of other integration tests that call `getSync` on the test client which was a workaround for this behaviour. However, it isn't as straightforward as just removing those calls, the test client doesn't give a guarantee that the messages will be sent in the order we call `client.get` since we are using chained futures, the initial messages are sent in an unexpected order. I didn't want to dig into it in this PR.

File: integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java [hunk 4]
```diff
@@ -384,6 +384,24 @@ void requestFiltersCanRespondWithoutProxyingRespondsInCorrectOrder() throws Exce
...
+            tester.addMockResponseForApiKey(new ResponsePayload(METADATA, METADATA.latestVersion(), new MetadataResponseData()));
+            tester.addMockResponseForApiKey(new ResponsePayload(API_VERSIONS, API_VERSIONS.latestVersion(), new ApiVersionsResponseData()));
+            Request requestA = new Request(METADATA, METADATA.latestVersion(), "clientA", new MetadataRequestData());
+            Request requestB = new Request(API_VERSIONS, API_VERSIONS.latestVersion(), "clientB", new ApiVersionsRequestData());
+            var futureA = client.get(requestA);
+            var futureB = client.get(requestB);
+            Response responseA = futureA.get(10, TimeUnit.SECONDS);
+            Response responseB = futureB.get(10, TimeUnit.SECONDS);
+            assertThat(responseA.payload()).isNotNull().extracting(ResponsePayload::apiKeys).isEqualTo(METADATA);
+            assertThat(responseB.payload()).isNotNull().extracting(ResponsePayload::apiKeys).isEqualTo(API_VERSIONS);
```
Comment (SamBarker) [inline integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java:401]: I can see how this asserts two successful sends to the cluster, but I'm not seeing how this asserts that the requests didn't queue up or block. 

How did the old behaviour manifest?

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 5]
```diff
@@ -84,10 +85,12 @@ public class KafkaProxyFrontendHandler
...
     // channel activation
-    private Object bufferedMsg;
+    private List<Object> bufferedMsgs = new ArrayList<>();
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:92]: Would it be worth wrapping this in a class? 

I was wondering about the benefits of making this lazily allocated and then conditional handling that might be needed later. Which lead me to thinking about separation of concerns and to thinking that buffering might not really be a concern for the `KafkaProxyFrontendHandler`. Or maybe more accurately that its not just a concern of the KafkaProxyFrontendHandler

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 6]
```diff
@@ -212,22 +217,21 @@ else if ((state == State.START
                     && msg instanceof RequestFrame) {
                 bufferMsgAndSelectServer(msg);
             }
+            else if (state == State.CONNECTING || state == State.CONNECTED) {
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: I get that this is consistent with how the other guard conditions are done, but I think I'd like to see them all extracted as methods. e.g. `shouldBufferFrame` or `shouldBufferMessage`

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java [hunk 7]
```diff
@@ -212,22 +217,21 @@ else if ((state == State.START
...
-        if (bufferedMsg != null) {
-            // Single buffered message assertion failed
-            throw illegalState("Already have buffered msg");
-        }
         state = State.CONNECTING;
         // But for any other request we'll need a backend connection
         // (for which we need to ask the filter which cluster to connect to
         // and with what filters)
-        this.bufferedMsg = msg;
+        this.bufferedMsgs.add(msg);
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java:234]: The fact we do this in two places from the same if condition hints, to me at least, that we should extract a method for managing the buffer.

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandlerTest.java [hunk 8]
```diff
@@ -104,9 +111,73 @@ public static List<Arguments> provideArgsForExpectedFlow() {
...
+            assertThat(netFilterContext).isNotNull();
+        });
+        connectContext.get().initiateConnect(new HostPort(CLUSTER_HOST, CLUSTER_PORT), List.of());
+        assertEquals(State.CONNECTED, handler.state());
+
+        writeInboundApiVersionsRequest("post-connected");
+        assertThat(outboundChannel.outboundMessages()).isEmpty();
+        simulateOutboundChannelActive(handler);
+
+        assertOutboundContainsApiVersionsRequestWithClientSoftwardName("initial");
```
Comment (SamBarker) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandlerTest.java:140]: nit: typo? 
```suggestion
        assertOutboundContainsApiVersionsRequestWithClientSoftwareName("initial");
```

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandlerTest.java [hunk 9]
```diff
@@ -104,9 +111,73 @@ public static List<Arguments> provideArgsForExpectedFlow() {
...
     }
 
+    /**
+     * If the client sends multiple messages immediately when connecting they may all be read
+     * from the socket despite the inbound channel auto-read being disabled. We need to tolerate
+     * messages being handled while in the CONNECTED/CONNECTING state before the outbound signals
+     * it is active.
+     */
+    @Test
+    void testMultipleMessagesReceivedBeforeOutboundActive() {
```
Comment (SamBarker) [inline kroxylicious/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandlerTest.java:121]: Feels like this test is asserting two or three different behaviours in one go. 

1. The message ordering as seen by the `assertOutboundContainsApiVersionsRequestWithClientSoftwardName` calls. 
2. That the state machine still transitions at the right points to appropriate states
3. That it generates a netFilterContext
4. The channel gets drained at some point (maybe part of 1)

I think those should probably three separate test cases as they are independent reasons to fail tests.

It's not clear to me that the state transitions are tired to the other steps.

**Review by SamBarker — APPROVED** [review]
I think this is mergeable and my feedback can be iterated independently if preferred/

File: integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java (hunk 4 above)
Comment (robobario) [reply integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java:401]: On main it causes a timeout in the `get` of the futures and the state machine is transitioned to `FAILED`.

Comment (robobario) [reply integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java:401]: interesting, the state machine has several paths to this terminal FAILED state, but the inbound connection is only closed in one case, that's a failed connection to the upstream. Maybe we should make every FAILED transition close the inbound channel.

Comment (SamBarker) [reply integrationtests/src/test/java/io/kroxylicious/proxy/FilterIT.java:401]: > On main it causes a timeout in the `get` of the futures and the state machine is transitioned to `FAILED`.

Maybe add an assertion that the futures completed successfully rather than doing it implicitly by checking the values?

> Maybe we should make every FAILED transition close the inbound channel.


Intuitively it feels wrong that only one transition to failed kills the connection so I'd be in favour of updating it. Maybe @tombentley has some thoughts on the matter.

File: kroxylicious/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandlerTest.java (hunk 9 above)
Comment (robobario) [reply kroxylicious/src/test/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandlerTest.java]: Pushed up some improvements and splitting, but the nature of the class makes it kind of tricky to design small tests for individual behaviours since you have to drive it through all the transitions to get to your "initial" test state.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java (hunk 6 above)
Comment (robobario) [reply kroxylicious/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java]: I've done a bit of method extraction now if you want to have a look at the naming

**Comment by robobario** [comment]
Tested with the reproducer in the issue and it now looks good :+1: 

```
base64 -d - <<<AAAANAASAAMAAAAAABBjb25zb2xlLXByb2R1Y2VyABJhcGFjaGUta2Fma2EtamF2YQYzLjQuMAA=AAAANAASAAMAAAAAABBjb25zb2xlLXByb2R1Y2VyABJhcGFjaGUta2Fma2EtamF2YQYzLjQuMAA= | nc -x  127.0.0.1 9192
Sent 112 bytes to the socket
00000000  00 00 00 34  00 12 00 03  00 00 00 00  00 10 63 6F  ...4..........co
00000010  6E 73 6F 6C  65 2D 70 72  6F 64 75 63  65 72 00 12  nsole-producer..
00000020  61 70 61 63  68 65 2D 6B  61 66 6B 61  2D 6A 61 76  apache-kafka-jav
00000030  61 06 33 2E  34 2E 30 00  00 00 00 34  00 12 00 03  a.3.4.0....4....
00000040  00 00 00 00  00 10 63 6F  6E 73 6F 6C  65 2D 70 72  ......console-pr
00000050  6F 64 75 63  65 72 00 12  61 70 61 63  68 65 2D 6B  oducer..apache-k
00000060  61 66 6B 61  2D 6A 61 76  61 06 33 2E  34 2E 30 00  afka-java.3.4.0.
�=	
	

	
�12389:<=ABReceived 446 bytes from the socket
00000000  00 00 01 BA  00 00 00 00  00 00 3D 00  00 00 00 00  ..........=.....
00000010  09 00 00 01  00 00 00 0D  00 00 02 00  00 00 07 00  ................
00000020  00 03 00 00  00 0C 00 00  04 00 00 00  07 00 00 05  ................
00000030  00 00 00 04  00 00 06 00  00 00 08 00  00 07 00 00  ................
00000040  00 03 00 00  08 00 00 00  08 00 00 09  00 00 00 08  ................
00000050  00 00 0A 00  00 00 04 00  00 0B 00 00  00 09 00 00  ................
00000060  0C 00 00 00  04 00 00 0D  00 00 00 05  00 00 0E 00  ................
00000070  00 00 05 00  00 0F 00 00  00 05 00 00  10 00 00 00  ................
00000080  04 00 00 11  00 00 00 01  00 00 12 00  00 00 03 00  ................
00000090  00 13 00 00  00 07 00 00  14 00 00 00  06 00 00 15  ................
000000A0  00 00 00 02  00 00 16 00  00 00 04 00  00 17 00 00  ................
000000B0  00 04 00 00  18 00 00 00  03 00 00 19  00 00 00 03  ................
000000C0  00 00 1A 00  00 00 03 00  00 1B 00 00  00 01 00 00  ................
000000D0  1C 00 00 00  03 00 00 1D  00 00 00 03  00 00 1E 00  ................
000000E0  00 00 03 00  00 1F 00 00  00 03 00 00  20 00 00 00  ............ ...
000000F0  04 00 00 21  00 00 00 02  00 00 22 00  00 00 02 00  ...!......".....
00000100  00 23 00 00  00 04 00 00  24 00 00 00  02 00 00 25  .#......$......%
00000110  00 00 00 03  00 00 26 00  00 00 03 00  00 27 00 00  ......&......'..
00000120  00 02 00 00  28 00 00 00  02 00 00 29  00 00 00 03  ....(......)....
00000130  00 00 2A 00  00 00 02 00  00 2B 00 00  00 02 00 00  ..*......+......
00000140  2C 00 00 00  01 00 00 2D  00 00 00 00  00 00 2E 00  ,......-........
00000150  00 00 00 00  00 2F 00 00  00 00 00 00  30 00 00 00  ...../......0...
00000160  01 00 00 31  00 00 00 01  00 00 32 00  00 00 00 00  ...1......2.....
00000170  00 33 00 00  00 00 00 00  38 00 00 00  02 00 00 39  .3......8......9
00000180  00 00 00 01  00 00 3A 00  00 00 00 00  00 3C 00 00  ......:......<..
00000190  00 00 00 00  3D 00 00 00  00 00 00 41  00 00 00 00  ....=......A....
000001A0  00 00 42 00  00 00 00 00  00 43 00 00  00 00 00 00  ..B......C......
000001B0  00 00 00 01  01 08 00 00  00 00 00 00  00 00        ..............  
�=	
	

	
�12389:<=ABReceived 446 bytes from the socket
00000000  00 00 01 BA  00 00 00 00  00 00 3D 00  00 00 00 00  ..........=.....
00000010  09 00 00 01  00 00 00 0D  00 00 02 00  00 00 07 00  ................
00000020  00 03 00 00  00 0C 00 00  04 00 00 00  07 00 00 05  ................
00000030  00 00 00 04  00 00 06 00  00 00 08 00  00 07 00 00  ................
00000040  00 03 00 00  08 00 00 00  08 00 00 09  00 00 00 08  ................
00000050  00 00 0A 00  00 00 04 00  00 0B 00 00  00 09 00 00  ................
00000060  0C 00 00 00  04 00 00 0D  00 00 00 05  00 00 0E 00  ................
00000070  00 00 05 00  00 0F 00 00  00 05 00 00  10 00 00 00  ................
00000080  04 00 00 11  00 00 00 01  00 00 12 00  00 00 03 00  ................
00000090  00 13 00 00  00 07 00 00  14 00 00 00  06 00 00 15  ................
000000A0  00 00 00 02  00 00 16 00  00 00 04 00  00 17 00 00  ................
000000B0  00 04 00 00  18 00 00 00  03 00 00 19  00 00 00 03  ................
000000C0  00 00 1A 00  00 00 03 00  00 1B 00 00  00 01 00 00  ................
000000D0  1C 00 00 00  03 00 00 1D  00 00 00 03  00 00 1E 00  ................
000000E0  00 00 03 00  00 1F 00 00  00 03 00 00  20 00 00 00  ............ ...
000000F0  04 00 00 21  00 00 00 02  00 00 22 00  00 00 02 00  ...!......".....
00000100  00 23 00 00  00 04 00 00  24 00 00 00  02 00 00 25  .#......$......%
00000110  00 00 00 03  00 00 26 00  00 00 03 00  00 27 00 00  ......&......'..
00000120  00 02 00 00  28 00 00 00  02 00 00 29  00 00 00 03  ....(......)....
00000130  00 00 2A 00  00 00 02 00  00 2B 00 00  00 02 00 00  ..*......+......
00000140  2C 00 00 00  01 00 00 2D  00 00 00 00  00 00 2E 00  ,......-........
00000150  00 00 00 00  00 2F 00 00  00 00 00 00  30 00 00 00  ...../......0...
00000160  01 00 00 31  00 00 00 01  00 00 32 00  00 00 00 00  ...1......2.....
00000170  00 33 00 00  00 00 00 00  38 00 00 00  02 00 00 39  .3......8......9
00000180  00 00 00 01  00 00 3A 00  00 00 00 00  00 3C 00 00  ......:......<..
00000190  00 00 00 00  3D 00 00 00  00 00 00 41  00 00 00 00  ....=......A....
000001A0  00 00 42 00  00 00 00 00  00 43 00 00  00 00 00 00  ..B......C......
000001B0  00 00 00 01  01 08 00 00  00 00 00 00  00 00        ..............  
^C[roby@roby kroxylicious]
```
