### PR TITLE
Recover from EDEK decryption failures and improve KMS resilience measures

### LINKED ISSUE #793: Topic-encrypton: Handle EDEK decryption failures
Currently if the decryptEdek CompletionStage fails (so maybe something went wrong decryption the EDEK via the KMS), it remains cached and will generate failures in perpetuity as more produce requests are received. There is no logic to retry failed EDEK decryption.

We likely want to guarantee that we only have one attempt in flight to decrypt an EDEK for a kekId so there is some threading concerns to think about too.

We should likely update to use caffeine to match #788 if that is accepted as it handles some concerns for us like ensuring there is only one decrypt in progress per EDEK and we can use it's LRU features to bound the size of the decryptor cache and evict less-used Decryptors.

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Enhancement / new feature

### Description

**Hardcoded retry when KMS operations fail**. Previously a retry was only done for the EDEK generation. Now decryption and alias resolution both would be retried 3 times in the face of errors.

The retries around KMS operations now implement some degree of exponential backoff with jitter to try and protect the KMS a little from thundering herd problems.

**Recover if EDEK decryption stage fails**. Previously a failed  decryption stage would have been cached and future fetch requests for that EDEK would also have no chance of being decrypted.

Also adds a more specific exception for the case where we couldn't obtain an Encryptor with enough capacity to encrypt the batch after retrying. This is hard to name, it's not in the same class as say a failure to connect to the KMS. We could be happily obtaining valid EDEKs but for some reason never having capacity to encrypt this batch. It will be more of a concern when/if we start sharing encryption resources across channels as some other channel might have exhausted it.

Closes #793

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/ExponentialJitterBackoffStrategyTest.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+    public void testBackoffWithNoRandomJitter(double multiplier, Duration initialDelay, int failures, Duration expected) {
+        Random mockRandom = Mockito.mock(Random.class);
+        when(mockRandom.nextLong()).thenReturn(0L);
+        ExponentialJitterBackoffStrategy strategy = new ExponentialJitterBackoffStrategy(initialDelay,
+                Duration.of(20, ChronoUnit.SECONDS), multiplier, mockRandom);
+        Duration delay = strategy.getDelay(failures);
+        assertThat(delay).isEqualTo(expected);
+    }
+
+    private static Stream<Arguments> testCappedToMaximumMaximum() {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/ExponentialJitterBackoffStrategyTest.java:55]: MaximumMaximum :woman_facepalming:

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/inband/InBandKeyManagerTest.java [hunk 2]
```diff
@@ -270,6 +318,47 @@ void afterWeFailToLoadADekTheNextEncryptionAttemptCanSucceed() {
         assertThat(encrypted).hasSize(2);
     }
 
+    @Test
+    void afterWeFailToDecryptAnEDekTheNextEncryptionAttemptCanSucceed() {
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/inband/InBandKeyManagerTest.java:322]: From my commit:

> Note: the testing required is ugly, Sam commented on this for the EDEK
> PR too. It's tough because the InBandKeyManager knows the parcel format
> and we don't have test utilities to independently generate examples of
> parcels yet. If we had the ability to generate serialized record examples
> we could avoid going through an encrypt cycle with a real KMS implementation
> just to get properly serialized records.

But keen to keep it separate

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/EdekReservationFailureException.java [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+ * Indicates a failure to obtain an Encryptor that can encrypt an entire batch.
+ * <p>
+ * A detail of the encryption algorithm is that we obtain an Encryptor object that
+ * is only allowed to encrypt a certain number of records. If it is exhausted we
+ * will try again, obtaining another encryptor and checking if it has encryptions
+ * remaining. If we cannot obtain an encryptor with enough remaining encryptions
+ * after some amount of retries this exception is thrown.
+ * </p>
+ */
+public class EdekReservationFailureException extends EncryptionException {
```
[the remark this answers is not in the document]
Comment (SamBarker) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/EdekReservationFailureException.java:21]: Why does it need to be Edek specific ? Seems like a specific incantation of a generic problem. `UnsatisfyableRequest`?

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/ExponentialJitterBackoffStrategy.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+        }
+        Duration backoff = getExponentialBackoff(failures);
+        backoff = backoff.plus(getRandomJitter(failures, backoff));
+        return backoff.compareTo(maximumDelay) < 0 ? backoff : maximumDelay;
+    }
+
+    private Duration getRandomJitter(int failures, Duration backoff) {
+        Duration prior = getExponentialBackoff(failures - 1);
+        long maxJitter = backoff.toMillis() - prior.toMillis();
+        return Duration.ofMillis(this.random.nextLong() % maxJitter);
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/ExponentialJitterBackoffStrategy.java:50]: So, if this backoff is 1.5 seconds, the previous backoff was 1 second, then the jitter will be 1.5 seconds plus or minus 500ms.

So the jittering range gets exponentially bigger along with the backoff.

Another approach is to have a randomization factor, so that you say "jitter within +-10%" so a 1 second delay would be jittered to be randomized within 0.9s and 1.1s.

Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/ExponentialJitterBackoffStrategy.java:50]: think this should guard against `% 0` in case things are arranged such that `delay-n == delay-n+1`

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/EnvelopeEncryption.java [hunk 5]
```diff
@@ -6,6 +6,9 @@
 
 package io.kroxylicious.filter.encryption;
 
+import java.time.Duration;
+import java.util.concurrent.ThreadLocalRandom;
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/EnvelopeEncryption.java:10]: I didn't know about this.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+ * Copyright Kroxylicious Authors.
+ *
+ * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
+ */
+
+package io.kroxylicious.filter.encryption;
+
+import java.time.Duration;
+
+public interface BackoffStrategy {
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java:11]: I wonder if this might end up being something with utility outside encryption, but I'm happy that we wait and see what emerges as we get into other use-cases.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+
+    /**
+     * Decides how long to delay the next attempt at an action given it has failed
+     * for N consecutive times in the past.
+     * @param failures count of failures
+     * @return how long to delay
+     */
+    Duration getDelay(int failures);
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java:19]: Do you foresee a backoff strategy needing to communicate "give up"?

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/ExponentialJitterBackoffStrategy.java [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+        if (multiplier <= 1.0d) {
+            throw new IllegalArgumentException("multiplier must be greater than one");
+        }
+        if (initialDelay.compareTo(Duration.ZERO) <= 0) {
+            throw new IllegalArgumentException("initialDelay must be greater than zero");
+        }
+        if (maximumDelay.compareTo(Duration.ZERO) <= 0) {
+            throw new IllegalArgumentException("maximumDelay must be greater than zero");
+        }
+        this.initialDelay = initialDelay;
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/ExponentialJitterBackoffStrategy.java:36]:
```suggestion
        this.initialDelay = initialDelay;
        Objects.requireNotNull(random)
```

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java [hunk 9]
```diff
@@ -0,0 +1,20 @@
...
+package io.kroxylicious.filter.encryption;
+
+import java.time.Duration;
+
+public interface BackoffStrategy {
+
+    /**
+     * Decides how long to delay the next attempt at an action given it has failed
+     * for N consecutive times in the past.
+     * @param failures count of failures
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java:16]: would you expect failures to be always > 0?

**Review by k-wall — APPROVED** [review]
Looks good to me.  Couple of questions/comments left.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java (hunk 9 above)
Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java:16]: I'll document it, it expects `>=0` so you can ask for a backoff on every request without having to special case the first request (0-failures case).

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java (hunk 7 above)
Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java:19]: I don't think the BackoffStrategy should be what makes that decision, I imagine something else knowing about retry limits and combining that with the backoff strategy.

I think the Retry logic could be more involved with `CompletionStages` and trigger the `exceptionallyCompose` type logic. So it could look something more like:

```
Retrier retrier = Retrier.create(maxAttempts, executor, backoffStrategy)
..
Supplier<CompletionStage<X>> heavyWork;
CompletionStage<X> = retrier.apply(heavyWork)
```

I'm trying not to pull in the world of dependencies but I think the API of [resilience4j](https://resilience4j.readme.io/docs/retry) is something to imitate here.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java (hunk 6 above)
Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java:11]: Yeah I think so, but needs some thought, similar to the thought about whether having some `ByteBuffer` manipulation classes somewhere common would be useful to Filter authors. I'm cautious about having some `commons-lang` type lib that could end up being used in Filters and the Proxy implementation with all these things depending on it's APIs. 

Maybe we could have a lib named like `filter-support`, it could be targeted at Filter Authors and we would specify that it's not on the classpath of Kroxy by default but is to be user managed.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/EdekReservationFailureException.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/EdekReservationFailureException.java]: :+1: Have refactored to an `RequestNotSatisfiable` exception. You are correct we could dream up other cases. Like in the future if/when we make the max-encryptions-per-DEK configurable it's more likely that a user could end up with `recordsInBatch > maxEncryptionsPerDek` which we could fail fast on.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java (hunk 7 above)
Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/BackoffStrategy.java:20]: On that, I'll come back in another PR and see how it looks with a resilience lib dropped in, can debate if we want to add a dependency there.

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/EdekReservationFailureException.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (robobario) [reply kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/inband/EdekReservationFailureException.java]: (Sam pointed out that we should be able to refactor to use multiple DEKs to encrypt one batch, spoilsport)
