### PR TITLE
Do not expose unknown APIs to the client

### LINKED ISSUE #444: ApiVersionsFilter exposes unknown ApiKeys from the broker to the client
> Also pushed up a test for a suspicious behaviour of the ApiVersionsFilter. That is that it does not remove unknown ApiKeys returned by the broker. If clients attempted to request these ApiKeys then Kroxylicious would throw an exception in the KafkaRequestDecoder when it's trying to determine what the ApiKey is. I think we should remove filter out unknown ApiKeys, removing them from the response.

_Originally posted by @robobario in https://github.com/kroxylicious/kroxylicious/issues/443#issuecomment-1629875369_

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

If we encounter unknown ApiKeys when intercepting the broker ApiVersionsResponse, we drop them so they are not exposed to clients.

Why:
If the broker is ahead of Kroxylicious and is offering a new RPC, but Kroxylicious does not know how to handle it we do not want to tell the client that we support that RPC. If the client sent that RPC to us we would fail to decode the request with an exception. So we remove unknown ApiKeys from the ApiVersionsResponse when intersecting with Kroxylicious's supported versions.

Resolves #444

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java [hunk 1]
```diff
@@ -75,9 +76,8 @@ public void shouldOfferTheMaximumLowestSupportedVersionWhenKroxyliciousIsAheadOf
         }
     }
 
-    // TODO we think this is a bug but will come back to it
     @Test
-    public void shouldOfferBrokerApisThatAreUnknownToKroxy() {
+    public void shouldNotOfferBrokerApisThatAreUnknownToKroxy() {
```
Comment (k-wall) [inline integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java:80]: The test would pass if the production code had a bug that dropped all api keys from the response in the presence of a single unknown one.

I think the test would be stronger if it added two apiKeys (line 86), one known, and one unknown.  The test would then assert that only the known one makes it to the client.

**Review by k-wall — APPROVED** [review]
Implementation looks good to me.

File: integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java (hunk 1 above)
Comment (SamBarker) [reply integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java:80]: Getting back on my "one reason to fail" soap box. I think @k-wall is making a great point *but* it's two separate tests. 

Tests:
1. `shouldNotOfferBrokerApisThatAreUnknownToKroxy` should assert that unknown API's are removed (as it does).
2. `shouldOfferBrokerApisThatAreKnownToKroxy` is the extension behaviour @k-wall outlines. 

I say this because if we only had test 2. and it fails in 6 months time, we don't know what went wrong we just know something changed in the filtering as there are two possible causes. 1. We stopped filtering an unknown API (maybe the API key stopped being unknown, maybe we broke it) or 2. We stopped including the known APIs. 

So for me the value of having two tests comes later. 



Now all this comes with the caveat of being slower to execute (we have to spool everything up twice), for the moment I'd argue we are not that sensitive to the build time and thus can afford it. There is also an argument about duplication but I think we already have the right abstractions in place to make that minimal and naming the test cases well (that is to say giving each one a meaningful name) mitigates that by showing the difference in intent.

File: kroxylicious/src/main/java/io/kroxylicious/proxy/internal/filter/ApiVersionsFilter.java [hunk 2]
```diff
@@ -23,12 +26,19 @@ public class ApiVersionsFilter implements ApiVersionsResponseFilter {
...
                 ApiKeys apiKey = ApiKeys.forId(apiId);
                 intersectApiVersion(channel, key, apiKey);
             }
+            else {
+                toDelete.add(key);
+            }
+        }
+        for (ApiVersionsResponseData.ApiVersion apiVersion : toDelete) {
+            resp.apiKeys().remove(apiVersion);
         }
```
Comment (SamBarker) [inline kroxylicious/src/main/java/io/kroxylicious/proxy/internal/filter/ApiVersionsFilter.java:42]: Nit on the set naming:
```suggestion
        Set<ApiVersionsResponseData.ApiVersion> unknownApis = new HashSet<>();
        for (var key : resp.apiKeys()) {
            short apiId = key.apiKey();
            if (ApiKeys.hasId(apiId)) {
                ApiKeys apiKey = ApiKeys.forId(apiId);
                intersectApiVersion(channel, key, apiKey);
            }
            else {
                unknownApis.add(key);
            }
        }
        resp.apiKeys().removeAll(unknownApis);
```

**Review by SamBarker — APPROVED** [review]
Thanks for following up on this @robobario

File: integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java (hunk 1 above)
Comment (robobario) [reply integrationtests/src/test/java/io/kroxylicious/proxy/ApiVersionsIT.java:83]: I've pushed up the inverse test `shouldOfferBrokerApisThatAreKnownToKroxy` to check all known ApiKeys can be represented.
