### PR TITLE
Fix #1691: Remove hardcoded project version references from the Operator

### LINKED ISSUE #1691: Operator proxy image version not updated by release automation
**Describe the bug**

After releasing 0.9.0, the operator code still refers to the kroxylicious 0.9.0-SNAPSHOT image. See #1689 

When we release the proxy we have automation to modify the project version in our maven build and in example kubernetes manifests. The recently added operator also refers to a proxy image that it will deploy. This image version (and the version checked in unit tests) is not covered by the release automation.

**Expected behavior**
When the stage release action is run:
1. in the release version commit, the operator code should refer to the released kroxylicious image
2. in the next-development-version commit, the operator code should refer to the next-development-version kroxylicious image

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Remove hardcoded project version references from the Operator
why: avoid stale references during the release.

### Additional Context

Using Maven resources filtering seems to be must straight-forward/least surprising solution.

I also expose an environment variable `KROXYLICIOUS_IMAGE`, letting uses of the operator inject the operand image
via an environment.  I envisage this might be useful for adhoc testing, or for Kroxyliciuous deriatives. 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] PR raised from a fork of this repository and made from a branch rather than main. 
- [x] Write tests
- [ ] Update documentation
- [x] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [x] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyDeployment.java [hunk 1]
```diff
@@ -134,4 +137,31 @@ private static Container proxyContainer(KafkaProxy primary,
         return containerBuilder.build();
         // @formatter:on
     }
+
+    private static String getOperandImage() {
```
Comment (robobario) [inline kroxylicious-operator/src/main/java/io/kroxylicious/kubernetes/operator/ProxyDeployment.java:141]: might be worth logging what image we picked and where it was sourced from?

**Review by robobario — APPROVED** [review]
LGTM

**Comment by k-wall** [comment]
@robobario can I ask for a re-rereview?  I've adopted the maven convention of [`src/main/resources-filtered`](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html#:~:text=If%20you%20have%20both%20text%20files%20and%20binary%20files%20as%20resources%20it%20is%20recommended%20to%20have%20two%20separated%20folders.%20One%20folder%20src/main/resources%20(default)%20for%20the%20resources%20which%20are%20not%20filtered%20and%20another%20folder%20src/main/resources%2Dfiltered%20for%20the%20resources%20which%20are%20filtered.) to make it clear which resources are to be filtered and which aren't.    Can I ask you check that your IDE is picking this up okay?   It is working fine for me.

**Comment by k-wall** [comment]
"[0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=kroxylicious_kroxylicious&pullRequest=1759&metric=new_coverage&view=list) (required ≥ 76%)"

^^ I'd don't understand that.  I can see from the Sonar run that the new test is being execute, so it should have coverage.

**Comment by k-wall** [comment]
I suggest we ignore the coverage quality gate in this case.  It corresponds to error conditions that are unlikely to occur.

**Review by robobario — APPROVED** [review]
Yep, the change to `resources-filtered` worked in IDEA without having to do anything :+1:
