### PR TITLE
bugfix(test): stabilise non-deterministic produce authz tests

### LINKED ISSUE #3410: ProduceAuthzTxnlIdIT failed on CI
Seems we have another sporadically failing test.

https://github.com/kroxylicious/kroxylicious/actions/runs/22715274566/job/65863310378

```
Error:  Errors: 
Error:    ProduceAuthzTxnlIdIT.shouldEnforceAccessToTopics:285->AuthzIT.verifyApiEquivalence:558 » ConditionTimeout Condition with alias 'assertions about visible side effects' didn't complete within 1 minutes because assertion condition defined as a Lambda expression in io.kroxylicious.it.filter.authorization.AuthzIT 
```

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Bugfix

### Description

Set batch logAppendTime and record timestamps to current epoch ms when generating test data.

Closes #3410

Why:
I noticed that the tests were failing about 30 seconds after the parameterized tests of `ProduceAuthzIT` and `ProduceAuthzTxnlIdIT` ran. I debugged this and found it failed at the same time as the LogManager `initialTaskDelayMs` of 30 seconds and by modifying the broker `log.initial.task.delay.ms` I could influence when the failure occured. Through some kafka debug logging I discovered that the segment was eligible for soft deletion because the max timestamp in the batch was 0, aka Jan 1st 1970. The test uses hand-rolled MemoryRecords and we had it hard-coded to 0.

So the flow was something like:
1. test creates topic
2. test sends MemoryRecords to topic with max timestamp 0
3. LogCleaner runs and soft-deletes the segment due to retention breach
4. test tries to consume and finds no records, retry until timeout

By setting up the append time and timestamp more realistically we should avoid the segment being eligible for deletion between Produce and Consume.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] PR raised from a fork of this repository and made from a branch rather than main. 
- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, make sure system tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/filter/authorization/ProduceAuthzIT.java [hunk 1]
```diff
@@ -201,19 +201,20 @@ private Map<String, List<String>> topicContents(KafkaCluster unproxiedCluster, i
     private static List<ProduceRequestData.PartitionProduceData> partitionData(String key, String value) {
         // It's important to use different pid different client instances, else ProduceReequests will get fenced out
         long producerId = pid++;
+        long currentTimeMillis = System.currentTimeMillis();
```
Comment (robobario) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/filter/authorization/ProduceAuthzIT.java:204]: This should prevent deletion, but introduces a new variable to the test.

Another way would be to configure the initial delay of the Log Manager jobs to an enormous number, to prevent LogCleaning during the test. But then we're testing with sort of surprising data that doesn't look like a typical client Produce, which might be more of a problem for an integration with the real Kafka broker.

Comment (robobario) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/filter/authorization/ProduceAuthzIT.java:204]: I feel like the 0 timestamp is more of a landmine than having a variable timestamp for this test

**Comment by k-wall** [comment]
Great sleuthing @robobario

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/filter/authorization/ProduceAuthzIT.java (hunk 1 above)
Comment (k-wall) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/it/filter/authorization/ProduceAuthzIT.java:204]: I think your current solution seems good enough.  I suppose the alternative is to set `log.initial.task.delay.ms` to some really large value, however, that means we are running the broker in an abnormal configuration - which could bring its own issues

I hope the proxy tests will never actually need to care about log cleaning.
