### PR TITLE
Fix #841: ensure envelope encryption filter transits record offsets unchanged.

### LINKED ISSUE #841: Envelope encryption assumes offsets are consecutive.
**Describe the bug**

EnvelopeEncryptionFilter#recordsBuilder is careful to pass the `baseOffset` from the incoming records when creating the Builder.
This means we are guaranteed that the first record will have the same offset as was sent by the peer.   If the partition has more than one record, subsequent records will be given baseOffset+1 and so forth.   This works okay - unless the original offsets are not consecutive (as would be the case with a compacted topic).    As things stand I believe the fetch path could have the affect of renumbering the records.   This'll cause chaos as the offset accounting will be off.  

I think we ought to be using `appendWithOffset` so that the offsets are preserved.

We ought to have test cases to ensure offset fidelity.

I think Sample might exhibit the same issue.

**To Reproduce**

I haven't verified this issue.  Inference from looking at the code.

1. Configure kroxylicious like this ...
2. Run command '....'
3. See error

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Bugfix

### Description

Filters that intercept `ProduceRequest`s/`FetchResponse`s (such as the `EnvelopeEncryptionFilter`) must take care not to cause the record offsets to be renumbered as the records transits the filter _unless_ the filter is also intercepting other RPCs (FetchOffsets etc) to ensure offset accounting is consistent across the API.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [x] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

File: kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilter.java [hunk 1]
```diff
@@ -92,7 +92,7 @@ private CompletionStage<ProduceRequestData> maybeEncodeProduce(ProduceRequestDat
                                     ppd.index(),
                                     new EncryptionScheme<>(kekId, EnumSet.of(RecordField.RECORD_VALUE)),
                                     encryptionRequests,
-                                    (kafkaRecord, encryptedValue, headers) -> builder.append(kafkaRecord.timestamp(), kafkaRecord.key(), encryptedValue, headers))
+                                    (kafkaRecord, encryptedValue, headers) -> builder.appendWithOffset(kafkaRecord.offset(), kafkaRecord.timestamp(), kafkaRecord.key(), encryptedValue, headers))
```
Comment (k-wall) [inline kroxylicious-filters/kroxylicious-encryption/src/main/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilter.java:95]: On the produce path, I'm not sure if using `#append()` would actually cause a defect.  It is the broker that assigns the offset to the record, so I *think* the offset in the record on the produce path will be ignored anyway.  However, I think it will keep the world simpler if we retain the offset from producer -> broker.  This has the advantage of symmetry with the fetch path, and will help keep debugging/tracing easy.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 2]
```diff
@@ -248,6 +257,77 @@ void produceAndConsumeEncryptedAndPlainTopicsAtSameTime(KafkaCluster cluster, To
...
+     * @param cluster underlying kafka cluster
+     * @param compactedTopic topic configured for compaction.
+     * @param directConsumer consumer connected directly to the underlying kafka cluster
+     * @param testKmsFacade kms facade
+     * @throws Exception exception
+     */
+    @TestTemplate
+    @SuppressWarnings("java:S2925")
+    void offsetFidelity(@BrokerConfig(name = "log.cleaner.backoff.ms", value = "500") @BrokerConfig(name = "log.retention.check.interval.ms", value = "500") KafkaCluster cluster,
+                        @TopicConfig(name = "segment.ms", value = "250") @TopicConfig(name = "cleanup.policy", value = "compact") Topic compactedTopic,
```
Comment (tombentley) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:271]: It's sad that the formatting makes this so unreadable, but not your fault.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 3]
```diff
@@ -248,6 +257,77 @@ void produceAndConsumeEncryptedAndPlainTopicsAtSameTime(KafkaCluster cluster, To
...
+        try (var tester = kroxyliciousTester(builder);
+                var proxyProducer = tester.producer();
+                var proxyConsumer = tester.consumer()) {
+
+            proxyProducer.send(new ProducerRecord<>(compactedTopic.name(), "a", "a1"));
+            // Send two messages for key "b", the first will be eligible for compaction
+            proxyProducer.send(new ProducerRecord<>(compactedTopic.name(), "b", "b1"));
+            proxyProducer.send(new ProducerRecord<>(compactedTopic.name(), "b", "b2")).get(5, TimeUnit.SECONDS);
+
+            // Sleep for > segment.ms to that the next segment will begin and first will become eligible for compaction
```
Comment (tombentley) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:291]:
```suggestion
            // Sleep for > segment.ms so that the next segment will begin and first will become eligible for compaction
```

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 4]
```diff
@@ -248,6 +257,77 @@ void produceAndConsumeEncryptedAndPlainTopicsAtSameTime(KafkaCluster cluster, To
...
+            Thread.sleep(250);
```
Comment (tombentley) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:292]: This rests on the assumption that the log cleaner thread will definitely run to completion at least once in 250ms. That's definitely not guaranteed, so this is likely to be flaky. We can make it _less_ flaky is we use something like 2×segment.ms. For higher self-documentation value we could factor out an `awaitCompaction` method, even if is just calls sleep right now.

**Review by tombentley — COMMENTED** [review]
Thanks @k-wall!

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 4 above)
Comment (k-wall) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:292]: The intent of the code is to allow sufficient time for the broker to be obligated to start a new segment.  Is the log cleaner really involved in this in this part?  I looked at `kafka.log.UnifiedLog#maybeRoll` which appeared to me to be called on the append path.  I noticed the method is called by a thread 'data-plane-kafka-request-handler-x' which appears to be serving requests rather than have a cleaning role.   _I don't know the Kafka code well so I could very well be misunderstanding the broker under the debugger or making spurious inferences._ 

I think where I do need to wait for the log cleaner to act is the next part.  Here I've used Awaitility to consume repeatedly until the records appear in the 'right' compacted shape.

I think therefore my Thread.sleep(segment.ms) is okay.  Sufficient time will have passed so the Broker is forced to start a new segment before it can write `c`. 

My application of `log.retention.check.interval.ms` is superfluous.  Log retention has no part to play in this text.

**Comment by k-wall** [comment]
I'm not happy with the last commit, but any feedback would be apperciated.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 4 above)
Comment (tombentley) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java]: OK, yes, I think you're right

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java [hunk 5]
```diff
@@ -203,12 +239,64 @@ void shouldDecryptEncryptedRecords() {
...
+
+                            // Yikes!
+                            var offsets = fetchResponseData.responses().stream()
+                                    .flatMap(pd -> pd.partitions().stream())
+                                    .map(PartitionData::records)
+                                    .map(org.apache.kafka.common.record.Records.class::cast)
+                                    .flatMap(r -> StreamSupport.stream(r.records().spliterator(), false))
+                                    .map(Record::offset).toList();
+//                            System.out.println(offsets);
+                            return Objects.equals(offsets, List.of(0L, 2L, 3L));
```
Comment (robobario) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java:288]: Might be nice to pull out `List.of(0L, 2L, 3L)` into an `initialOffsets` variable and use it at L245, and rename `offsets` to something like `forwardedOffsets`.

**Comment by robobario** [comment]
pushed up reformat/imports FYI @k-wall, just realised you might be in the process of improving the reformatted test

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 6]
```diff
@@ -248,6 +257,78 @@ void produceAndConsumeEncryptedAndPlainTopicsAtSameTime(KafkaCluster cluster, To
...
+     * @param cluster underlying kafka cluster
+     * @param compactedTopic topic configured for compaction.
+     * @param directConsumer consumer connected directly to the underlying kafka cluster
+     * @param testKmsFacade kms facade
+     * @throws Exception exception
+     */
+    @TestTemplate
+    @SuppressWarnings("java:S2925")
+    void offsetFidelity(@BrokerConfig(name = "log.cleaner.backoff.ms", value = "50") KafkaCluster cluster,
+                        @TopicConfig(name = "segment.ms", value = "125") @TopicConfig(name = "cleanup.policy", value = "compact") Topic compactedTopic,
```
Comment (SamBarker) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:271]: I get that `compact` is the more complicated policy and thus the one we need to ensure fidelity with, but should we also have a version of the test with a non compact topic?

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 7]
```diff
@@ -248,6 +257,78 @@ void produceAndConsumeEncryptedAndPlainTopicsAtSameTime(KafkaCluster cluster, To
...
+                var proxyConsumer = tester.consumer()) {
+
+            proxyProducer.send(new ProducerRecord<>(compactedTopic.name(), "a", "a1"));
+            // Send two messages for key "b", the first will be eligible for compaction
+            proxyProducer.send(new ProducerRecord<>(compactedTopic.name(), "b", "b1"));
+            proxyProducer.send(new ProducerRecord<>(compactedTopic.name(), "b", "b2")).get(5, TimeUnit.SECONDS);
+
+            // Sleep for segment.ms so that the broker will begin a new segment when the next produce is received.
+            // The records in the first segment will become eligible for compaction.
+            Thread.sleep(125);
```
Comment (SamBarker) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:293]: Are segments rolled based on a background timer or on elapsed time between records? Just wondering if we need a longer delay to ensure the segment has actually been rolled. (ideally we would have some mechanism to detect the roll and await that, but we do not live in that sort of world)

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java [hunk 8]
```diff
@@ -248,6 +257,78 @@ void produceAndConsumeEncryptedAndPlainTopicsAtSameTime(KafkaCluster cluster, To
...
+            proxyProducer.send(new ProducerRecord<>(compactedTopic.name(), "c", "c1")).get(5, TimeUnit.SECONDS);
+
+            // Wait until the topic compaction has coalesced the two b records into one.
+            // This will result in a gap in the offsets.
+            var directlyReadRecords = await().atMost(Duration.ofSeconds(30))
+                    .pollDelay(Duration.ofSeconds(1))
+                    .until(() -> consumeAll(compactedTopic.name(), 0, directConsumer).map(EnvelopeEncryptionFilterIT::stringifyRecordKeyOffset).toList(),
+                            Matchers.contains("a:0", "b:2", "c:3"));
```
Comment (SamBarker) [inline kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:301]: The contains confuses me as the produced records are `a1, b1, b2, c1` but the assertion only checks for `0, 2, 3`....

OH wait no the assertion is checking the offset not the value! Ok. that is actually demonstrating what we want but certainly surprised me on first pass.  

It does lead me to wonder if we should be including the value as well to prove we didn't do something screwy and some how produce `b1` at offset `2` (I can't think of a realistic way for us to do that but want to test the idea)

**Review by SamBarker — APPROVED** [review]
I found the test a little confusing but it does what we need so any changes are optional.

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java [hunk 9]
```diff
@@ -233,6 +239,58 @@ void shouldDecryptEncryptedRecords() {
...
+
+        // When
+        encryptionFilter.onFetchResponse(ProduceResponseData.HIGHEST_SUPPORTED_VERSION,
+                new ResponseHeaderData(), encryptedFetchResponse, context);
+
+        // Then
+        verify(context, times(1)).forwardResponse(any(ResponseHeaderData.class), assertArg(actualFetchResponse -> assertThat(actualFetchResponse)
+                        .isInstanceOf(FetchResponseData.class)
+                        .asInstanceOf(InstanceOfAssertFactories.type(FetchResponseData.class))
+                        .has(new FetchResponseDataCondition(fetchResponseData -> {
```
Comment (SamBarker) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java]: Nice to see the `FetchResponseDataCondition` being used, but I don't think is adding a lot of value yet. 

The hard part is adding the smarts to the code generator to make the conditions more aware of what we might want to assert about. Any and all thoughts gratefully appreciated.

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java [hunk 10]
```diff
@@ -233,6 +239,58 @@ void shouldDecryptEncryptedRecords() {
...
+//                                });
+//
+//                            });
+
+                            // Yikes!
+                            var offsets = fetchResponseData.responses().stream()
+                                    .flatMap(pd -> pd.partitions().stream())
+                                    .map(PartitionData::records)
+                                    .map(org.apache.kafka.common.record.Records.class::cast)
+                                    .flatMap(r -> StreamSupport.stream(r.records().spliterator(), false))
```
Comment (SamBarker) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java]: This feels very similar to something I was poking at recently. I wonder about pulling this out a util function returning a `Stream<kafka.Record>`

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java [hunk 11]
```diff
@@ -233,6 +239,58 @@ void shouldDecryptEncryptedRecords() {
...
+            return CompletableFuture.completedFuture(null);
+        });
+
+        // When
+        encryptionFilter.onFetchResponse(ProduceResponseData.HIGHEST_SUPPORTED_VERSION,
+                new ResponseHeaderData(), encryptedFetchResponse, context);
+
+        // Then
+        verify(context, times(1)).forwardResponse(any(ResponseHeaderData.class), assertArg(actualFetchResponse -> assertThat(actualFetchResponse)
+                        .isInstanceOf(FetchResponseData.class)
```
Comment (SamBarker) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java]: I think the `FetchResponseDataCondition` does this for you and I think it implies 268 as well but I'd need to check that.

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java [hunk 12]
```diff
@@ -233,6 +239,58 @@ void shouldDecryptEncryptedRecords() {
...
+                .setPartitions(List.of(new PartitionData().setRecords(recsWithNonConsecutiveOffsets))));
+
+        when(keyManager.decrypt(any(), anyInt(), assertArg(records -> assertThat(records).hasSize(3)), any(Receiver.class))).thenAnswer(invocationOnMock -> {
+            final List<Record> records = invocationOnMock.getArgument(2);
+            final Receiver receiver = invocationOnMock.getArgument(3);
+
+            // Oh my!!
+            records.forEach(r -> {
+                receiver.accept(r, ByteBuffer.wrap(HELLO_PLAIN_WORLD), Record.EMPTY_HEADERS);
+            });
```
Comment (SamBarker) [inline kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java:256]: @tombentley is working on a PR to kill the receiver! 🎉

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 2 above)
Comment (SamBarker) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java]: Is there a case for `@BrokerConfigs(keys = [], values = [])` and use matching array indexes to make it more readable? A bit ugly in theory but with a some bounds checking its probably good enough in practice?

**Review by SamBarker — APPROVED** [review]

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 2 above)
Comment (k-wall) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java]: Something to make broker/topic/producer/consumer more succinct would be desirable.

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java (hunk 5 above)
Comment (k-wall) [reply kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java]: Done.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 6 above)
Comment (k-wall) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:271]: Yes, I agree there's scope for more testing.  One case that's not covered is the case where a topic's offset begin at a > 0 value on the broker (i.e. after retention rules have caused a segment to be deleted).  I think are rather leave this kind of thing for another PR.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 7 above)
Comment (k-wall) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:293]: > Are segments rolled based on a background timer or on elapsed time between records? 

AFAIK it is actually the produce path that detects the need to roll the segment.  There's no background thread involvement. I talked about this in this thread. https://github.com/kroxylicious/kroxylicious/pull/850#discussion_r1441626972

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java (hunk 11 above)
Comment (k-wall) [reply kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java]: Agreed.. fixed.

File: kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java (hunk 9 above)
Comment (k-wall) [reply kroxylicious-filters/kroxylicious-encryption/src/test/java/io/kroxylicious/filter/encryption/EnvelopeEncryptionFilterTest.java]: I'd wondered about this too.  I don't have any ideas right now, but I'll think on it.

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 8 above)
Comment (k-wall) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java]: If I were to have the stringification of record include the _value_, the resulting string would contain the encrypted bytes.  So I'd no longer be able to make the assertion between the value obtained from the proxy and the value obtained directly.

**Comment by k-wall** [comment]
@SamBarker and @robobario Hopefully the comments are addressed.  Could you take another looks?

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 6 above)
Comment (SamBarker) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:271]: Yeah happy to leave for a new PR

**Review by robobario — APPROVED** [review]
LGTM, thanks Keith

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 7 above)
Comment (SamBarker) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java:293]: Yes, re-reading that comment did answer my question

File: kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java (hunk 8 above)
Comment (SamBarker) [reply kroxylicious-integration-tests/src/test/java/io/kroxylicious/proxy/encryption/EnvelopeEncryptionFilterIT.java]: Yeah. That would rule out comparisons between the clusters. 

My two thoughts are:
1. Could we change the values to look more distinct from the offsets. `value_AA`  `value_BA` `value_BB` ... ?
2. Do we need an additional test to check the values at given offsets?  

I'm happy for 1 to be addressed without another review cycle and 2 happen in a separate PR if you feel it adds value.

**Review by SamBarker — APPROVED** [review]
LGTM thanks @k-wall
